== Prefacio

Antes de presentar esta pequeña selección al público,
el compilador considera necesario observar que muchos de los materiales fueron
transcritos tiempo atrás para su propio beneficio--y que en años pasados,
solía presentar ocasionalmente éstos y muchos otros extractos de
los escritos de los Amigos entre el círculo de sus amigos más íntimos,
y que posteriormente se vio persuadido, durante una época de mucha aflicción personal,
a adaptarlos y prepararlos para su impresión. Su principal objetivo, en primer instancia,
era instruir a los jóvenes de la Sociedad a la que pertenece,
pero a medida que la obra crecía bajo su mano,
no podía evitar desear para ella una distribución menos confinada.
El compilador no duda que el ojo crítico tendrá presente el estilo de aquellos
escritores que vivieron en una época menos refinada que la presente (la mayoría
de los cuales había recibido a lo sumo una educación básica y útil),
y cuyo mayor deseo en las obras dirigidas a sus semejantes,
era dirigirse con sencillez al corazón y a la conciencia.
La "`excelencia de palabras,`" o las "`palabras persuasivas de humana sabiduría,`"^
footnote:[1 Corintios 2:1,4]
no eran el objetivo de ellos.
De hecho, la precisión y la redacción correcta a veces están casi ausentes;
de modo que por este y otros motivos se han tomado ocasionalmente
algunas muy leves libertades con el texto de los autores.

El compilador también añade, que de algunas observaciones que se ha atrevido a insertar,
él es sin duda alguna, el único responsable.

John Barclay

Londres, noveno día del quinto mes.
