== Capítulo I

[.centered]
=== George Fox y el Carcelero

En el año 1650, George Fox fue puesto en prisión en Derby,
donde permaneció confinado cerca de un año. El guarda de la prisión,
un orgulloso profesante de la religión, estaba muy enfurecido contra G. Fox,
hablaba malvadamente de él,
y a menudo intentaba sacarle alguna palabra imprudente con la que pudiera acusarlo.
Pero George se mantenía en una conducta tan inocente y prudente,
que aunque sus palabras y acciones eran cuidadosamente observadas,
no se le podía achacar ninguna falta.
Lo siguiente está expresado en sus propias palabras:

[.embedded-content-document]
--

Le plació al Señor golpear un día al carcelero,
de modo que estaba bajo gran angustia y terror mental.
Mientras caminaba en su cámara, oí un clamor de dolor, y quedándome quieto para escuchar,
oí al guarda decirle a su esposa: "`Esposa,
he visto el día del juicio y vi a George allí,
y tenía miedo de él porque le he hecho mucho mal;
he hablado mucho contra él a los ministros, profesantes y jueces,
en tabernas y cervecerías.`" Después de esto, casi de noche,
el guarda entró a mi cámara y me dijo: "`He sido como un león contra ti,
pero ahora vengo como un cordero,
y como el carcelero que llegó donde Pablo y Silas temblando.`"
También reconoció que él y su casa habían sido atormentados por mi causa.
Después me contó todo lo que había en su corazón,
y dijo que él creía que era cierto lo que yo había dicho de la verdadera fe y esperanza;
y confesó que en los momentos en que yo le había pedido que me
dejara salir para hablarle la palabra del Señor a la gente,
y él se había negado, y yo había puesto el peso de eso sobre él,
se había encontrado bajo gran angustia, desconcertado y casi demente por un tiempo,
y en tal estado que le quedaban pocas fuerzas.
La mañana siguiente,
el guarda fue a los jueces y les contó que él y su
casa habían sido atormentados por mi causa.
A lo que uno de los jueces dijo (como me informó),
que los tormentos estaban sobre ellos también por retenerme.
Este fue el juez Bennet de Derby, quién fue el primero en llamarnos Cuáqueros,
porque les dije que debían temblar ante la palabra del Señor.

[.signed-section-signature]
Diario de George Fox

--

Cabe señalar al lector,
que este arrepentido carcelero se unió más adelante a la sociedad de los Amigos,
y en lugar de cuidar una prisión, perdió todo lo que tenía,
y muy probablemente también sufrió encarcelamiento.
En aquella época, le escribió una carta llena de sentimientos a George Fox,
que muestra claramente una mente rendida "`a causa de Cristo, no solo para creer en él,
sino también para padecer por él.`"^
footnote:[Filipenses 1:29]

De esta manera vemos que los juicios y tormentos
del Señor atormentan los corazones de los desobedientes,
y que Él no está ausente para defender la causa de los justos,
incluso en las mismas conciencias de aquellos que los persiguen y odian.
Así se cumple el antiguo proverbio que declara:
"`Los juicios están preparados para los escarnecedores.`"^
footnote:[Proverbios 19: 29 LBLA]

[.centered]
=== William Callow

[.embedded-content-document]
--

W+++.+++ Callow fue detenido en la Isla de Man por ocho semanas, en el año 1657,
por haber reprendido a un sacerdote,
a quién había oído abusar del pueblo llamado Cuáqueros
durante un sermón dirigido al pueblo.

Varias personas fueron sacadas de una reunión el primer día de la semana,
y puestas en el cepo^
footnote:[El cepo fue utilizado hasta inicios del siglo diecinueve,
como instrumento de tortura, en el que la víctima quedaba inmovilizada de pies y manos.
Cuando se trataba de un castigo,
el cepo se encontraba generalmente en la plaza del pueblo, para exponer al reo,
servir de escarnio y someterlo a todo tipo de vejaciones, como el ser golpeado, escupido,
insultado.
En ocasiones,
el pueblo incluso orinaba y defecaba sobre el condenado o le arrojaban comida podrida.]
por horas en la plaza del pueblo; otras fueron multadas, y entre ellas William Callow,
a quien le fueron arrebatadas diez fanegas de avena como embargo,
y puestas en el granero de otra persona.
El siguiente primer día, después del sermón,
el sacerdote dio aviso público para que los pobres de la
parroquia fuera al granero y tomaran un poco de grano,
el cual, el gobernador había ordenado que fuera distribuido entre ellos; ante esto,
algunos de los pobres, sus propios oyentes,
respondieron que hubiera sido más caridad si el gobernador hubiera
dado sus propios bienes a los pobres que los de otras personas,
y que no tomarían nada de ello.
Sin embargo, algunos de los pobres fueron al lugar con el sacerdote y los soldados,
y William Callow también fue.
El sacerdote llamó varias veces a los pobres para que cogieran sus sacos,
pero ninguno de ellos lo hizo; ante esto el sacerdote se enfureció,
y viendo fijamente a William Callow le dijo al pueblo: "`¿Por qué no toman el grano?
¿Hay alguien aquí que tenga que ver con este grano,
o que diga que no se puede dar a los pobres?`"
Dijo esto para provocar alguna reacción en William, sin embargo, él mantuvo la calma.
Los pobres permanecieron ahí por un tiempo, y luego se fueron retirando uno a uno,
dejando el grano con el sacerdote y los soldados.
El siguiente primer día,
el párroco haciendo nuevamente pública la distribución
del grano como lo había hecho anteriormente,
expresó cuán disgustado estaba el gobernador porque no lo habían tomado.
Por temor al gobernador y al sacerdote,
algunas personas pobres fueron nuevamente al lugar,
pero solo uno de ellos quiso tomar algo, y dijo jactanciosamente a los demás:
"`Ustedes son tan orgullosos que no lo tomarán; yo tomé esto,
y le quitarán más de sus bienes antes de que esto sea comido,
y entonces yo tomaré más.`" Pero sucedió que antes
de que hubiera comido lo que había tomado,
se lo llevó la muerte.
Su abrupta partida fue interpretada por los otros pobres como un juicio contra él,
y se alegraron de haberse mantenido libres de ello.
El resto del grano permaneció hasta que se echó a perder, pues nadie quiso llevárselo.

William Callow y varios más--que fueron demandados
por el sacerdote a pagar dos peniques cada uno,
por el pan y el vino,
de los cuales ellos no habían recibido nada--fueron encarcelados por orden del gobernador;
de quién también, en el mes séptimo de 1659,
el sacerdote obtuvo otra orden para el encarcelamiento de William Callow y otro amigo,
por haberse rehusado a pagar los diezmos.
Una mañana temprano, tan pronto llegaron a la orilla,
tras haber estado toda la noche en el húmedo y frío mar (porque ellos eran pescadores),
fueron llevados a la cárcel con sus ropas mojadas,
y detenidos por varios días en medio de la temporada de arenques,
la mejor época para su negocio.
Esto, sin embargo, planeado por su adversario,
no produjo el perjuicio naturalmente esperado;
porque la noche después de haber sido liberados,
pescaron tanto como fueron capaces de traer hasta la orilla,
de modo que tuvieron razones para reconocer con agradecimiento
la extraordinaria providencia que los ayudaba.

[.signed-section-signature]
__La Historia del Pueblo llamado Cuáqueros__ por John Gough

--

[.centered]
=== Lord Baltimore

Lord Baltimore junto con su señora y su séquito,
asistieron a una reunión de adoración en Treddhaven en Maryland, en el año 1700,
a la cual, siendo la reunión anual, William Penn los acompañó. Pero al llegar tarde,
cuando empezaba a desvanecerse la fuerza y la gloria
del poder celestial del Señor de la reunión,
la dama se sintió muy decepcionada,
y le dijo a William Penn que ella no quería oírlo _a él_ ni a nadie como él,
pues era un erudito y un hombre sabio, y no dudaba de que pudiera predicar;
pero que quería oír predicar a algunos de los mecánicos, campesinos,
zapateros y personas rústicas por el estilo,
pues pensaba que no podían predicar en absoluto.
William le dijo, que algunos de ellos eran de hecho,
los mejores predicadores que había entre ellos.

[.centered]
=== John Richardson

La siguiente narración del diario de John Richardson,
si bien muestra claramente el compromiso sincero del alma,
digno de un verdadero ministro del evangelio, también transmite, al final del diario,
una idea de esa preciosa paz de la que el profeta Isaías hablaba: "`Así ha dicho Jehová,
Redentor tuyo, el Santo de Israel: Yo soy Jehová Dios tuyo,
que te enseña provechosamente, que te encamina por el camino que debes seguir.
¡Oh, si hubieras atendido a mis mandamientos!
Fuera entonces tu paz como un río, y tu justicia como las ondas del mar.`"^
footnote:[Isaías 48: 17-18]

[.embedded-content-document]
--

Teniendo en mente visitar una reunión río arriba en un lugar llamado Perquimus,
en el lado oeste del río Choptank, y estando yo en el lado este,
Henry Hosier y algunos otros amigos emprendieron el viaje conmigo en un
pequeño bote que no estaba en buenas condiciones pues era frágil,
y contaba con solo una pequeña vela.
Partimos creyendo que contábamos con buen tiempo para llegar al puerto esperado,
pero cuando estábamos en el gran río (según recuerdo,
tenía diez millas de ancho en el cruce más corto,
pero la manera en que lo cruzamos lo hizo aún más ancho),
el viento empezó a soplar mucho en contra nuestra,
estando dentro de unos cuatro grados de nuestro curso.
Llovía tanto y estaba tan oscuro, que escasamente podíamos vernos el uno al otro;
y el agua empezó a meterse en el barco,
de modo que fue trabajo continuo de un hombre sacarla,
y toda nuestra tripulación estaba desanimada,
ya que la mayoría de ellos estaban muy mareados.
Henry Hosier, en quién yo tenía más esperanzas de ayuda,
dijo que no podía conducir más el bote.
Debido a la extrema oscuridad, la agitación de las olas,
la tempestad del viento y la fuerte lluvia, yo, que me encontraba indispuesto,
me vi obligado a llevar el timón de la embarcación, y con gran inquietud de mente,
pues no contaba con alguna guía externa que me indicara
con certeza el camino que debíamos tomar.
Al no tener fuego y estando el barco al descubierto,
no teníamos luz para ver nuestra brújula; pero mi fe estaba en el Señor,
de que Él nos llevaría a la orilla.
Así que me mantuve tan cerca del viento en la medida que el bote podía soportar,
y le dije a mi pobre tripulación enferma y desamparada, que creía que no pereceríamos,
aunque era posible que perdiéramos nuestro puerto.

Creo que nunca había estado en un peligro tan eminente como ese sobre el agua;
pero alabado sea por siempre el nombre del Señor,
porque nos metimos en la desembocadura de nuestro deseado río de Perquimus,
como si lo hubiéramos visto de día o guiado por una brújula,
nada de lo cual tuvimos el beneficio de tener durante varias horas.
Ahí bajamos a tierra, e hicimos una gran fogata bajo el acantilado del río,
y cerca de la media noche, salió la luna, se despejó y heló,
y hacía mucho frío. Cuando mis compañeros se durmieron, yo los volteaba,
apartándolos del fuego cuando aumentaba, y acercándolos cuando disminuía,
pero no logré mantenerlos despiertos.
Busqué troncos de madera, los acarreé y cuidé del fuego,
lo que fue suficiente trabajo por el resto de la noche.
Llegada la mañana, nos embarcamos en el helado bote y navegamos hacia la reunión.

Cuando estábamos entre los Amigos, se les avisó de que había un visitante allí;
y fue una reunión celestial y dulce,
de modo que pensamos que habíamos tenido una buena
recompensa por todo lo que habíamos pasado,
¡bendito sea el nombre del Señor ahora y para siempre, porque Él es digno!
Aunque Él considere oportuno probarnos, a veces de una manera y a veces de otra,
¿cómo podríamos saber si tenemos fe, si no somos probados?
¿Cómo sabremos que tenemos verdadero amor a Dios, si nunca somos probados?
La prueba de la fe del verdadero creyente es más preciosa que el oro.
Los excelentes dichos de Job vinieron a mi mente: "`He aquí yo iré al oriente,
y no lo hallaré; y al occidente, y no lo percibiré. Si muestra su poder al norte,
yo no lo veré; al sur se esconderá, y no lo veré.`"^
footnote:[Job 23: 8,9]
Luego, como un hombre en la fe verdadera, dice: "`Mas Él conoce mi camino; me probará,
y saldré como oro.`"^
footnote:[Job 23: 10]

A menudo he pensado en Moisés, en lo lejos que llegó para que Israel se salvara,
y en lo lejos que llegó Pablo para que sus parientes según la carne se salvaran;
estos grandes y buenos hombres dieron una gran demostración
de que tenían verdadera fe e interés en el Señor,
y también un amor muy grande a Su pueblo.
Y aquellos cuyos ojos están verdaderamente abiertos,
no pueden sino ver que el amor de Dios y el amor a las almas de los hombres,
es lo que nos constriñe a tomar nuestras vidas así, como en nuestras manos,
y a trabajar bajo muchos pasos fatigosos, y muchos peligros por mar y por tierra,
y en el desierto, el frío, y a veces en tumultos y alborotos,
a veces en vigilias y ayunos,
de modo que en ocasiones hemos sido un espectáculo ante los hombres;
pero el Señor nos ha dado fe y paciencia para soportarlo y vencerlo todo,
a medida que nos hemos mantenido firmes en su consejo celestial,
y hemos sido verdaderamente devotos a Su voluntad en todas las cosas.

--

[.centered]
=== Fidelidad Bajo Persecución

El mismo obrero del Evangelio, de joven fue dejado por la muerte de su padre,
a cargo de un cruel padrastro,
con quien su madre se casó cuando tenía unos dieciocho años. Él había estado
asistiendo diligentemente a las reuniones de los Amigos durante algún tiempo,
y sabía muy bien el valor de ellas,
y de los testimonios que como pueblo estamos llamados a dar;
habiendo pasado previamente por muchos de esos conflictos,
que en mayor o menor medida se permite que asalten al alma despierta.
Su padrastro pronto se disgustó bastante con él porque asistía a las reuniones,
y a pesar de que trabajaba muy duro para él en su negocio--siendo casi increíble
lo que su pobre y débil cuerpo sufría--aun así nada servía para ganar su amor.
Cuando regresaba de las reuniones,
a pesar de ser tan puntual como sus fuerzas se lo permitían,
se encontraba con muchas miradas y palabras poco amables.
Su padre por lo general lo enviaba por las mañanas del primer día al campo,
a una o dos millas a pie, para que observara el ganado, los caballos y las ovejas,
aparentemente, con la intención de que no pudiera ir a las reuniones,
por lo que él se veía obligado a caminar rápido,
y algunas veces a correr con sus zapatos debajo de sus brazos por falta de tiempo.
Esto conmovía profundamente a muchos Amigos,
de modo que no podían evitar llorar cuando lo veían entrar a la reunión muy acalorado,
habiendo recorrido dos, tres, cuatro,
y algunas veces hasta seis millas para llegar a las reuniones de los Amigos.

"`El gran poder del Señor me sostenía,`" dice John Richardson,
"`y Él me daba (por decirlo así) pies de ciervo,
y me daba capacidad para pasar por estos ejercicios
y soportar la carga en el calor del día de mis pruebas,
tanto interna como externamente, las cuales eran muchas y diversas.`"

Después de usar otras artimañas para impedirle que fuera a las reuniones de los Amigos,
y al ver que ni los ceños fruncidos, ni las amenazas, ni las dificultades,
ni las grandes promesas de amabilidad prevalecieron contra él,
su padre le dijo franca y ásperamente que no podía permanecer más tiempo en su casa,
a lo cual John le respondió inocentemente, que si debía ser así, él no podía evitarlo,
pues ya que todo lo que podía hacer no le daría contentamiento
sin herir su conciencia o la paz de su mente,
lo cual dijo, que valoraba por encima de todas las cosas mutables de este mundo.

[.offset]
John Richardson prosigue así en su relato:

[.embedded-content-document]
--

A pesar de que yo le supliqué a mi padrastro que me dejara
quedarme hasta que tuviera noticias de algún lugar,
él no lo hizo, aunque yo apenas era apto para trabajar, al ser casi solo piel y huesos,
como dice el dicho,
de modo que la mayoría de los que me conocían decían
que seguramente me consumiría la tuberculosis.
Pero resulta que debía irme y lo hice, aunque era débil,
decaído y estaba en malas condiciones de cuerpo, mente, dinero y ropa,
porque creo que no tenía más que doce peniques en mi bolsillo,
y ropa muy sencilla sobre mi espalda.
Así que me despedí solemnemente de la familia, con mi corazón lleno,
pero manteniéndome internamente vuelto hacia el Señor y bajo el gobierno de la Verdad.
Se derramaron muchas lágrimas cuando me fui, especialmente de parte de mi pobre madre.
Mi padrastro dijo muy poco,
pero parecía maravillado de ver cuánto amor me manifestaban
los otros miembros de la familia,
y lo mucho que deseaban que yo no tuviera que irme.

Salí a los grandes campos, donde había hecho muchas caminatas en solitario,
pero ninguna había sido como esta, porque esta vez no sabía adónde ir.
Entonces pensé en Abraham, cuando fue llamado a salir de Ur, en la tierra de los caldeos;
pero había una diferencia entre nosotros: Que él había sido llamado,
yo había sido forzado a salir.
Pero mientras caminaba en los campos mencionados, la sensación de mi débil condición,
al no saber dónde ir,
o dónde reposar mi cabeza--aunque yo tenía muchos
amigos pero no me sentía libre de ir a ellos,
porque no creía que tuvieran algún trabajo para mí;
ya que yo no era de una disposición atrevida, sino más bien retraída y tímida--digo,
el sentido de mi débil condición me sobrecogió a tal grado,
que parecía que mi camino estuviera cercado por todo lado, interna y externamente.
Yo pensaba de mí mismo como un pelicano en el desierto,
o como un búho en regiones desoladas,
y me parecía que no había otro hombre en toda la tierra en mí misma
condición. En la conciencia y consideración de mi estado de abandono,
me sentí bajo una gran opresión de espíritu y con mi corazón tan cargado,
que parecía una botella a punto de explotar.
Miré a mi alrededor para asegurarme que no había nadie cerca
que pudiera ver mis lágrimas ni oír mis clamores,
y en la angustia y amargura de mi alma, derramé mis quejas,
clamores y lágrimas delante del Juez de toda la tierra.
El Señor me consoló en mi deplorable estado--que era peor que el de Jacob,
cuando estaba acostado en el suelo y tenía una piedra por almohada;
porque él tenía parientes cercanos a quienes acudir,
de los que podía esperar que lo recibieran de buen grado,
pero yo no tenía a nadie a quien acudir,
sino a quienes más bien me injuriaban y me hablaban con dureza--y me dijo,
como si un hombre me hubiera hablado:
"`Busca primero el reino de los cielos y su justicia,
y todas estas cosas de las que tienes necesidad, te serán dadas.`"
Entonces deseé que Él se complaciera en mostrarme un lugar adónde ir,
y el Señor abrió mi camino y me mostró la casa a
la que debía ir y permanecer por un tiempo.
Dije: "`Buena es la palabra del Señor.`" Yo creí,
y esto fue un gran medio para fijar mi mente y establecerla en la Verdad,
con plena intención de corazón de seguir al Señor y obedecer Sus requisitos,
según me daba conocimiento y habilidad.

--

[.centered]
=== Richard Davies

Algunas circunstancias asociadas con los primeros
años de la vida religiosa de Richard Davies,
son de una naturaleza tan interesante y edificante,
que entran dentro del propósito y alcance de estas breves anécdotas.

Fue convencido a una temprana edad mediante el poder y la gracia de Dios,
de que las doctrinas religiosas de nuestra Sociedad concordaban con las
Escrituras y con la Verdad que está en Jesús. Vivió en Gales del Norte,
y se cree que fue uno de los primeros de nuestros Amigos que se levantó en esa
parte del país. Su labor fue notable en las iglesias de Cristo reunidas allí,
especialmente en los tiempos de persecución. Los testimonios de sus hermanos en Cristo,
adjuntos en su diario, reflejan su aprecio, y el extracto de uno ellos,
puede ser suficiente para mostrar cuán estimados
eran esos esforzados obreros por sus sucesores:

[.embedded-content-document.testimony]
--

¡Oh, la maravillosa sabiduría y amor de Dios,
que lo llamó a él y a muchos otros en aquellos días,
y los preparó y capacitó para la gran obra que tenían que hacer,
y los fortaleció para hollar el camino delante de nosotros,
que éramos débiles y frágiles! ¡Oh, cuán fuertes, confiados y valientes instrumentos,
preparó el Señor Dios, para comenzar a quebrantar la gran imagen del orgullo, soberbia,
etc., que estaba entonces y que aún está en el mundo!
Ciertamente, su memoria es digna de ser registrada,
para que las generaciones venideras puedan ver lo que el Señor ha hecho por sus fieles,
quienes dieron sus vidas, y todo lo que tenían por causa de la Verdad.

--

El siguiente extracto es más extenso de lo que me hubiera gustado incluir;
pero como está elaborado para esclarecer muchos puntos
de nuestro testimonio y práctica Cristianos,
y presentado por alguien que se convirtió en un padre para muchos,
incluso un apóstol y obispo del rebaño en aquel país, no me pareció oportuno abreviarlo.

[.embedded-content-document]
--

Cerca del año 1656,
nuestros ministros nos dijeron que había aparecido un tipo de pueblo en el norte,
llamados Cuáqueros, y que era un pueblo de una postura y principios extraños;
diciéndonos que estos eran los últimos días y los tiempos
de los que Cristo había hablado en Mateo 24:5:
"`Porque vendrán muchos en mi nombre,
y a muchos engañarán.`" "`Porque se levantarán falsos Cristos, y falsos profetas,
y harán grandes señales y prodigios, de tal manera que engañarán, si fuere posible,
aun a los escogidos`" (versículo 24). Se predicó mucho contra este pueblo llamado Cuáqueros;
se nos dijo que eran falsos profetas, etc.,
que negaban las Escrituras y todo tipo de ordenanzas,
y que también negaban al mismo Cristo que los había comprado.
Se nos hizo creer que eran un pueblo tan peligroso,
que temíamos a cualquiera que tuviera el nombre de Cuáquero,
para no ser engañados por ellos.
Hasta ese momento, nunca antes habían estado por estas partes del territorio,
ni sabíamos cuáles eran los principios que sostenían;
sino sólo lo que informaban (aunque falsamente) nuestros predicadores y otras personas;
lo que nos mantuvo ciegos y nos impidió investigar más,
para examinarlo todo y retener lo bueno, según el consejo del apóstol.^
footnote:[1 Tesalonicenses 5:21]

Ahora, cerca del año 1657,^
footnote:[Richard Davies entonces tenía alrededor de veintidós años.]
llegó a la casa de mi amo un hombre, pobre, vestido humildemente, llamado Morgan Evan,
de Gales del Sur.
En sus viajes se había topado con el pueblo llamado Cuáqueros,
y había sido convencido de la Verdad.
Este hombre conversó con mi amo sobre los principios de la Verdad,
y como yo estaba en la tienda trabajando, mi ama se acercó y me dijo:
"`¿Por qué no sales a ayudar a tu amo?
Porque hay un Cuáquero en la puerta que le ha dejado sin palabras.`"
Al escuchar esto, me apresuré, tomé mi Biblia bajo el brazo,
y me armé del valor que pude para discutir con ese hombre;
pero resultó ser demasiado difícil para nosotros.
Le dije que habíamos escuchado que los Cuáqueros negaban las Escrituras,
y que no las leían. Él dijo que había muchos informes falsos acerca de ellos.
Y en verdad, cuando él leyó la Escritura tan fácilmente,
llegué a la conclusión de que lo que se informaba acerca de ellos no era cierto;
y él vio que había alcanzado al testigo de Dios en mí. Luego me
exhortó a prestar atención a esa Luz que brilla en mi corazón,
y me muestra mis pensamientos vanos,
y me reprueba en lo secreto por cada palabra o acción ociosa; diciendo,
que _esa_ era la luz verdadera que alumbra a cada hombre que viene al mundo (Juan 1:9);
y que en esa Luz, yo vería más Luz, y que _ella_ abriría las Escrituras para mí,
y que yo recibiría una medida de ese mismo Espíritu que las había escrito.
También me dijo, que era la palabra profética más segura,
a la que yo haría bien en prestar atención,
como a una antorcha que alumbra en lugar oscuro,
hasta que el día esclarezca y el lucero de la mañana salga en mi corazón.^
footnote:[2 Pedro 1: 19]
Y habló mucho de la obra interna,
y de cómo opera el Santo Espíritu de Dios sobre el alma;
encomendándome a la gracia de Dios que trae salvación, y nos enseña,
"`que renunciando a la impiedad y a los deseos mundanos, vivamos en este siglo sobria,
justa y piadosamente.`"^
footnote:[Tito 2:11-12]
Y así partió de nuestra casa, y yo lo acompañé a que tomara su camino.

Cuando me separé de él,
sus palabras se fueron apoderando de mí en la medida que las consideraba, de modo tal,
que no podía escapar de ellas;
y cuanto más esperaba en esa Luz a la que él me había encomendado,
más se quebrantaba mi antigua paz,^
footnote:[Richard Davies
había sido un miembro de la iglesia del Estado desde su nacimiento,
pero después se unió a los Independientes.]
y aquello en lo que solía consolarme.
Así llegué a ver que nuestra antigua edificación no podía prevalecer,
pues habíamos construido en lo que el apóstol llamaba madera, heno y hojarasca.
De esa manera experimenté la pérdida de todo mi conocimiento previo,
y mis antiguas prácticas demostraron ser tan solo una edificación sobre la arena.
Luego, con gran humildad y pobreza de espíritu,
le rogué al Dios Todopoderoso que me permitiera edificar sobre la Roca,
sobre la que la iglesia de Cristo estaba edificada,
para que las puertas del hades no prevalecieran contra mí.

Pero yo temía ser engañado por los Cuáqueros; sin embargo, no sabía adónde ir,
externamente, en busca de consejo.
Por eso deseaba que el Dios de Abraham, Isaac y Jacob fuera mi maestro;
porque creía que el Señor establecería un nuevo pacto con su pueblo,
tal como lo había prometido a través de la boca del profeta Jeremías.^
footnote:[Jeremías 31: 31-34]

Me dispuse, entonces, a aferrarme a esas preciosas promesas,
y esperé el cumplimiento de ellas en mí mismo,
y de lo que Cristo le había dicho a los judíos: "`Escrito está en los profetas:
Y serán todos enseñados por Dios.
Así que, todo aquel que oyó al Padre, y aprendió de él, viene a mí.`"^
footnote:[Juan 6:45]
Y se dice: "`Todos tus hijos serán enseñados por Jehová;
y se multiplicará la paz de tus hijos.`"^
footnote:[Isaías 54:13]

Cuando llegué a saber un poco de las enseñanzas del Señor,
abandoné a todos mis maestros anteriores,
y muchas veces me iba al bosque y a otros lugares apartados, donde nadie me pudiera ver,
a esperar en el Señor, donde era muy quebrantado y enternecido por el poder de Dios.
Y aunque comencé a ver un poco de mí mismo, y algo de la bondad de Dios,
aún tenía temor de ser engañado,
pues había leído y escuchado que el propio satanás se disfraza como ángel de luz.^
footnote:[2 Corintios 11:14]
Le pedía al Señor poder ver una vez más a aquel hombre pobre,
pues no sabía dónde encontrar a alguno de los llamados Amigos;
y le plació a Dios que él regresara por aquel camino,
y le pedí a mis amos que lo alojaran, y que estuviera conmigo, a lo cual consintieron.
Entonces le pregunté acerca de la forma de adoración de los Amigos,
sobre las llamadas dos grandes ordenanzas en las que tanto confiábamos, a saber,
el pan y el vino, y el bautismo, y acerca de las Escrituras,
para saber lo que pensaban de ellas;
a todo lo cual me respondió con cierta satisfacción. En la mañana me despedí de él,
y que yo sepa, no volví a verlo durante varios años.

En todo ese tiempo mantuve la costumbre de retirarme al bosque,
o a algún otro lugar privado; y allí, en mi espera,
le pedí al Señor que Él mismo me satisficiera aún más en cuanto a estas cosas: Primero,
si las Escrituras eran la Palabra de Dios, como se había dicho y predicado que eran;
y segundo, sobre el Camino a la vida y a la salvación. Luego,
comencé a meditar seriamente en el primer capítulo de Juan.
Yo me encontraba, junto con muchos otros, bajo el error en el que estaban los judíos,
que pensaban que podían tener la vida eterna en las Escrituras;
mientras que Cristo afirma:
"`Ustedes examinan las Escrituras porque piensan tener en ellas la vida eterna.
¡Y son ellas las que dan testimonio de Mí! Pero ustedes
no quieren venir a Mí para que tengan esa vida.`"^
footnote:[Juan 5: 39-40 NBLA]
Puesto que Él es la vida, también es el camino al Padre: "`Yo soy el camino, y la verdad,
y la vida; nadie viene al Padre, sino por mí.`"^
footnote:[Juan 14:6]
En cuanto a las Escrituras, yo era un gran amante y un gran lector de ellas,
y me deleitaba mucho escudriñándolas, pensando que _eso_ me haría sabio para la salvación;
tal como Pablo le dijo a Timoteo:
"`y que desde la niñez has sabido las Sagradas Escrituras,
las cuales te pueden hacer sabio para la salvación por la fe que es en Cristo Jesús.`"^
footnote:[2 Timoteo 3:15]
Sin embargo, me faltaba lo principal, la fe verdadera y salvadora que es don de Dios.
"`Porque por gracia sois salvos por medio de la fe; y esto no de vosotros,
pues es don de Dios.`"^
footnote:[Efesios 2: 8]
De modo que es _la gracia de Dios_ la que trae salvación,
y no el simple conocimiento histórico de las Escrituras.

Puede que los hombres tengan un gran conocimiento literal de las Escrituras,
y aun así permanecer en el error, porque no las conocen como deberían,
ni conocen el poder que estaba en los hombres santos que las dieron;
tal como Cristo les dijo a los judíos: "`Erráis,
ignorando las Escrituras y el poder de Dios.`"^
footnote:[Mateo 22: 29]
Eso que da el verdadero conocimiento de Dios,
y un correcto entendimiento de las Escrituras es, por tanto, el poder de Dios:
"`Porque,`" dice el apóstol: "`Dios,
que mandó que de las tinieblas resplandeciese la luz,
es el que resplandeció en nuestros corazones,
para iluminación del conocimiento de la gloria de Dios en la faz de Jesucristo.`"^
footnote:[2 Corintios 4: 6]
Y en la medida que los hombres y las mujeres se vuelvan a esta luz,
que es el Espíritu de Dios, y la obedezcan, llegarán a la consolación de las Escrituras,
de las que el mismo apóstol dice: "`Porque las cosas que se escribieron antes,
para nuestra enseñanza se escribieron,
a fin de que por la paciencia y la consolación de las Escrituras, tengamos esperanza.`"^
footnote:[Romanos 15: 4]

Y al considerar con seriedad lo que leía en las Sagradas Escrituras,
creí que el Espíritu del Señor era el intérprete de ellas.
Aquellos grandes misterios que estuvieron ocultos por edades y generaciones,
y que aún en esta nuestra era permanecen ocultos para muchos,
han llegado a ser revelados por el Espíritu de Dios.
Y aunque antes leía las Escrituras como muchos lo hacen,
sin un verdadero sentido y una debida consideración,
ahora puedo bendecir a Dios por ellas y experimentar un gran consuelo al leerlas,
pues ya no son un libro sellado para mí, ni para muchos otros,
que esperan recibir la ayuda del Espíritu Santo de Dios en todos
sus deberes y actividades que el Señor requiere de ellos;
porque sabemos que separados de Él no podemos hacer nada que le agrade.
Antes corríamos en nuestro propio tiempo y voluntades para predicar y orar,
sin considerar la dirección y movimiento del Espíritu del Señor. Muchas veces,
cuando me levantaba de mis rodillas tras una manera formal de oración,
la reprensión estaba muy cerca de mí, diciendo: "`¿Quién demanda esto de vuestras manos?
Son las teas que encendisteis.`"^
footnote:[Isaías 1:12; 50:11]
Yo temía ser sepultado en dolor, como el Señor les dijo a algunos en Isaías 50:11.

Razonaba mucho y tenía muchas dudas en mi mente acerca del bautismo en agua,
el pan y el vino.
Y cuando me sentí satisfecho en cuanto a esos asuntos de peso,
pensé que podría descansar ahí y conservar mis antiguas costumbres, modas y lenguaje;
pero eso no funcionaría, no encontraría paz en ello.
Dios me mostró las vanas costumbres de las personas,
y que nuestro lenguaje no era acorde con el lenguaje del
pueblo de Dios registrado en las Escrituras de la Verdad.
Y aunque tenía poco conocimiento en gramática,
sabía cuán inadecuado era decir _ustedes_ para una persona, en lugar de _tú_.^
footnote:[La mayoría de los angloparlantes modernos desconocen
que las palabras "`you`" y "`your`" eran originalmente pronombres
plurales que se utilizaban sólo para dirigirse a dos o más personas,
mientras que "`thee`" y "`thou`" se usaban para dirigirse a una sola persona.
En el siglo XVII,
se puso de moda (originalmente con el fin de mostrar honor o adulación)
utilizar el plural "`you`" y "`your`" (que es como usar "`ustedes`" y
"`vosotros`") para dirigirse a individuos de mayor estatus social,
mientras que "`thee`" y "`thou`" (como "`tú`" y "`usted`") se reservaban para los sirvientes,
los niños o las personas de menor posición social o económica.
Los Amigos se ciñeron a los usos originales de los pronombres,
en lugar de mostrar preferencia refiriéndose a las
personas de clase alta con pronombres plurales.
Esto parece algo insignificante para el lector del siglo XXI,
pero muchos miles de los primeros Amigos fueron insultados, golpeados,
encarcelados y hasta matados por negarse a conformarse a esas costumbres externas.]

Así, por motivos de conciencia,
me sentí obligado a hablar el lenguaje puro de _ti y tu_ con todos,
sin acepción de personas, lo que era una gran cruz para mí,
aunque algunos lo consideraban como algo débil y tonto.
Sin embargo, cuando el Señor impone la necesidad de hablar la verdad a todos,
esto llega a tener más peso del que muchas personas superficiales piensan que tiene.
Al tener esta necesidad impuesta sobre mí, me dirigí a mi amo en ese lenguaje;
él no se ofendió porque estaba convencido de la verdad de ello,
y de que debía usarse con todos.
Pero cuando le hablé del mismo modo a mi ama,
ella tomó un palo y golpeó mi cabeza de manera tal,
que quedó hinchada y adolorida por un largo tiempo.
Estaba tan disgustada por ello, que juró que me mataría, aunque la ahorcaran por ello;
si bien antes de eso, rara vez, si es que alguna,
me había dirigido una sola palabra con enfado.
Pero yo sabía que la enemistad estaba entre las dos semillas,
y que "`el que había nacido según la carne perseguía al que había nacido según el Espíritu.`"^
footnote:[Gálatas 4: 29]
Como yo estaba bastante convencido de la Verdad en mí mismo,
recordé las palabras de Cristo: "`El que ama a padre o madre más que a mí,
no es digno de mí; el que ama a hijo o hija más que a mí,
no es digno de mí. El que halla su vida, la perderá;
y el que pierde su vida por causa de mí, la hallará.`"^
footnote:[Mateo 10: 37, 39]

El Todopoderoso puso en mi corazón que considerara el costo,
y que a través de la tribulación entraría al reino de los cielos;
y fui fiel en este testimonio que tenía que dar.
Me sentí muy animado a seguir en ese estrecho y angosto
camino por el que Dios me mostró que debía andar.
También consideré el dicho: "`El que no lleva su cruz y viene en pos de mí,
no puede ser mi discípulo.`"
Y de nuevo: "`Quién de vosotros, queriendo edificar una torre,
no se sienta primero y calcula los gastos,
a ver si tiene lo que necesita para acabarla?`"^
footnote:[Lucas 14: 27-28]
Esta consideración pesaba bastante sobre mí,
no fuera que comenzara a tomar la Cruz y a caminar en este camino,
y no pudiera permanecer hasta el fin; porque la tentación de Satanás,
el deseo de la carne,
y las costumbres y modas pecaminosas de este mundo eran muy predominantes.
El peso y la carga que estaban sobre mí eran grandes,
pues no tenía a nadie cercano que me ayudara en mi tiempo de prueba, sino sólo al Señor,
que ha prometido estar con Su pueblo en todas sus tribulaciones,
y que no los dejará ni desamparará. Me encontraba
presto y dispuesto a aferrarme a Sus promesas,
y mis oraciones a Él eran,
que me capacitara para atravesar todas las cosas que Él requiriera de mí.

Por primera vez recibí el nombre Cuáquero,
porque me dirigía con tú y ti a una sola persona, no me quitaba el sombrero,
y no seguía las costumbres y modas del mundo en las que otros profesantes vivían y andaban;
aunque muchos de estos se quejaban de sus propias costumbres,
y estaban cansados de las modas del mundo, sin embargo,
no tomaban su cruz y las abandonaban.
Al hacer esto encontré gran consuelo del Señor,
y recibí de Él satisfacción y aliento vivificantes para seguir en mi camino;
recordando que la Escritura dice: "`Proseguirá el justo su camino,
y el limpio de manos aumentará la fuerza.`"^
footnote:[Job 17: 9]
También podría haber dicho con Job: "`Mas Él conoce mi camino; me probará,
y saldré como oro.
Mis pies han seguido sus pisadas; guardé su camino,
y no me aparté. Del mandamiento de sus labios nunca me separé;
guardé las palabras de Su boca más que mi comida.`"^
footnote:[Job 23: 10-12]

El Señor nos mantuvo a mí y a su pueblo, muy mansos y humildes,
en el espíritu de negación al yo.
Esperábamos la palabra viva,
que llegaba a nosotros con una voz viva de Aquel que habla desde el cielo
por Su Espíritu--la voz viva que es la voz de "`Cristo en nosotros,
la esperanza de gloria`"^
footnote:[Colosenses 1:27]
--cuya voz estimábamos más que nuestro alimento necesario.
Por obedecer esta voz, llegamos a ser objeto de burla y escarnio;
ellos hablaban toda clase de mal contra nosotros,
aborreciéndonos por causa de Su nombre.^
footnote:[Mateo 10:22]
Yo recordé lo que Cristo nos había dicho en Lucas 21:12, "`Os echarán mano,
y os perseguirán, y os entregarán a las sinagogas y a las cárceles,
y seréis llevados ante reyes y ante gobernadores por causa de mi nombre,`" etc.
Estas y otras aflicciones similares debía enfrentar,
si seguía verdadera y fielmente al Señor Jesucristo;
de manera que me esforcé por vestirme con todas las armas de la Luz,
para poder resistir los dardos de fuego del enemigo.

La ira de mi ama no se había aplacado aún, aunque no tenía nada en mi contra,
sino que no me conformaba al lenguaje corrupto y a las vanas costumbres del mundo.
Pues me esforzaba por mantener una conciencia libre de ofensa,
tanto hacia Dios como hacia el hombre.
Una vez,
cuando ella creyó tener una oportunidad apropiada para ejecutar su crueldad hacia mí,
se dejó llevar por tal ira,
que yo me rendí voluntariamente a morir en esa hora por causa de ella;
pero le plació al Señor aceptar mi ofrenda voluntaria, y puedo decir con el apóstol,
que "`no estimé preciosa mi vida para mí mismo, con tal que acabe mi carrera con gozo.`"^
footnote:[Hechos 20:24]
Y sólo el Señor apareció para socorrerme,
e hizo que ella se comportara más moderadamente por el tiempo restante de mi servidumbre,
que duró menos de dos años. Luego de que me marché
el Señor la visitó con una severa enfermedad,
en cuyo tiempo le dijo a su esposo y a los que estaban con ella,
que creía que no moriría hasta que me hubiera pedido perdón,
y deseaba que me enviaran a llamar si estaba en Londres; y así lo hicieron.
Yo pude perdonarla libremente, porque eso lo había hecho hacía mucho tiempo,
y le había orado a mi Padre celestial que Él también la perdonara.
Me despedí de ella;
y le plació a Dios tocarla con un sentido de Su amor y alargarle sus días,
y a menudo confesaba el mal que le había hecho a un joven honesto y prudente,
como decía que yo había sido,
quien había cuidado el bienestar interno y externo de su esposo,
incluso más que ellos mismos.

Por aquel entonces (1657),
era la gran comidilla del pueblo que yo me había convertido en Cuáquero.
Mis padres estaban muy preocupados por mí. Aún no había estado con ellos,
pues estaba esperando sentir libertad y tranquilidad en mí mismo, y luego fui a verlos.
Les molestó ver que yo no me arrodillaba para pedirles su bendición,
ni me inclinaba ante ellos, ni me quitaba mi sombrero como solía hacerlo antes.
Mi padre no tardó en darme la espalda.
Yo había escuchado de su disgusto, y que había dicho que no me dejaría herencia;
diciéndoles a mis parientes que antes había creído recibir consuelo de mí,
pero que ahora no esperaba ninguno, sino que yo recorriera todo el condado gritando:
¡Arrepiéntanse! ¡Arrepiéntanse!
Ahora bien, si mi padre me había rechazado por semejante motivo,
estaba muy convencido de que era por causa de Cristo y del evangelio.
Recordé la condición de David cuando dijo: "`Mi ayuda has sido.
No me dejes ni me desampares,
Dios de mi salvación. Aunque mi padre y mi madre me dejaran, con todo,
Jehová me recogerá. Enséñame, oh Jehová, tu camino,
y guíame por senda de rectitud a causa de mis enemigos.`"^
footnote:[Salmos 27:9-11]

Al fin mi madre se acercó tiernamente, me echó un vistazo, mirándome a mi rostro,
y vio que yo era su hijo y que no estaba, como decían los demás,
"`hechizado o transformado en otra semejanza;`" que
era lo que entonces se decía de los Cuáqueros,
y que ellos hechizaban a la gente para que se convirtieran a su religión, etc.
Así los engañaban a ellos y a muchos otros con historias muy extrañas,
y nos tenían por "`engañadores, pero veraces.`"^
footnote:[2 Corintios 6:8]
Y cuando hablé con ella de las Escrituras,
su corazón se enterneció y se conmovió por la bondad de Dios hacia mí;
se fue a buscar a mi padre, y le dijo: "`Ten ánimo,
nuestro hijo no es como se decía de él, todavía podemos recibir consuelo de él.`"

Un poco después de eso,
escuché que algunas de las personas que eran llamadas Cuáqueras se encontraban en Shrewsbury,
que quedaba a unas dieciocho millas del lugar donde yo vivía.
Esperé que se me presentara una oportunidad para ir a verlos,
y conocer así la forma de su adoración, pues aún no había visto a ninguno de ellos,
sino a aquel hombre pobre que mencioné anteriormente.
Cuando llegó la época llamada Navidad,
obtuve permiso para viajar hasta ahí. Primero fui a la casa de John Millington,
donde se reunían muchos Amigos,
y los del pueblo llegaban a verme con gran amor y ternura,
y había gran quebrantamiento de espíritu entre nosotros, aunque pocas palabras.
Esperábamos para sentir al Señor entre nosotros en todas nuestras reuniones.
Cuando llegó el primer día de la semana fuimos a una reunión en la casa de William Pane,
y aunque se mantuvo en silencio de palabras, la Palabra del Señor estuvo entre nosotros;
era como un martillo y fuego, más filosa que una espada de dos filos,
penetró hasta lo más íntimo de nosotros, nos derritió y nos llevó a derramar lágrimas,
de modo que apenas quedó un ojo seco entre nosotros;
el bendito poder del Señor cubrió con Su sombra nuestra reunión,
y podría haber dicho que sólo Dios era el amo de aquella reunión. Al día siguiente,
mientras me preparaba para regresar a casa,
habiendo compartido un tiempo considerable con los Amigos,
y sido muy consolado con la bondad de Dios y el amor no fingido de los hermanos,
escuchamos que John ap John iba a tener una reunión ahí. Yo me quedé para esa reunión,
y cuando lo oí, pensé que hablaba como quien tiene autoridad y no como los escribas,
sus palabras eran sanas y penetrantes.

Cuando llegué a la casa de mi amo, medité sobre muchas cosas,
especialmente en las palabras de Cristo: "`Vosotros sois la luz del mundo.
Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras,
y glorifiquen a vuestro Padre que está en los cielos.`"^
footnote:[Mateo 5:14,16]

Tiempo después, el Señor me pidió que fuera a dar mi testimonio de Él,
y advertirle a un grupo de personas que pensaran en el final de sus vidas,
las cuales acostumbraban reunirse para bailar y jugar
en un lugar no lejos de la casa de mi amo.
Cuando entré al lugar donde estaban bailando,
el violinista dejó de tocar y ellos de bailar,
y yo declaré la palabra del Señor entre ellos.
Lo que tenía ante mí era el caso de Job: "`Sus pequeños salen como manada,
y sus hijos van danzando.
Toman el pandero y el arpa, y se regocijan al son de la flauta.
Pasan sus días en prosperidad, y en un momento descienden a la sepultura.`"^
footnote:[Job 21:11-13 RVG]
Tras haber descargado mi conciencia de lo que pesaba sobre mí,
me despedí de ellos en amor y paz, y ellos me agradecieron por la buena exhortación,
y algunos de ellos me acompañaron a casa.
Continué, en la medida que el Señor me habría camino,
visitando a aquellos en los que encontraba alguna inclinación a las cosas que eran buenas;
y estaba conmigo un tal William Davies, que había sido convencido de la Verdad.

Después de esto, todavía esperaba saber la voluntad y el consejo de Dios,
y que dirigiera mi camino y ordenara mis pasos en mi viaje espiritual;
porque no tenía a nadie a quién mirar sino sólo a Aquel que era
totalmente suficiente para continuar la obra que había empezado,
aunque a menudo por medio de instrumentos débiles, pobres,
miserables y despreciables a los ojos del mundo.
Bien podría decir con el apóstol: "`Sino que lo necio del mundo escogió Dios,
para avergonzar a los sabios; y lo débil del mundo escogió Dios,
para avergonzar a lo fuerte; y lo vil del mundo y lo menospreciado escogió Dios,
y lo que no es, para deshacer lo que es.`"^
footnote:[1 Corintios 1:27-28]

Por aquel entonces fui a visitar a algunos jóvenes,
antiguos compañeros de profesión de religión;
dos o tres de ellos fueron convencidos y recibieron la Verdad.
Cuando éramos un total de cuatro personas,
sentí que debíamos reunirnos en el nombre del Señor, pues recordaba la promesa de Cristo:
"`Donde están dos o tres congregados en mi nombre, allí estoy yo en medio de ellos.`"^
footnote:[Mateo 18:20]
De modo que todos acordamos reunirnos,
pero ninguno de nosotros contaba con una casa propia para hacerlo.
Entonces acordamos reunirnos en una colina, en un lugar común,
tan cerca como fuera posible para mayor comodidad de todos,
ya que vivíamos a algunas millas de distancia.
Nos reuníamos en silencio allí, para asombro de los del pueblo.
Cuando la lluvia y el mal tiempo nos azotaban en un lado de la colina, nos íbamos al otro.
No sentíamos libertad para guarecernos en alguno de los establos de los vecinos,
porque ellos eran tan ciegos, oscuros e ignorantes,
que nos veían como brujos y se alejaban de nosotros,
algunos incluso hacían cruces con sus manos sobre sus frentes y rostros.

Así proseguimos durante un tiempo,
hasta que dos de ellos me dejaron +++[+++para irse a vivir a otro lado.]
El tercero era William Davies, y por algún tiempo nos reunimos juntos.
Pero en una ocasión, él se quedó más tiempo de lo usual, y un espíritu oscuro lo poseyó,
de modo que el poco tiempo que estuvimos juntos no fue cómodo
para mí. Cuando terminamos la reunión me preguntó,
a manera de conversación, cómo creía yo que nos opondríamos a todo el pueblo.
Le respondí con gran celo: "`La serpiente, la serpiente,
la misma que engañó a la mujer en el paraíso, te ha engañado,
no podrás mantenerte firme.`"
Mientras discutíamos, vi que mi amo se acercaba y que dos mujeres lo seguían,
una era su esposa, mi cruel ama, la otra era hermana de ella,
y ambas tenían varas en sus manos.
Cuando llegaron donde estábamos, mi ama comenzó a golpear a William Davies.
Así, pues, su prueba llegó rápidamente,
y no volvió a reunirse conmigo ni con otro Amigo por muchos años.
Aconteció que yo no recibí ningún golpe por parte de ellos;
y si hubiera recibido alguno, ya había aprendido de Jesucristo, mi Señor y Amo,
a sufrir pacientemente por causa de Su nombre,
y a no apartarme de Él por muchas que fueren mis pruebas, tentaciones y aflicciones.

Como esos jóvenes se marcharon, me quedé solo de nuevo,
pero seguí esperando en el Señor para saber Su voluntad con respecto a mí;
y cuando concluyó el tiempo de mi aprendizaje,
hallé libertad para ir a Londres a visitar a los Amigos de ese lugar,
que fue en el año 1658-9. Encontré allí a muchos
buenos Amigos que estaban vivos en la Verdad,
y me establecí en mi oficio, que era fabricante de fieltros,
y estaba muy satisfecho de poder ir a las reuniones y continuar con mi negocio.
Cuando venía a mi mente algo de mi tierra natal,
estéril y despoblada de Amigos y de la Verdad,
me esforzaba por ignorarlo y quedarme donde estaba, y hacía lo que podía;
pero todas mis buenas intenciones y razonamientos no servían de nada,
porque estaba desobedeciendo al Señor, y me sobrevinieron aflicción,
dolor y juicio de parte del Señor,
por no haber obedecido Su mandato de ir a mi propio pueblo para dar testimonio de Él
allí. Continué en mi desobediencia hasta que perdí el sentido de Su presencia,
y Él me hirió con angustia interna y con dolor en mis huesos,
de modo que no podía trabajar ni hacer ningún esfuerzo.
Durante ese tiempo, los Amigos de Londres fueron amables y cuidadosos conmigo,
y me habrían suplido generosamente,
pero yo no estaba dispuesto a aceptar nada de parte de ellos, mientras tuviera lo mío.

El dolor de mi cuerpo y espíritu se incrementaron,
hasta que al final me vi forzado a someterme a la voluntad
del gran Dios que era demasiado fuerte para mí;
y razonando con Él una noche en el lecho de mis dolores,
me mostró claramente que debía regresar a mi pueblo.
Yo me sentí dispuesto a rendirme e ir,
si al Él le placía mostrarme Su voluntad y agrado con esta señal:
que me quitara el dolor.
También razoné con Él diciéndole, que yo estaba solo, como un pelícano en el desierto,
o como un gorrión sobre el tejado de una casa.
Aun así, el Señor me mandó a ir,
mostrándome que Él iba a proveer una ayuda idónea
para mí. Y cuando hice el pacto con el Señor de ir,
mi dolor fue removido inmediatamente, y experimenté paz y quietud de mente y espíritu.
Me levanté la mañana siguiente y me fui a trabajar; y cuando aquellos tiernos Amigos,
que se habían preocupado por mi durante la enfermedad, vinieron a verme esa mañana,
encontraron que yo me había ido a trabajar; lo cual fue motivo de admiración.

De modo que en poco tiempo, el Señor y sólo Él, proveyó una ayuda idónea para mí;
porque le rogué que fuera de Su propia provisión,
pues aún no me había sido manifestado dónde estaba, o quién era.
Pero un día, mientras me encontraba en la reunión de Horslydown en Southwark,
oí a una Amiga abrir su boca a modo de testimonio contra un espíritu maligno y blasfemo,
que se oponía mucho a los Amigos en aquellos días. Vino a mí por parte del Señor,
que esa mujer iba a ser mi esposa, que iría conmigo al campo y sería mi ayuda idónea.
Yo estaba muy dispuesto a que el Señor lo hiciera como a Él le pareciera mejor,
y me quedé tranquilo.
Con el tiempo el Señor hizo que nos conociéramos,
y ella confesó que ella había visto lo mismo, que yo había visto concerniente a ella.
Yo le dije que si el Señor le ordenaba que fuese mi esposa,
iba a tener que acompañarme a un lugar extraño,
donde no había más Amigos que los que Dios llamara y reuniera en Su tiempo para Sí mismo.
Después de considerarlo un poco dijo, que si el Señor lo ordenaba, iría con su esposo,
aunque fuera al desierto;
y siendo algo sensible a las obras de Dios sobre su espíritu en ese asunto,
estaba dispuesta a aceptar en su corazón lo que Él obrara en ella.
Sin embargo, por escuchar a una persona que no había sopesado bien el asunto,
desobedeció lo que Dios le había revelado; trayendo gran dolor y tribulación sobre ella.
Fui a verla en esta pobre condición,
y descansé satisfecho con la voluntad de Dios en este asunto,
completamente rendido a recibirla como Su don para mí. Después de un tiempo,
esperando juntos en el Señor,
declaró delante de mí y del otro Amigo quién había
sembrado dudas y razonamientos en su mente,
que en el nombre y poder de Dios aceptaba ser mi esposa,
y que iría donde el Señor nos ordenara; y yo le dije: "`En el temor del Señor,
te recibo con un don de Dios para mí.`"

Tras considerar seriamente cómo llevar a cabo nuestro matrimonio,
decidimos exponer nuestro caso a los ancianos,
y especialmente a nuestro viejo Amigo George Fox +++[+++en esos días,
la gente se casaba por medio de un sacerdote,
o ante un juez]. Yo le conté a George Fox que pensábamos casarnos en una reunión pública;
con lo cual, él deseó que el Señor estuviera con nosotros.
Y sintiendo que teníamos libertad en el Señor, nos dirigimos a la reunión de Snail,
en Tower Street, Londres, por la mañana; y por la tarde, a Horslydown, Southwark;
y en esa reunión, en la presencia de Dios y de esa asamblea,
nos tomamos el uno al otro como marido y mujer.

Sólo Dios sabía nuestra inocencia e integridad al unirnos.
No fue por oro, ni plata, ni por ninguna cosa externa;
sino para servirle en nuestra época y generación,
y ser testigos de Él y de Su bendita Verdad donde nos enviara.
Poco después, en el tiempo del Señor,
nos apresuramos lo más que pudimos para ir al campo,
donde creíamos que el Señor quería que estuviéramos, y dijimos: ¡Oh Señor,
si vas con nosotros y nos guardas en este viaje,
y nos das pan para comer y vestido para vestir, entonces, oh Dios,
tú serás nuestro Dios!^
footnote:[Ver Génesis 28:20]
Y el Señor estuvo con nosotros en todo nuestro viaje,
y nos dio Su dulce y consoladora presencia.

[.signed-section-signature]
Diario de Richard Davies

--
