== Capítulo II

[.centered]
=== El Amigo y el Ladrón

El valor y la capacidad de mantener la calma que exhibe el verdadero soldado de Jesucristo,
cuando la Divina Providencia le permite atravesar apuros y situaciones duras,
suele ser notorio.
Éste no sólo conoce la fuerza de ese Brazo protector,
que gobierna o domina todas las circunstancias para el bien de los que son fieles;
no sólo está equipado para todas las circunstancias,
y "`de la debilidad se hace fuerte`" hasta el punto de "`cerrar
las bocas de leones,`" y "`apagar fuegos impetuosos,`"^
footnote:[Hebreos 11:33-34]
sino que está abundantemente provisto de rendición
para someterse al Señor en todas las cosas,
y con aquel que estuvo en "`peligros de ladrones,`"
y "`en peligros de muerte muchas veces,`"^
footnote:[2 Corintios 11:23]
puede decir: "`sea que vivamos, o que muramos, del Señor somos.`"^
footnote:[Romanos 14:8]

La conducta de algunos de nuestra Sociedad que han caído en manos de ladrones,
y que debido a sus escrúpulos religiosos se han visto impedidos (como
es de esperar) de tomar represalias violentas incluso en su propia defensa,
ilustra este rasgo del carácter cristiano.
Se dice de Robert Barclay, que cuando regresaba de un viaje en Herfordshire,
su vida se vio en peligro por el ataque de un asaltante.
Esa mañana, su esposa lo había notado más pensativo de lo usual,
y él le comentó que creía que ese día el grupo iba a sufrir
una prueba poco común. Cuando el asaltante sacó su pistola,
Robert Barclay le preguntó calmadamente,
"`cómo había llegado a ser tan descortés,`" y lo tomó por el brazo;
ante lo cual el asaltante dejó caer la pistola y cesó la amenaza.
También se dice de Leonard Fell, uno de los hijos del Juez Fell, que viajando solo,
fue atacado por un asaltante que le pidió su dinero, y él se lo entregó;
luego le pidió el caballo y Leonard desmontó y dejó que se lo dejara.
Entonces, al sentir el poder de la Verdad levantarse en su mente,
Leonard se volvió hacia el asaltante y bajo la autoridad de ella,
solemnemente le advirtió de la maldad de sus caminos.
Entonces el asaltante enfurecido le preguntó al Amigo, por qué le estaba predicando,
y lo amenazó con volarle los sesos.
Pero Leonard le respondió: "`Aunque no daría mi vida por mi dinero o por mi caballo,
la daría para salvar tu alma.`"
El asaltante quedó tan impactado,
que dijo que como se trataba de un hombre de ese calibre,
no le quitaría ni su dinero ni su caballo; y tras devolver ambos al fiel Amigo,
siguió su camino,
dejando a Leonard disfrutando la paz que acompañó al sincero descargo de su consciencia,
que obtuvo al no considerar su vida como preciada.

[.centered]
=== Relato de John Woolman

En su diario, John Woolman ofrece el siguiente relato instructivo, el cual, creemos,
que pocos de los que están verdaderamente preocupados
por los asuntos de la verdadera piedad,
y de la religión práctica establecida por la Cabeza de la Iglesia,
leerán con desinterés. Quizás sea bueno,
que todos tomen muy en serio los pensamientos que surjan
al contemplar el cristianismo genuino y primitivo,
y que examinen en qué medida, como individuos,
están contribuyendo con sus vidas y conductas al crecimiento de esa vanidad,
orgullo y mentalidad terrenal que son demasiado comunes.

[.embedded-content-document]
--

En nuestra reunión anual en Filadelfia, el veinticinco del noveno mes de 1764,
John Smith, de Marlborough, de más de ochenta años, un ministro fiel,
aunque no elocuente, se levantó en nuestra reunión de ministros y ancianos,
y mostrando estar bajo un gran ejercicio de espíritu, les informó a los Amigos,
en esencia, lo siguiente:
Que él había sido miembro de nuestra Sociedad por más de sesenta años,
y recordaba muy bien que durante aquellos primeros años,
los Amigos eran un pueblo humilde y sencillo;
y que en sus reuniones había mucha ternura y contrición. Que veinte años después,
a partir de ese tiempo, la Sociedad había crecido en riqueza, y que en cierta medida,
se había conformado a las modas del mundo,
la verdadera humildad se había hecho cada vez menos visible, y en general,
sus reuniones ya no eran tan vivas ni edificantes.
Que al cabo de cuarenta años, muchos de ellos se habían enriquecido grandemente;
el uso de ropas finas y costosas, etc. se había vuelto algo común entre ellos,
sus hijos y sus hijas,
y que muchos de la Sociedad habían adoptado una apariencia ostentosa en el mundo;
con lo cual,
estas marcas de riqueza y grandeza externas se manifestaban
en algunas de nuestras reuniones de ministros y ancianos;
y por eso, en la medida que estas cosas se volvían más predominantes,
la poderosa sobreabundancia del Espíritu Santo era cada vez menos manifiesta en la Sociedad.
Que había habido un continuo aumento de estos estilos de vida hasta la fecha;
y que la debilidad que se había propagado en la Sociedad,
y la esterilidad que se manifestaba entre nosotros, era motivo de mucho dolor.
Luego, mencionó la incertidumbre de su futura participación en estas reuniones,
creyendo que su final se acercaba;
y habiendo expresado tiernamente su inquietud por nosotros,
señaló que había visto en la luz de la verdad,
que el Señor deseaba sacar a su pueblo de esas cosas en las que se había degenerado,
pero que sus fieles siervos debían atravesar primero
grandes y difíciles ejercicios para lograrlo.

--

[.centered]
=== Extracto del diario de Thomas Story

En sus viajes, Thomas Story llegó al pueblo de Mildorp en Alemania,
y se quedó allí para descansar.
Él y Pieter Leendaars se dirigieron a un lugar de adoración que estaba abierto,
y que pertenecía a los Luteranos, de lo cual escribe en su diario como sigue:

[.embedded-content-document]
--

Observamos varios cuadros e imágenes (según dicen) de Cristo en diversas condiciones,
como en la cruz, en la resurrección, etc. y una de ellas era completamente dorada.
Ahí había Cristos pintados y Cristos de madera, en estatuas e imágenes, cielos pintados,
infiernos pintados, santos pintados,
y todo esto entre profesantes de Cristo que pretendían una
reforma de esa iglesia que está condenada por su idolatría;
todo lo cual está debidamente condenado por las Sagradas Escrituras,
y por la práctica de los santos en todas las eras.
Le pregunté a nuestro anfitrión,
por qué tenían tantas imágenes de Cristo en sus iglesias y casas.
Él respondió: "`Para tener presente a Cristo.`" Yo le respondí:
"`Parece que no aman a Cristo tanto como deberían,
ya que necesitan tantos recordatorios de Su apariencia externa; en cambio,
los cristianos primitivos tenían la mente y el espíritu de Cristo;
llevaban en sus propios cuerpos la muerte del Señor, y cargaban Su cruz en sus corazones,
por la cual estaban crucificados al mundo, y el mundo a ellos,
con toda su ostentación y vanagloria.
Esta Cruz es esa virtud y vida vivas de Cristo que
aparecen en los corazones de los hombres hoy,
tal como aparecía en aquellos días;
obrando los mismos efectos en todos los que creen en ella, la siguen y obedecen,
al ser la gracia salvadora y luz de Cristo para todas las personas.`"
Esto le pareció extraño, basado en el aspecto de su rostro, sin embargo,
considero que correspondía a lo que sentía en su conciencia, porque no dijo más.

--

[.centered]
=== Relato de Algunos Indios

Entre muchos ejemplos que tienden a demonstrar la operación
universal de la gracia divina en el corazón humano,
una en particular surgió hace algunos años,
entre un grupo de indios en la Provincia de Pennsylvania.
Estas personas eran muy fervientes para la promoción de la piedad entre ellas,
entendiéndola como el efecto de una obra interna,
mediante la cual el corazón cambiaba de malo a bueno.
Cuando les pidieron unirse a otros indios en la guerra contra los ingleses,
lo rechazaron rotundamente, sin importar las consecuencias para ellos,
incluso si los indios que combatían los hacían esclavos, o como ellos lo expresaban,
_negros_, y alegaron lo siguiente: que cuando Dios había creado a los hombres,
Su intención no había sido que ellos se lastimaran o se mataran unos a otros.^
footnote:[Ellos han continuado en esta manera de vivir aproximadamente treinta años,
pese a los malos tratos que han recibido de los indios y de otros.
Más aún, recientemente han sido saqueados,
sus asentamientos ubicados en tres pueblos han sido destrozados,
y han sido llevados cautivos a Canadá. Los indios que los llevaron lejos,
explicaron como excusa de esa crueldad,
que ellos se encontraban en su camino y eran un gran
estorbo cuando se dirigían para la guerra.
Ver Pennsylvania Packet, del mes 12, día 22, 1781.]

Tras conversar con ellos respecto a sus perspectivas religiosas,
uno que había sido el instrumento principal para
hacerlos volver al entendimiento del bien,
relató en resumen lo siguiente:

[.embedded-content-document]
--

Que por una providencia particular, había sido sometido a dificultades y dolor,
y llevado a una profunda consideración del estado de las cosas en el mundo;
y que cuando veía la insensatez y la maldad que prevalecían entre los hombres,
sus penas aumentaban.
Sin embargo,
como estaba convencido de que existía un gran Poder que había creado todas las cosas,
su mente había dejado de contemplar este mundo de abajo, para ver Al que lo había creado,
y se engendraron en su corazón fuertes deseos de conocer aún más a su Creador.
Que después, había sido convencido de que el mal no sólo prevalecía en el mundo,
sino que él mismo participaba en gran medida de su influencia mortal;
y finalmente había descubierto, que su propio corazón era malo y duro.
Ante esto, un gran sentido de abatimiento y angustia se habían apoderado de su mente,
preguntándose: qué iba a ser de su alma.
Que estando bajo esa situación había clamado a ese poderoso Ser,
del que él estaba consciente que había creado el corazón del hombre;
y tras un largo tiempo de dolor y perseverancia buscando ayuda,
le había placido a Dios revelarse a su mente,
y poner Su bondad en su corazón. Que había descubierto que había sido levantado,
como él mismo lo expresó, por encima de sí mismo y del mundo,
y había sentido que su corazón había experimentado un gran cambio;
la dureza y la maldad bajo las cuales había gemido por tanto tiempo,
habían sido quitadas, y ahora se había vuelto suave y bueno.
Que había encontrado tanto amor en él hacia todos los hombres,
que pensaba que podía sobrellevar sus ultrajes y abusos sin enojo,
pues creía que así como los corazones de todos los hombres eran malos y duros,
hasta que Dios los hiciese buenos,
los malos tratos que recibía de ellos procedían de esa misma semilla maligna,
bajo la cual él mismo había sufrido por tanto tiempo.

Que esta consciencia de la corrupción de la naturaleza humana,
junto con una constante súplica a su Creador,
para que eliminara la maldad y la dureza del corazón, y lo hiciera suave y bueno,
era lo que él llamaba _religión;_ y que tras sentir el poder de Dios para su consuelo,
se preocupaba de exhortar a sus hermanos a que buscaran
la experiencia de ello en ellos mismos.
Y también añadió, que bajo estos tratos de Dios,
se había dado cuenta de que el espíritu de la religión era un espíritu de amor,
que guiaba a los que lo obedecían a amar a todos los hombres;
pero que cuando los hombres no se mantenían en este espíritu de amor,
un espíritu opuesto conseguía entrar en sus corazones;
y que de ahí surgían todos los males que tanto prevalecían entre los hombres.
Que también se había dado cuenta de que todavía había un espíritu
maligno maquinando para obtener el dominio en su corazón,
contra el espíritu del evangelio;
pero que a los que habían sido visitados por el poder de Dios,
y eran obedientes a la medida de luz y amor que Él se había complacido en darles,
serían más y más fortalecidos y establecidos en Él. Que también
había comprendido la necesidad del bautismo del Espíritu y fuego,
del cual las Escrituras y la experiencia de los fieles en todas las épocas
testifican que todo verdadero discípulo de Cristo debe atravesar;
mediante el cual, a través de la negación y la muerte al yo,
la raíz del pecado sería destruida.
Esto lo describió debido a una visión que había tenido de algo
similar a lo que sería un fuego externo para el cuerpo natural,
por el que debía atravesar para obtener esa pureza de corazón que él deseaba.
Añadió, que mientras contemplaba atentamente este fuego,
había visto un camino muy pequeño cerca,
por el cual podría rodear el fuego y evitar así la dolorosa prueba.
Comprendió que esto representaba el camino,
por el que aquellos considerados sabios habían encontrado
medios para evitar la prueba que debieron haber pasado,
y que aun así, habían conservado un nombre entre los hombres,
como si hubieran sido purificados por ella.

Así este indio,
sin haber sido enseñado por libros y sin conocimiento en lo llamado teología,
mediante el brillo interno de la luz de Cristo en su entendimiento,
explicó el misterio de la piedad de una manera sencilla y sobria;
mostrando que la verdadera religión sigue siendo el poder de Dios para salvación,
que cambia y purifica el corazón,
y lo lleva a una verdadera contrición y sumisa rendición a la voluntad de Dios.
Este ha sido siempre el resultado de Su operación en todos los que, al entregarse a Dios,
se convierten en los verdaderos seguidores y discípulos de Jesucristo.

[.signed-section-signature]
Extracto del Prefacio de A. Benezet al libro _The Plain Path to Christian Perfection_

--

[.centered]
=== Viajes y Aflicciones de George Whitehead

Los miembros de nuestra Sociedad, quienes hoy en día gozan de una vida tranquila y fácil,
en cuanto a las persecuciones externas y a los sufrimientos por causa de la consciencia,
y que no están faltos de los "`bienes de este mundo,`"
quizás puedan extraer alguna lección importante a partir de una
revisión de las diversas y difíciles circunstancias bajo las cuales
se encontraron sus predecesores cristianos en muchas ocasiones.
La fe, el celo, la valentía, la paciencia de aquellos,
conocidos bajo nuestro nombre o bajo cualquier otro,
han de ser a menudo mencionados y recordados,
no sólo como otras tantas muestras del divino poder de la Verdad revelada,
sino también como muchos otros llamados que motivan a seguirlos
de la misma manera que ellos han seguido a Cristo,
modelando la excelencia y la gloria de la salvación que Él ofrece.

Los fragmentos adjuntos tomados del diario de George Whitehead
quizás no sean los más precisos para describir el comportamiento
y los conflictos cristianos desde una perspectiva general,
como otros que podrían haberse incluido; sin embargo, hasta cierto punto,
y en un sentido muy particular, tienen gran peso e importancia.
El primer extracto que está al inicio, se presenta principalmente,
con la ferviente esperanza de que el joven lector pueda considerar ese Poder todo-suficiente,
mediante el cual se lograron tantas cosas,
y a través del cual ellos también pueden vivir aceptablemente
para Aquel que murió por ellos,
cumpliendo el fin de su existencia en la obediencia de la fe.

Durante la época de cosecha del año 1654, George Whitehead,
que por aquel entonces no contaba con dieciocho años,
viajó a pie en la obra del ministerio de Westmorland a York,
acompañado por Edward Edwards, aproximadamente sesenta millas.
Permanecieron allí dos o tres días. Después de esto
se separaron y George Whitehead se dirigió a Lincoln,
a una distancia de ochenta millas, donde permaneció durante una noche.
De allí se fue a Cambridge, un trayecto de al menos setenta millas en línea recta,
que realizó en menos de tres días, "`aunque mis pies,`" dice,
"`estaban bastante doloridos y llenos de ampollas aún antes de salir de Yorkshire;
sin embargo, se curaron mientras viajaba.`" Estuvo en Cambridge dos o tres días,
y de ahí se fue a Wymondham,
que no podía estar a menos de cincuenta millas según los cálculos,
y a Norwich al siguiente día.

[.embedded-content-document]
--

El hecho de que se nos cerraran las puertas de nuestras
casas de reunión durante varios años,
en y alrededor de las ciudades de Londres y Westminster,
y que nuestras reuniones se realizaran en las calles bajo toda clase de clima,
invierno y verano, fue una gran prueba y dificultad para nosotros,
incluso para los mayores y los jóvenes, los hombres y las mujeres.
Sin embargo,
esa prueba no fue tan grande como la de ver nuestras propiedades y medios
de subsistencia arrasados por una jauría de informantes rapaces;
aunque no fue una pequeña prueba para nuestra gente
tener que permanecer a la intemperie en las calles,
durante las grandes, severas y largas heladas y nieve del año 1683,
que se prologaron cerca de tres meses seguidos,
cuando el río Támesis se congeló tanto que los caballos,
carruajes y carretas podían pasar de un lado a otro,
y también se construyó una calle que pasaba por encima.
No obstante, durante toda esa difícil temporada que nos mantuvieron en las calles,
en el helado aire, no recuerdo haber sufrido ningún daño que perjudicara mi salud,
a pesar de que solía asistir con frecuencia a nuestras reuniones en las calles.
En esas ocasiones tomé nota, grande y seria,
de la misericordiosa providencia del Todopoderoso
Dios hacia mí y hacia muchos más de nuestros Amigos,
quienes compartieron la misma misericordia y preservación
durante ese sufrimiento y prueba,
no gracias a nuestros inmisericordes adversarios y perseguidores,
sino a nuestro Padre celestial, a Quien sean dadas para siempre gloria y alabanzas.

En aquellos días teníamos algunas libertades,
y se nos permitía anunciar la Verdad abiertamente en las calles,
así como también hacer súplicas públicas a Dios; sin embargo,
la mayoría de las veces las tropas entrenadas y los oficiales
nos sacaban a la fuerza y nos enviaban a prisión,
o nos metían en la casa de reunión y allí nos retenían
bajo custodia hasta que la reunión de la calle terminaba.
De modo que los ministros y otros entre nosotros,
eran a menudo violentamente interrumpidos y tratados a la fuerza, y por lo general,
apenas se les permitía declarar dos o tres oraciones antes de ser arrastrados.
Sin embargo, en el temor del Dios vivo,
considerábamos que era nuestro deber conservar nuestras
reuniones y esperar pacientemente en Él,
donde a menudo gozábamos de Su presencia para nuestro consuelo,
aún en nuestra silenciosa atención a Él. No estábamos
llamados a luchar ni a contender con nuestros adversarios,
o con los siervos que ellos mismos contrataban, sino a soportar todo con fe y paciencia,
creyendo que a su debido tiempo obtendríamos la victoria.
A menudo tenía ante mí, que el Cordero y sus fieles seguidores obtendrían la victoria,
lo cual me consoló muchas veces en lo secreto; gloria a Su nombre por siempre.

--

[.centered]
=== La Predicación de Edward Burrough

[.embedded-content-document]
--

Aunque joven, era un hombre de inconmovible valentía,
y el Señor lo puso por encima del temor de sus enemigos.
Lo he visto lleno de poder por el Espíritu del Señor. En una reunión en Bull and Mouth,^
footnote:[Bull and Mouth, era el nombre de la casa de reunión de los Cuáqueros.]
sucedió que cuando la sala que era bastante grande se llenó de personas (muchas
de las cuales habían estado en tumultos y peleando unas contra otras),
algunas empezaron a vociferar contra los Cuáqueros acusándolos y culpándolos de herejía,
blasfemia, sedición y cosas por el estilo.
Gritaban que eran engañadores y que confundían al pueblo;
que rechazaban las Sagradas Escrituras y la resurrección;
mientras que otros se esforzaban por defenderlos y hablar de ellos de manera más favorable.
En medio de todo el ruido y el pleito,
este siervo del Señor se puso de pie sobre una banca y con
su Biblia en una mano (porque solía cargar con una),
le habló a la gente con gran autoridad a partir de las palabras de Juan 7:12 que dicen:
"`Y había gran murmullo acerca de Él (Jesús) entre la multitud, pues unos decían:
Es bueno; pero otros decían: No, sino que engaña al pueblo.`"
Y lo que dijo a continuación fue tan adecuado para la discusión entre ellos,
que toda la multitud quedó abatida; se tranquilizaron, prestaron atención,
y se marcharon en paz y con aparente satisfacción.

[.signed-section-signature]
_Memorias de William Crouch_

--

[.centered]
=== El Celo Cristiano

James Gough, en el relato de su propia vida, cuenta de John Ashton de Kilconimore,
(quien era un anciano cuando James Gough lo conoció) diciendo:
"`Cuando él y su esposa estaban en libertad,^
footnote:[Él estuvo en prisión por diezmos, poco después de su convencimiento.]
asistían consistentemente a la reunión en Birr dos veces por semana.
Por lo general,
llegaban caminando hasta allí--aproximadamente siete
millas inglesas--por un camino en muy malas condiciones,
y atravesando un río de ida y de vuelta.
Durante el invierno, en ocasiones necesitaban romper el hielo para cruzar el río;
y John contaba que había llorado al ver la sangre
en las piernas de su esposa tras haberlo cruzado.
En esos días la Verdad era preciosa para sus profesantes, quienes además la poseían,
y ninguna dificultad o peligro podía impedirles llegar a sus reuniones religiosas,
para gozar con sus hermanos la renovación del amor y de la vida divinos.`"

[.centered]
=== Simplicidad del Evangelio

El escritor antes mencionado brinda una vívida ilustración
de los efectos prácticos de esa unción divina,
energía santa, o principio interno de acción,
por el que nuestra Sociedad siempre se ha caracterizado, en mayor o menor medida.
Lo siguiente es un pasaje del mismo diario:

[.embedded-content-document]
--

La Verdad siempre nos ha conducido a la integridad, puntualidad,
y al trato recto en nuestros asuntos externos; a limitarnos a unas pocas exigencias,
y a una condición humilde en la vida,
en lugar de invadir o arriesgar las pertenencias de otros.^
footnote:[Por acumular grandes deudas o tomar prestados los bienes de otros.]
No todos podemos obtener mucho de los tesoros de este mundo,
(ni es algo necesario para nuestro bienestar:
"`la vida del hombre no consiste en la abundancia de las
cosas que posee`") pero todos podemos vivir con poco,
si nuestras mentes se mantienen humildes,
y los apetitos sensuales se someten a la cruz de Cristo.

John Goodwin, de Escargogh en Monmouthshire,
vivía y mantenía a su familia en una granja de cuatro libras al año,
pero con el tiempo la había comprado y mejorado,
de modo que en ese momento calculaba que valía unas seis libras al año.^
footnote:[Una cantidad aún muy pequeña.]
En el primer viaje que hizo en el ministerio, que fue para visitar a los Amigos en Gales,
tenía en su posesión más de cuarenta chelines en efectivo, y si se presentaba la ocasión,
tenía la libertad de gastarlos en el servicio del Señor,
sabiendo que Él podía darle o permitirle conseguir más. Al principio,
cuando empezó a hospedar a los Amigos viajeros (ya que la mayor parte
de aquella reunión se había ido a Pennsylvania) sólo tenía una cama,
la cual se las dejaba, y él y su esposa se alojaban en el establo.

--

Nuestros predecesores en la profesión religiosa,
eran notablemente reconocidos por su hospitalidad y desinterés,
que parecía levantarse en ellos evidentemente de un arraigado sentido del deber
religioso y de ese amor cristiano que los constreñía poderosamente.

[.centered]
=== Thomas Chalkley: Sobre el Uso de la Espada

[.embedded-content-document]
--

Cuando me encontraba en Barbados,
P+++.+++ M. me acompañó de Bridgetown a la casa del abogado Week,
y me contó que cuando había estado anteriormente en la isla,
él y yo habíamos tenido una conversación sobre el uso de la espada.
Él, que en aquel entonces no era de nuestra Sociedad, llevaba una,
pero ya la había dejado, al igual que su negocio,
que estaba valorado en unos cientos de libras al año. En
aquella conversación yo le recordé las palabras de Cristo:
"`Todos los que tomen la espada, a espada perecerán.`"
Y: "`No resistáis al que es malo;
antes, a cualquiera que te hiera en la mejilla derecha,
vuélvele también la otra... Amad a vuestros enemigos,
bendecid a los que os maldicen,
y orad por los que os ultrajan y os persiguen.`"^
footnote:[Mateo 5: 38-44]
Después de exponerle estos argumentos, él me preguntó: "`Si alguien viniera a matarte,
¿no matarías antes que ser matado?`"
Yo le dije que no; que hasta donde yo conocía mi corazón,
prefería que me mataran antes que matar.
A él esto le pareció extraño y quiso que yo le diera mis razones para ello.
Entonces le dije, que si siendo inocente, alguien mataba mi cuerpo,
mi alma podría ser feliz; pero que si yo lo mataba, y moría en su maldad,
él sería inevitablemente infeliz.
Que si él me mataba, es posible que viva para arrepentirse; pero que si yo lo mataba,
no tendría tiempo para arrepentirse.
Por lo tanto, si él me mataba, yo estaría mucho mejor,
tanto en lo que se refiere a mí mismo como a él. Esa conversación
le había causado un gran impresión y lo había afectado tanto,
que me dijo que no había podido olvidarla.
Y cuando nos separamos en Bridgetown,
nos abrazamos con los brazos abiertos de amor cristiano,
lejos de todo lo que podía lastimar o destruir.

--

[.centered]
=== John Churchman: Sobre los Nombres de los Días de la Semana

[.embedded-content-document]
--

Antes de mi viaje a Holanda,
había ido varias veces a la barbería de esta ciudad (Norwich), para que me afeitaran.
La segunda vez que estuve allí,
tuve que esperar un poco para que me atendieran pues el barbero no tenía asistente.
Cuando los demás se fueron, él me dijo que lamentaba que yo hubiera tenido que esperar,
y que esperaba conservarme como cliente;
y que si yo llegaba los sábados y los miércoles por la mañana, no tendría que esperar,
ya que por la tarde llegaban más gente.
Yo le pregunté qué días de la semana eran esos que él llamaba sábados y miércoles;
pareció extrañarse de mi ignorancia, pero no supo explicármelo de otra manera.
Entonces le dije: "`No leo en las Escrituras de días llamados así;`" y él respondió:
"`Eso es cierto.`"
"`Entonces,
¿por qué motivo los llamas así?`" le pregunté. "`Porque es una
costumbre muy común,`" me respondió. "`Supón entonces,`"
le dije, "`que vivimos en un lugar pagano, entre incrédulos que adoran a los ídolos.
¿Debemos seguir sus costumbres porque son muy comunes?`"
Él respondió: "`De ninguna manera.`" Entonces le dije: "`Si no me equivoco,
los paganos le dieron esos nombres a los días de la semana.`" Él dijo:
"`Yo nunca antes había escuchado eso; pero por qué motivo lo hicieron?`"
Le respondí: "`Ellos adoraban al sol el primer día de la semana,
y lo nombraron en honor a su ídolo Sunday (domingo).
Adoraban a la luna el segundo día de la semana, y así fue como surgió Monday (lunes);
y el resto de los días según otros ídolos, porque tenían muchos dioses.
El tercer día lo llamaron Tuesday (Martes), según su ídolo Tuisco;
el cuarto día lo llamaron Wednesday (miércoles) según el ídolo Woden; el quinto día,
según su ídolo Thor, lo llamaron Thursday (Jueves); a partir de Friga, Friday (viernes);
y por Saturno llamaron al sétimo día Saturday (sábado).
Y como yo creo en el único Dios verdadero, y en Jesucristo a quien Él ha enviado,
y espero la vida eterna por medio de ningún otro nombre o poder,
no me atrevo por motivos de consciencia, a reconocer los dioses de los paganos,
ni a llamar un día en honor a ellos;
sino que elijo los nombres con que fueron llamados los días,
cuando el Altísimo llevó a cabo sus diversas obras de la creación, a saber: primero,
segundo, tercero, y así sucesivamente; lo cual es bíblico,
más sencillo y fácil de entender.`"
Él parecía estar algo impresionado por la información,
y le pedí que investigara el asunto por sí mismo,
y que no pensara que yo intentaba imponerle algo.

A mi regreso de Holanda a Norwich, un hombre corrió hacia mi en la calle,
colocó un papel en mi mano y se marchó inmediatamente;
en seguida supe que era el barbero.
La carta contenía un inocente reconocimiento hacia mí por mi franqueza hacia él,
como ya se ha mencionado,
en un lenguaje que mostraba un aprecio un poco exagerado hacia mí como instrumento.
Creyendo que él había sido alcanzado por el amor de la Verdad, y en cierta medida,
convencido de Su principio,^
footnote:[La palabra "`principio`" era utilizada
a menudo por los Amigos para referirse a la Semilla,
Palabra o don de Gracia en el corazón,
que es la fuente y el comienzo de la obra de Dios en el hombre.]
consideré que era mejor encomendarlo en las manos del Señor para mayor instrucción.

Hago mención de este fragmento con el objetivo de
animar a mis amigos de la misma santa profesión,
para que su lenguaje en palabras sea el verdadero
lenguaje de la verdad para con todos los hombres,
en pureza de espíritu,
y a no llamar los días de la semana o los meses según costumbres idólatras y paganas,
alegando como excusa, que aquellos a quienes hablan los entienden mejor,
y así les ahorran cualquier explicación adicional.
Dicha excusa está lejos de proceder de una disposición "`apta para enseñar,`" (2 Tim.
2:24) y dejar que la luz de la Verdad brille como debe hacerlo.
Nuestro bendito Instructor dijo: "`Ni se enciende una luz y se pone debajo de un almud,
sino sobre el candelero, y alumbra a todos los que están en casa.`"^
footnote:[Mateo 5:15]
Ni tampoco enciende el Señor Su candela^
footnote:[Proverbios 20: 27, es decir, el espíritu del hombre.]
mediante el conocimiento puro de la Verdad, para que la cubramos,
ya sea con una disposición cómoda para evitarnos problemas,
o para que ocultemos Su obra bajo el almud del "`afán de este siglo y el engaño
de las riquezas,`" en pos de las ganancias y los tesoros de este mundo;
sino para que sea puesta sobre el candelero,
y corone así a los que son favorecidos con la santa luz,
para que como una ciudad asentada sobre un monte, no puedan ser ocultados.
Este lenguaje corrupto de usar "`ustedes`" a una sola persona,
y llamar a los meses y días con nombres paganos, algunos lo consideran una pequeñez;
pero si un fiel testimonio en estas pequeñas cosas fue de gran bendición,
como en el caso antes mencionado,
hasta el punto de suscitar una ferviente búsqueda del conocimiento
salvador de Dios y de Su bendito Hijo,
a Quien conocer es la vida eterna;
quizás aquellos que se resisten a dar testimonio del talento
puro de la Verdad que se les ha sido dado para que lo utilicen,
algún día tengan su porción asignada con el siervo malo y negligente.^
footnote:[Ver Mateo 25: 24-26]

--

[.centered]
=== Anécdota de Thomas Chalkley

Thomas Chalkley, de viaje en Nueva Inglaterra, relata que cerca del año 1704,
los indios había sido muy bárbaros en la destrucción de los habitantes ingleses.
A algunos les arrancaron la cabellera, y a otros les destrozaron el cerebro (hombres,
mujeres y niños,) por lo que el pueblo estaba muy alarmado, tanto de noche como de día.

[.embedded-content-document]
--

Pero +++[+++continúa él,]
al gran Señor de todo le plació preservar a nuestros Amigos maravillosamente,
en especial a los que se mantuvieron fieles a sus principios pacíficos,
según la doctrina de Cristo en las Sagradas Escrituras,
tal como se registra en Su excelente sermón que predicó en el monte,
que es totalmente opuesto a matar, vengarse y destruir, incluso a nuestros enemigos.

Y puesto que nuestros Amigos no podían unirse a aquellos principios y prácticas de guerra,
algunos de ellos fueron puestos en prisión;
muchas personas los insultaban y hablaban muy duramente en contra de sus pacíficos vecinos,
deseando que los Cuáqueros fueran eliminados.
De entre los cientos de personas que fueron asesinados, sólo oí hablar de tres Amigos,
cuya destrucción fue muy notable, según me informaron;
uno de ellos era una mujer y los otros dos eran hombres.
Los hombres solían ir a su trabajo sin armas,
confiando en el Todopoderoso y dependiendo de que Su providencia los protegiera
(pues su principio era no utilizar armas de guerra de forma ofensiva hacia otros,
ni para protegerse a sí mismos);
pero un espíritu de desconfianza se apoderó de sus mentes,
y tomaron armas de guerra para defenderse.
Como los indios los habían visto muchas veces sin armas, los habían dejado en paz,
diciendo que eran hombres pacíficos y que no lastimaban a nadie,
y que por consiguiente ellos no los lastimarían; pero ahora, al verlos con armas,
creyeron que pretendían matar a los indios, y por eso los mataron a tiros.

La mujer se había quedado en su casa,
y no sentía la libertad de ir a algún lugar amurallado para su protección, ni ella,
ni su hijo, ni su hija, ni llevar a los pequeños allí. Pero después de un tiempo,
la pobre mujer dejó entrar un miedo servil,
y les aconsejó a sus hijos que fueran con ella a un fuerte
que no estaba lejos de donde vivían. Su hija,
al ser una persona que confiaba en el nombre del Señor--torre fuerte al que los
justos acuden y encuentran protección--no pudo consentir ir con ella.
Ella dejó un relato particular en una carta dirigida a sus
hijos sobre la preservación de ella y la de ellos.
Pienso que es digno incluirla aquí en sus propias palabras:

"`Cuando a los crueles indios se les permitió matar y destruir,
me fue mostrado que debía permanecer en un testimonio por la Verdad,
y confiar en el nombre del Señor, que era una torre fuerte,
y que debíamos esperar en Él. A menudo deseaba que mi madre
y mi esposo se sentaran y esperaran en el Señor,
y que Él nos iba a mostrar lo que debíamos hacer.
Pero no lograba persuadir a mi esposo,
pues él decía que ya era muy tarde y que estaba urgido por marcharse;
pero yo no podía irme con él, porque temía ofender al Señor. Sin embargo,
él seguía diciendo que yo estaba siendo engañada por el diablo,
por lo que mi madre decía con frecuencia: "`Una casa dividida no puede permanecer.`"
Ella no sabía qué hacer, aunque sentía más paz quedándose,
aun así tenía pensamientos de marcharse, y me decía: "`Hija,
¿puedes decir con certeza qué te ha sido revelado que nos debemos quedar?
Si es así, estoy dispuesta a quedarme;
sólo si estuviera segura de que es la voluntad de Dios.`"
Pero como yo era joven y temía hablar con tanta confianza, dije: "`Mamá,
yo puedo decir que cuando pienso en quedarme y confiar en el nombre del Señor,
encuentro una paz y consuelo tan grandes que no puedo expresarlos,
junto con la convicción de que seremos preservados.
Pero cuando pienso en marcharme, ¡oh! la angustia y la carga que siento,
junto con el temor de que algunos de nosotros caigamos en sus manos.`"
Entonces mi querida madre suspiró y dijo que no sabía qué hacer;
pero yo les dije que si ellos se iban, yo estaba dispuesta a permanecer sola;
que si encontraban libertad de irse, yo estaba muy dispuesta a quedarme,
pues temía ofender al Señor. Sin embargo,
mi pobre esposo decía que yo había aceptado a un espíritu equivocado como si fuera correcto.
Y me preguntaba: "`¿Cómo lo sabes?
Porque si tuvieras el espíritu correcto,
deberías estar dispuesta a someterte a mí.`" Entonces le dije,
que en sumisión a él me mudaría; pero que esperaba que el Señor no me condenara por ello,
porque de no ser por sumisión a él, no me mudaría por nada en el mundo.

Y tras haber rendido mis fuerzas,
al poco tiempo llegaron dos hombres de la guarnición con sus armas,
diciéndonos que venían por nosotros,
y que ellos creían que los indios podrían estar acercándose; entonces nos fuimos.
Mi madre fue con mi cuñado, a pesar de que intenté persuadirla de que no lo hiciera.
Pero me dijo: "`Mi hijo está allí; ¿por qué no puedo estar con él tanto como contigo?`"
Así que nos dirigimos a Hampton, a casa del hermano de mi esposo.
Pero, ¡oh,
el temor y la angustia que sentía! Le dije a mi esposo que parecía
como si nos estuviéramos metiendo en la boca de los indios.
Al día siguiente, que era el primer día de la semana,
nuestra querida Amiga Lydia Norton llegó con mi querida mamá;
y en su testimonio en una reunión, dijo que allí había alguien muy cercano a su vida,
que estaba muy cerca de la muerte.
Oh, entonces yo estuve lista para pensar que sería yo,
porque creía que nos habíamos equivocado al mudarnos,
y me encontraba en gran aflicción. Entonces se lo hice saber a mi querida Lydia,
pero ella me consoló tanto como pudo, y me dijo que no creía que fuera yo.
Mi querida madre se fue de nuevo a casa de mi hermana en la guarnición,
donde no se sentía tranquila; sino que, como solía contar a algunos,
se sentía en una condición nublada,
y más alejada del consejo divino de lo que jamás había estado desde que conocía la Verdad.
Como estaba inquieta, se mudó a la casa de unos Amigos que vivían en el vecindario;
y mientras lo hacía,
los sangrientos y crueles indios que estaban en el camino la mataron.

¡Oh, entonces cuánto lamenté haberme mudado!
Y prometí que si el Señor se complacía en perdonar mi vida,
la de mi esposo y la de mis hijos, y nos llevaba de nuevo a casa,
jamás volvería a hacer algo así. Pero, ¡oh, el temor,
la aflicción y la oscuridad que cayeron sobre mí,
y sobre muchos otros durante aquella época!
Tres o cuatro de nosotros mantuvimos nuestra reunión, sin embargo,
a pesar de que nos sentábamos y esperábamos tan bien como podíamos,
permanecíamos bajo una pobre y nublada condición; así fue hasta que regresamos a casa.
Entonces le plació al Señor hacer resplandecer la luz de Su amor,
sobre nuestras pobres almas.

Entonces le dije a mi esposo,
que aunque había construido una casita cerca de la guarnición, no podía mudarme de nuevo.
Él estuvo dispuesto a quedarse hasta que terminara el invierno,
pero me advirtió que no podía quedarse cuando llegara el verano,
porque entonces los indios rondarían por ahí;
y que si yo no estaba dispuesta a ir a la guarnición,
podría ir a la casa de un Amigo que estaba cerca de ella.
Yo estaba dispuesta a complacerlo si era la voluntad del Señor,
y luego dispuse mi corazón para conocer la mente de la Verdad.
Entonces me fue mostrado que si me mudaba de nuevo,
perdería el sentido de la Verdad y nunca más levantaría cabeza.
Sin embargo, mi esposo seguía diciendo que era una idea mía;
hasta que llegó nuestro Amigo Thomas Story y le dijo a mi esposo,
que no veía cómo yo podría tener una revelación de
la voluntad del Señor mayor que la que tenía entonces.
Su respuesta complació tanto a mi esposo, que nunca más me pidió que me mudara,
sino estuvo muy contento de quedarse durante todas las guerras.
Entonces las cosas se hicieron más fáciles,
y vimos la riqueza de las maravillosas obras y del gran poder del Señor,
al guardarnos y preservarnos cuando los indios asechaban nuestras puertas y ventanas,
y en otras ocasiones también, y cómo el Señor puso valor en ustedes, mis queridos hijos.
No lo olviden, y no piensen que como eran niños y no sabían mucho, no temían nada;
sino recuerden con frecuencia,
que cuando se quedaban solos en casa mientras nosotros asistíamos a las reuniones,
el Señor los estaba preservando y guardando para que ningún daño los alcanzara.
Les dejo este encargo:
Vivan en el temor del Señor y procuren tenerlo siempre delante de sus ojos,
no sea que pequen contra Él;
porque si yo no hubiera temido al Señor y sentido los consuelos de Su santo Espíritu,
nunca hubiera podido soportar semejante prueba,
cuando muchos me juzgaron y dijeron que yo estaba engañada,
y que la sangre de mi esposo y de mis hijos sería demandada de mis manos.
Pero el Señor estaba cerca de mí y me dio fuerzas y valor, y fe para confiar en Él,
porque yo sabía que Su nombre era una "`Torre fuerte,`" sí,
y más fuerte que cualquiera en el mundo;
pues muchas veces he huido allí en busca de refugio.
¡Oh, alabanza y honor, y exaltación perpetua sean dadas al Señor y a Su querido Hijo,
nuestro Salvador y Mediador, Jesucristo.
Amén.`"

[.signed-section-signature]
Mary Doe

Un vecino de las personas antes mencionadas +++[+++continúa Thomas Chalkley],
me contó que mientras se encontraba en su trabajo en el campo,
los indios lo vieron y lo llamaron, y que él fue donde ellos.
Le dijeron que ellos no tenían ningún problema con los Cuáqueros,
porque eran personas tranquilas, pacíficas y no le hacían daño a nadie,
y por eso nadie debía lastimarlos.
En esa época,
aquellos indios comenzaron a disparar a las personas que viajaban por el camino,
y a golpearlas en la cabeza mientras estaban en sus camas,
y asesinaron bárbaramente a muchas.
Sin embargo, nosotros viajábamos por el territorio y realizábamos grandes reuniones,
y la buena presencia de Dios siempre estaba con nosotros abundantemente;
y experimentábamos un gran gozo interno en el Espíritu
Santo en medio de nuestros peligros y viajes externos.
Por lo general, la gente iba a caballo y acudía al lugar de adoración armada,
pero los Amigos iban a sus reuniones sin espada ni pistola,
puesta su confianza y seguridad en Dios.

--

[.centered]
=== La Raíz y el Fundamento de la Idolatría

Mientras John Churchman realizaba una visita religiosa
a Amigos en la costa oriental de Maryland,
se encontró con un anciano que le preguntó, si había visto unos postes en pie,
y señalándolos añadió,
que la primera reunión que George Fox había tenido de ese lado de la Bahía de Chesapeake,
se había realizado en una tabacalera ahí, que entonces estaba nueva;
y que los postes que estaban en pie eran de nogal.
Ante lo cual,
el compañero de J. Churchman cabalgó hasta los postes
y se quedó sentado en su caballo muy quieto y callado;
luego regresó con más velocidad que con la que se había alejado,
y John le preguntó qué había visto en esos postes viejos.
Él respondió: "`No me habría perdido lo que vi ni por cinco libras;
porque vi la raíz y el fundamento de la idolatría. Antes de dirigirme allí,
pensé que quizás podría sentir alguna virtud secreta
en el lugar donde George Fox había estado y predicado;
quien creo, que fue un buen hombre.
Pero mientras estaba ahí, se me informó en lo secreto,
que si George había sido un buen hombre, estaba en el cielo y no allí,
y que la virtud no se comunica mediante cosas muertas, ya sean postes, tierra,
o cuadros curiosos, sino mediante el poder de Dios,
que es la Fuente de la virtud viva.`" "`Toda una lección,`"
dijo John Churchman "`que si se aprende correctamente,
destetaría de la adoración de imágenes y de la veneración de reliquias.`"

[.centered]
=== Un notable testimonio del poder que acompañó el ministerio de nuestros primeros Amigos.

Una persona de cierta notoriedad que había sido oficial bajo el cargo de Oliver Cromwell,
contó la anécdota a unas personas en una posada,
entre las que se encontraba James Wilson, quien a partir de entonces,
tuvo una opinión más favorable de los Amigos y estuvo dispuesto a asistir a sus reuniones,
pues anteriormente había sentido muchos prejuicios contra ellos.

[.embedded-content-document]
--

Tras la batalla de Dunbar, mientras cabalgaba en Escocia a la cabeza de mi tropa,
observé a cierta distancia del camino una multitud de personas,
y a una más alta que el resto;
por lo cual envié a uno de mis hombres para que viera y me trajera noticias
del propósito de la reunión. Al verlo acercarse y quedarse allí sin regresar,
según mi orden, envié a un segundo hombre, que se quedó de la misma manera;
entonces decidí ir yo mismo.
Cuando llegué al lugar, encontré a James Nayler predicando a las personas,
con tal poder y con tanto alcance, como nunca antes había presenciado.
No pude evitar quedarme un poco, aunque temía hacerlo;
porque el poder de Dios me hizo un "`Cuáquero,`"^
footnote:[La palabra "`Cuáquero`" es un anglicismo
que proviene de la palabra inglesa Quaker,
que significa temblar.]
al verme forzado a temblar ante mi propia condición. Fui
golpeado con más terror por la predicación de James Nayler,
que en la batalla de Dunbar,
cuando no teníamos más expectativas que caer víctimas de las espadas de nuestros enemigos,
sin poder defendernos.
Vi claramente la cruz de Cristo a la que debía someterme,
de modo que no me atreví a quedarme más tiempo.
Me marché y cargué con la condenación de ello en mi propio pecho.
Las personas allí, en la clara y poderosa revelación de sus estados,
clamaban contra sí mismos implorando misericordia, clamando por un cambio completo,
y que toda la obra de salvación se llevara a cabo en ellos.
Desde entonces, me he visto obligado a declarar a favor de ellos, como lo he hecho ahora.

[.signed-section-signature]
Del diario de James Gough

--

[.centered]
=== Un Vistazo a una Reunión Trimestral

En Masham, Yorkshire, John Churchman se alojó en la casa de John Kelden,
quien le contó algo que ocurrió entre un caballero del condado y uno de sus arrendatarios,
un miembro de nuestra Sociedad religiosa, tal como se describe a continuación:

[.discourse-part]
_Terrateniente:_ John, ¿entonces estás ocupado?

[.discourse-part]
_Arrendatario:_ Sí; a mi señor le gusta ver a sus arrendatarios ocupados.

[.discourse-part]
_Terrateniente:_ Pero John, ¿dónde estabas?,
porque el otro día no estuviste en la reunión trimestral de York.^
footnote:[Las sesiones de la corte en York siempre
se celebraban a la misma hora de la reunión trimestral.]
Vi a la mayoría de tus fieles Amigos allí, pero no a ti.

[.discourse-part]
_Arrendatario:_ Bueno,
ya sabes que tengo un señor difícil de complacer que ama que sus
arrendatarios prosperen en sus negocios y paguen su renta a tiempo,
y yo tenía tanto trabajo entre manos que me obligó quedarme en casa.

[.discourse-part]
_Terrateniente:_ ¿Quedarte en casa?
No prosperarás ni pagarás más por descuidar tu deber, John.

[.discourse-part]
_Arrendatario:_ Puedo ver que mi señor estuvo en la reunión trimestral.
¿Te gustó?

[.discourse-part]
_Terrateniente:_
¿Qué si me gustó? Estuve en una sola reunión y vi algo que me hizo doler el corazón.

[.discourse-part]
_Arrendatario:_ ¿Y qué era?

[.discourse-part]
_Terrateniente:_ Bueno, la vestimenta de los jóvenes; los hombres con sus pelucas,
y las jóvenes con sus galas, imitando las modas.
Entonces pensé que probaría otra reunión; así que al día siguiente fui de nuevo,
y entonces concluí que había poca diferencia,
salvo por el nombre entre nosotros--los que ustedes
llaman "`mundanos`"--y algunos de ustedes;
porque ustedes nos están imitando rápidamente en el amor y las modas del mundo.
Así que dije en mi corazón, este pueblo necesita un Fox, un Penn y un Barclay entre ellos.
Y luego se alejó de su arrendatario.

[.small-break]
'''

"`Pensé que sería una lástima,`" añade John Churchman,
"`que se perdiera la verdadera y muy acertada observación de este gran hombre,
entendiendo que fue expresada más en compasión que en son de burla.`"

[.centered]
=== Relato de la Fiebre Pestilente en Filadelfia en 1699

[.section-author]
Tomado de [.book-title]#la Vida de Thomas Story#

[.embedded-content-document]
--

Después de eso, celebramos reuniones en Jericó, Jerusalén y en otros lugares.
Tuvimos una reunión en Newton en la que los Amigos se sintieron
muy afectaos por el testimonio que dio mi compañero Roger Gill,
sobre la muerte de muchos en Filadelfia por causa de una fiebre pestilente,
que estaba muy extendida en ese entonces.
Diez fueron enterrados en un solo día, junto con cuatro más que murieron ese mismo día;
varios de ellos eran buenos Amigos.
Su testimonio fue a modo de advertencia para los Amigos de esa reunión,
para que estuvieran preparados para encontrarse con el Señor,
si por casualidad el golpe de Su mano llegara a alcanzar esos lugares.
Luego Samuel Jennings les recordó a los de la reunión,
que no era algo nuevo o extraño que el pueblo de Dios sufriera en calamidades comunes;
pero como el amor y el favor de Dios estaban asegurados para ellos,
ya fuera que la vida o la muerte sucedieran (según mejor le pareciera al Señor),
no había motivo para temer o para desmayar ante tales cosas,
especialmente para aquellos que estaban preparados como el apóstol, cuando dijo:
"`Porque para mí el vivir es Cristo, y el morir es ganancia.`"^
footnote:[Filipenses 1:21]
Y dado que el paso de la muerte a la vida era la gran ganancia de los santos,
no teníamos motivos para quejarnos por la pérdida de su compañía aquí,
aunque muy apreciada; sino más bien,
que debíamos esperar paciente y diligentemente en el Señor,
hasta que fuera nuestra porción.

A partir de ese momento,
mi compañero se sintió deseoso de ir a Filadelfia para ayudar a los angustiados Amigos;
pero me mantuve en nuestro plan,
que se estableció antes de que nos enteráramos de la condición y las pruebas de ellos.
Nos dirigimos a Nueva York, Woodbridge y Burlington,
reuniéndonos en el camino con algunos Amigos de esos lugares.
Allí oímos más y más de los tristes efectos de la
pestilente fiebre que aún prevalecía en Filadelfia.
De ahí mi compañero fue directamente a Filadelfia, y yo,
tras haber celebrado algunas reuniones en el camino
llegué donde él estaba y lo encontré bien,
aunque muchos otros Amigos estaban enfermos y en sus lechos de muerte.
Sin embargo, la firme y continua presencia del Señor estaba con ellos,
acompañándolos durante ese tiempo.
Tal es la bondad de Dios hacia su pueblo,
que en medio de sus aflicciones corporales o de cualquier otro tipo,
Su santa presencia mitiga grandemente los ejercicios de la naturaleza,
mediante su divino consuelo.

¡Oh, el amor que fluía en mi alma hacia muchos durante el tiempo de mis visitas!
En esos momentos me sentía elevado por encima de todo temor al contagio, y sin embargo,
con un temor reverencial hacia el Señor en ello.
Por causa de esta enfermedad habían muerto seis,
siete y algunas veces hasta ocho personas al día por varias semanas seguidas;
y siendo que la reunión anual debía iniciar al día siguiente,
tuvimos ciertas consideraciones y conversaciones al respecto,
debido a la propagación de la enfermedad en la ciudad en ese entonces;
aunque no tanto en el campo.
Por ello, algunos Amigos escribieron desde Burlington,
proponiendo a los Amigos de Filadelfia que la reunión
se aplazara para una época más fresca;
a lo cual se respondió, que hasta que la reunión no se celebrara,
no tenían la potestad para aplazarla; pero pensaban que sería bueno desalentar,
en todo lugar,
al gran número de jóvenes y criados que solían llegar a la ciudad en esas ocasiones;
y que sólo acudieran los que necesariamente estaban
involucrados en el servicio de las reuniones,
debido a la gran infección y a la falta de capacidad
de los Amigos y de las posadas del pueblo,
en semejante momento, para alojarlos y atenderlos,
ya que había pocas casas (por no decir ninguna) donde no hubiera enfermos.

En la reunión matutina de los ministros y ancianos,
el séptimo día de la semana en Filadelfia,
estábamos bajo una gran preocupación sobre si debíamos
llevar a cabo la reunión a la hora usualmente conocida,
o si era mejor suspenderla.
Y mientras esperábamos el consejo del Señor, el testimonio de la Verdad, en general,
se opuso al aplazamiento o suspensión,
y la presencia del Señor nos acompañó en gran manera hasta el final.
Aunque encontramos algo de oposición por parte de los que se creían sabios entre nosotros,
quienes consultaron su propia razón y no a la Verdad;
Quien tiene todo el poder y puede hacer y prevenir lo que a Él le plazca.

Por lo tanto, al día siguiente, el primer día de la semana, se llevó a cabo la reunión,
y fue numerosa, teniendo en cuenta todas las circunstancias.
El Señor se manifestó tan evidentemente con nosotros,
que no quedó ninguna duda de que Su voluntad era que lleváramos
a cabo nuestras reuniones y sirviéramos a Dios de ese modo,
tanto en tiempos de adversidad y aflicción,
como en tiempos de prosperidad y momentos de menos peligro aparente.

En general, los Amigos se sintieron muy reconfortados en la Verdad divina,
el temor al contagio fue en su mayor parte quitado,
y el testimonio de la Verdad fue sumamente glorioso en distintos instrumentos,
como también sobre la reunión en general; y así continuó hasta el final.
El primer, segundo y tercer día fueron de adoración,
y el cuarto para asuntos de administración;
los cuales también se manejaron en sabiduría y unanimidad,
y acabaron en dulzura y armonía;
como corresponde a todas las reuniones del pueblo de Dios en todas partes.

Pero sucedió algo muy sobresaliente:
a pesar de que la enfermedad había sido muy agresiva
y contagiosa durante toda la semana anterior,
no hubo ningún enfermo mientras duró la reunión--tanto
entre los que asistieron en esa ocasión,
como entre las personas del pueblo--que pudiera ser recordado por los Amigos presentes.
Sin embargo, poco después, muchos del pueblo se enfermaron y varios murieron,
pero pocos en comparación con la cantidad que había fallecido anteriormente.
Y al poco tiempo, fue finalmente detenida por la buena mano de la divina Providencia.

Mi compañero y yo permanecimos en el pueblo durante algún tiempo,
visitando a los Amigos enfermos, según considerábamos necesario o conveniente.
La presencia del amor de Dios fue grande con los Amigos,
en medio de esta dura visitación, lo cual nos dio la oportunidad de decir:
"`Bueno es el Señor, y muy digno de ser temido, amado y obedecido.
Porque aunque Él permite que las aflicciones alcancen a Su propio pueblo escogido,
al igual que a los demás hombres, aun así, eso que sería intolerable de otro modo,
se convierte en nada,
en la medida que el sentido de ello es absorbido y sumergido en Su divino amor.
¡Oh, ese amor que derrite! ¡Oh, la dulzura inmortal que gocé junto con muchos otros,
mientras yacían bajo el sufrimiento del mal devorador,
aunque indescriptiblemente consolados en el Señor! ¡Que mi alma siempre lo recuerde,
y espere humillada delante del Señor hasta el fin de mis días! ¡Grande fue la
majestad y la mano del Señor! ¡Grande fue el temor que cayó sobre toda carne!
No vi ningún semblante altivo o arrogante,
ni oí ninguna broma vana que impulsara a los hombres a la risa,
ni una respuesta ingeniosa para levantar jocosidad,
ni banquetes extravagantes para incitar las pasiones y deseos de la carne.
Sino que todos los rostros palidecieron, y muchos corazones se humillaron,
y los semblantes cayeron y se hundieron,
como los que esperan a cada momento ser convocados
al tribunal y ser contados para el sepulcro.
¡Pero los justos aparecían con su rostro descubierto, y andaban erguidos en las calles,
y se regocijaban en secreto en ese amor perfecto que echa fuera todo temor;
y cantaban alabanzas Al que vive y reina y es digno por siempre,
rindiéndose a Su santa voluntad en todas las cosas, y diciendo: "`Sea hecha Tu voluntad,
en el tiempo y en la eternidad, ahora y para siempre.`" Ni el amor al mundo,
ni el temor a la muerte, pudieron impedir su rendición, reducir su confianza,
o nublar sus goces en el Señor.

Entonces mi compañero cayó enfermo y parecía mostrar los síntomas
de la enfermedad común. Como ya había concertado algunas reuniones,
no podía quedarme con él; y aunque me dijo en el momento en que me despedía,
que estaba bastante tranquilo y no tan enfermo,
aun así me marché con una gran carga sobre mi espíritu, sospechando lo peor,
pues él había orado en la reunión anual con gran celo y fervor,
para que el Señor se complaciera en aceptar su vida como sacrificio por su pueblo,
para que se detuviera el contagio.
En esto se mostró su gran amor y preocupación por los Amigos,
a quienes había venido a ver desde muy lejos.

Me dirigí a Burlington, y allí tuve una reunión bastante grande en la casa de John Shin;
luego regresé a Filadelfia unos días después, y encontré a mi compañero muy enfermo.
Mi preocupación por la reunión anual en Maryland se incrementaba,
y me resultaba muy difícil dejarlo en esas circunstancias;
pero habiendo considerado debidamente cada aspecto,
y habiendo encontrado que no sería de mucha ayuda para él, me marché,
aunque no sin sentirme profundamente conmovido.
En compañía de varios Amigos, me dirigí a Maryland,
llevando a cabo reuniones en el camino,
y la consoladora presencia del Señor estuvo con nosotros,
¡para alabanza de Su santo nombre, que vive y que es digno de reinar para siempre!
Al cabo de una semana,
recibí la dolorosa noticia de la muerte de mi compañero Roger Gill, en Filadelfia;
ante lo cual mi alma se conmovió grandemente y mi corazón se compungió,
tanto que el suelo donde yo estaba sentado se mojó con mis lágrimas.
Tras lo cual quedé completamente convencido de que él había
obtenido la corona de eterna paz con el Señor,
y que su recuerdo no se marchitaría,
ni su testimonio vivo se perdería en esas partes de América,
donde habíamos trabajado juntos, desde las Carolinas hasta Nueva Inglaterra.
¡Muchos corazones fueron enternecidos por él,
las almas fueron consoladas y muchas personas fueron convencidas;
todo mediante ese divino poder por el cual ahora él había sido levantado a la gloria,
para cantar alabanzas Al que se sienta en el trono, gobierna y reina,
y es el Único digno por los siglos de los siglos! ¡Amén!

Esto dio lugar a una profunda humillación y reflexión,
sobre cuánto tiempo y cuán a menudo el Señor me había preservado, y con qué fin.
Pues no tengo ningún interés en el mundo, ni nada cuyo disfrute me haga desear vivir,
excepto que le plazca al Señor y dador de la vida preservar la mía,
hasta que esté más preparado para presentar mis cuentas delante de Él.

--
