== Capítulo III

=== Relato de William Crouch

William Crouch, ha dejado registrado en su historia,
un relato que se considera de gran interés,
para aquellos lectores que aman ver el surgimiento y la manifestación de la sagrada
Verdad en sus diversas y sucesivas expresiones sobre la tierra.
Como se relata a continuación:

A principios del año 1654,
algunas manifestaciones del poder de la Verdad comenzaron a sentirse entre
algunas personas de corazón tierno en la ciudad de Londres y sus alrededores,
y unas cuantas fueron convencidas y vueltas al Señor. Durante ese tiempo,
dos mujeres que venían del norte a la ciudad, a saber, Isabel Buttery y su compañera,
conocieron, por una providencia divina que no puedo explicar,
a Amos Stodart (quién fue capitán en el ejército del Parlamento,
y tras ser convencido de la Verdad dejó su cargo), y a Simon Dring de Moorfields.
Estas mujeres tenían una carta o testimonio dado por George Fox,
(la primera incluida en el volumen de sus Libros Doctrinales,
dirigida "`A todos los que quieran conocer el camino al reino,
ya sea que estén en formas, sin formas, o por encima de las formas`"),
que instaba a las personas a volver sus mentes hacia dentro,
donde se debe escuchar la voz de Dios.
Esta carta, una vez impresa,
fue entregada o repartida en el extranjero por ellas entre aquellos que deseaban recibirla.^
footnote:[Este tratado ha sido reimpreso recientemente.]

Isabel Buttery, junto con la otra mujer,
caminaba en compañía de Amos Stodart y Simon Dring por los campos hacia Stepney,
cuando fueron alcanzados por Ruth Brow, que en ese entonces tenía unos dieciséis años,
(y que más adelante se convirtió en mi esposa).
Isabel Buttery, mirándola fijamente,
le entregó una de las cartas impresas mencionadas anteriormente, y al leerla,
Ruth fue convencida de la Verdad y se sumó al pequeño
número de los que entonces creían. Tras esto,
estas mujeres tuvieron reuniones privadas en la casa de Robert Dring, en Watling Street,
y en la casa de Simon Dring en los campos de Moot,
donde solían compartir algunas palabras.
Mi esposa asistía a esos lugares con gran expectativa, y allí se encontró con Ann Downer,
quién más adelante se convirtió en Ann Whitehead,
una honorable joven que creció en la Verdad,
y que posteriormente se convirtió en un instrumento
eminente en la mano del Señor en su tiempo,
como se aprecia en los numerosos testimonios dados por varios Amigos, hombres y mujeres,
tras su fallecimiento,
quienes fueron testigos de su fe hacia Dios y del servicio en Su iglesia.

Por otra parte, en el quinto mes del año 1654,
le plació a Dios enviar a dos de sus fieles mensajeros
e idóneos ministros a la ciudad de Londres,
a saber, Francis Howgill y Edward Burrough,
quienes fueron los primeros en declarar la Verdad públicamente allí,
y a quienes Él hizo instrumentos en Su santa mano para reunir a
muchos que estaban "`esperando la consolación de Israel`". Estos,
al oír las buenas nuevas del Evangelio, podían decir: "`Hemos esperado y nos gozaremos`";
y junto al buen y anciano Simeón--quien tomó al niño Jesús en sus
brazos cuando fue llevado al templo--bendecir a Dios diciendo:
"`Ahora, Señor, despides a tu siervo en paz; porque han visto mis ojos tu salvación;
Luz para revelación a los gentiles, y gloria de tu pueblo Israel`".

Ahora,
puesto que al Señor le agradó visitar la tierna semilla en y alrededor
de la ciudad de Londres mediante Sus instrumentos elegidos,
y abrir los corazones de un remanente para recibir
la palabra de vida y para creer en ella,
éstos abrieron sus puertas para celebrar reuniones en sus casas;
y así continuó por algún tiempo, reuniéndose de casa en casa.

Entonces,
habiendo pregonado y proclamado el grande y notable
día del Señor en la ciudad y en las partes aledañas,
el Señor los movió a visitar la nación de Irlanda.
Cuando llegó el momento de partir de la ciudad,
se convocó una reunión en la casa de Robert Dring, en Watling-street,
para despedirse de sus amigos y hermanos.
En ese momento hubo un gran quebranto de corazón,
y el poder ablandador de Dios estaba entre ellos,
lo que causó gran dolor y muchas lágrimas brotaron de los ojos de muchas plantas tiernas.
Al momento de escribir estas líneas,
todavía viven algunos de los que estuvieron presentes, y al recordarlo,
dan gracias y alabanzas a Dios con sinceridad y rectitud de corazón.

Durante su ausencia y estancia en Irlanda,
le plació al Señor enviar a otros de sus mensajeros y siervos a la ciudad de Londres,
a saber: Thomas Aldam, Christopher Atkinson, Richard Hubberthorn, George Fox,
Alexander Parker, John Stubbs, Thomas Salthouse y otros más,
quienes publicaron y declararon la palabra del Señor con libertad.

=== Testimonio de George Fox sobre Thomas Taylor

George Fox declaró por escrito un testimonio respecto a Thomas Taylor,
del cual se transcribe una parte a continuación.

Él había sido un eminente párroco, y uno de renombre entre los profesantes y sacerdotes,
así como un conferencista en distintas partes del territorio,
dando sermones durante los días de la semana.

Cuando él llegó a Swarthmore en Lancashire, junto con otros sacerdotes,
le pregunté a él y a los demás, frente al Juez Fell,
si alguno de ellos podía decir que había escuchado
la voz de Dios o de Cristo desde el cielo,
ordenándoles ir a hablarle a la gente,
tal como Dios y Cristo lo hicieron con los profetas y los apóstoles.
Y Thomas dijo delante de todos que él nunca había escuchado tal voz o mandato.
Le pregunté qué le predicaba entonces al pueblo.
Él dijo: "`Mis experiencias.
Yo le dije que su experiencia podría no llegar a cada condición,
pero aquel que tuviera la palabra del Señor podría predicarla, el que Dios enviara,
y que eso alcanzaría todas las condiciones.

De modo que la palabra y el poder del Señor lo golpearon de tal forma,
que permaneció en silencio; pero el resto de los sacerdotes eran altivos y se opusieron,
sin llegar a nada.
El Juez Fell se maravilló y asombró de lo que oyó decir a Thomas:
que nunca había oído la voz de Dios ni la de Cristo, enviándolo a predicar a la gente.
Thomas Taylor era considerado un notable sacerdote, por encima de los sacerdotes comunes,
y un hombre sobrio y muy querido entre los profesantes externos.

Ese día fui con él a un lugar llamado Newton, en Lancashire, donde a veces predicaba;
él estaba muy decaído, triste, y gimió esa noche.

Al día siguiente fuimos a una reunión que teníamos en el patio de la casa de adoración,
donde a él le hubiera gustado entrar a la casa, pero el sacerdote no nos lo permitió;
y yo le dije que no había problema.
Luego llegó otro sacerdote de Underbarrow, junto con otros; y Thomas,
que estaba sentado y quieto, finalmente sintió un tierno brote de vida levantarse en él,
y le habló muy bien a la gente desde allí,
tanto de su propia condición como de la del pueblo,
y que debían volverse al Señor Jesucristo.

El sacerdote de Underbarrow y algunos otros profesantes
se ofendieron y se opusieron a él;
sin embargo, el poder del Señor vino sobre todos ellos,
pues durante el tiempo de su sacerdocio se le consideraba superior a ellos.
Thomas Taylor creció en la gracia y en la verdad de Cristo,
llegó a conocer la palabra del Señor y a predicar a Cristo de gracia,
como entonces la había recibido.
Abandonó la casa del campanario de su parroquia, su antiguo salario parroquial,
y al resto de los sacerdotes que predicaban por sueldo;
y viajó por las distintas partes de Inglaterra,
predicando la palabra del Señor y Su Evangelio por gracia, como le fue ordenado.

El relato anterior es el de un hombre sencillo sobre un hecho sencillo.
No se caracteriza por la belleza o el poder del lenguaje; sin embargo,
el lector imparcial reconocerá una excelencia natural e intrínseca en la obra,
y no la despreciará debido a su sencillez.
George Fox, autor de la narración,
es bien conocido que era--como se llamaría hoy--un hombre iletrado y modesto,
no acostumbrado al refinamiento de la época en la que vivió,
y mucho menos al de nuestros días. Desde nuestra perspectiva,
se percibe cierta aspereza o sencillez en su modo de hablar y de escribir,
así como en sus hábitos generales.
Asimismo, él era un caballero en el sentido más literal y estricto de la palabra,
un cristiano en sus modales y comportamiento,
que se esforzó al máximo por fomentar "`paz en la tierra,
y buena voluntad para con los hombres`".

El tema al que él consideró apropiado, en el presente caso,
dirigir la atención y conversación de su grupo, es uno de gran importancia, abarcando,
según se cree, la principal característica del ministerio de los Amigos.
Por lo tanto,
se recomienda especialmente el pasaje a la consideración y seriedad de nuestra juventud,
ya que está diseñado para ofrecer mucha enseñanza sin mucho formalismo.
En verdad, es de temer que algunos de nuestra profesión,
de mayor edad y juicio más maduro, puedan no sentir la necesidad de que se les recuerde,
mediante este sencillo relato,
que el ministro de Cristo no debe de recibir nada menos que la palabra del Señor,
y que cuando se le ordena debe predicarla donde y como se le indique.

Esta visión del asunto corta de raíz los elaborados artilugios
de la mayor parte de los profesantes del cristianismo,
que pretenden alcanzar una supuesta destreza en la predicación,
mediante habilidades humanas.
En realidad,
la santidad--la completa sumisión o entrega a la voluntad divina--hasta donde la conocemos,
y una tranquila expectativa y esfuerzo por lograr una mayor familiaridad con ella,
es lo único que puede preparar al alma para convertirse, mediante la misericordia,
en un instrumento en la mano del Señor para el bien eterno de los demás.

Es extraordinaria la ejemplificación de esta verdad en el caso frente a nosotros.
Thomas Taylor era un hombre erudito y piadoso;
había absorbido todo lo que una educación universitaria podía brindarle;
y siendo estricto en su profesión,
no cabe duda de que estaba seriamente comprometido en obtener todas las ayudas
y apoyos que evidentemente requería el ministerio en el que había sido educado.
Sin embargo, llegó a ver por el renovado poder extendido de la ayuda divina,
que sus perspectivas del ministerio eran deficientes.
Podía decir con el apóstol en el lenguaje de la sinceridad: "`Lo que hemos visto y oído,
eso os anunciamos`"; él predicaba sus experiencias (como reconocía),
pero no había comprendido que su deber era buscar
las manifestaciones de esa "`Palabra de Vida`",
de la que el apóstol habla allí,
por medio de la cual sólo el verdadero predicador del Evangelio está capacitado
para ministrar eficazmente los estados y necesidades de sus oyentes.

El gran Pastor declaró que "`Sus ovejas oyen Su voz,`" y que Él llama a sus propias
ovejas "`por nombre`" y "`las saca`". Y cuando Él "`saca`" a Sus propias ovejas,
"`va delante de ellas,`" y Sus ovejas lo siguen, porque "`conocen Su voz`". No obstante,
este celoso pastor confesó que no había sido consciente
de tratos tan particulares hacia él. Sin duda,
hablaba de cosas buenas a la gente, quizás con las mejores intenciones,
pero si hubiera conocido la aparición interna y la voz de Cristo en su alma,
y se hubiera sometido a Sus instrucciones y límites en sus servicios religiosos,
habría predicado, cuando lo hacía, con la autoridad de una orden divino, es decir,
"`conforme a la palabra de Dios`".

Cuando una persona que profesa el ministerio es llevada
a ver que toda su capacidad para ser verdaderamente útil,
que todo el bien que brota en ella depende completamente de los alcances
particulares y expresos de la gracia celestial en cada instante;
cuando es llevada a rendirse a ella sin reservas en todas las circunstancias,
entonces verdaderamente se puede decir que es "`un instrumento en la mano divina`".

El efecto y la influencia de la predicación del Evangelio en tales instancias,
son a menudo muy sorprendentes, como en el caso de Thomas Taylor,
quien en un corto tiempo se convirtió en un eminente predicador de la Palabra.
Puede decirse de él, como se dijo de su santo Modelo y Maestro,
que "`enseñaba como quien tiene autoridad;`" es decir,
en la "`demostración del Espíritu y de poder`". Así,
muchos fueron vueltos de las tinieblas a la luz, persuadidos de llevar sus obras a ella,
y capacitados para caminar en ella.

Sus escritos siempre serán valiosos para aquellos que buscan sustancia y no apariencia;
algo de la mansedumbre y ternura de Cristo se refleja en la faz de ellos.
Además, en algunas partes se evidencia una profunda experiencia cristiana,
y lo que rara vez se ve en las obras de quienes tienen
cierto grado de conocimientos literarios,
hay en sus escritos una inusual simplicidad de lenguaje y sencillez de estilo,
con tan escasa apariencia de estudio,
que uno podría imaginar que su origen y educación fueron tan humildes
y ordinarios como los de Aquel que fue llamado el "`Hijo del carpintero`",
o como los de sus apóstoles pescadores.

=== Anécdota de la Vida de John Richardson

El gobernador de Virginia quería un tonelero para reparar sus barriles de vino,
sidra y cerveza, y algunos le dijeron que había un obrero cerca, pero que era Cuáquero.
Él dijo que si era buen trabajador, no le importaba la religión que profesara.
De modo que enviaron a buscar al Cuáquero, tal como era,
y llegó con su sombrero bajo su brazo.
El gobernador se sorprendió un poco al ver al hombre presentarse de esa manera,
y le preguntó si él era el tonelero que había enviado a buscar.
Él le contestó: "`Sí.`" "`Bueno,`" dijo el gobernador, "`¿no eres Cuáquero?`"
"`Sí`", respondió el hombre, "`así es como me llaman, pero no he sido fiel`". Entonces,
él le preguntó: "`¿Desde cuándo te llaman Cuáquero`"? El pobre hombre dijo:
"`Cerca de veinte años`". "`Ay de ti, pobre hombre`", dijo el gobernador,
"`¡siento pena por ti!`"

Con esto podemos ver con claridad +++[+++señala John Richardson],
que los que caminan acorde con lo que profesan se hallan
en gran estima entre las personas más reflexivas y religiosas.
En cambio, los profesantes de la Verdad que son infieles y libertinos son despreciados,
y creo que serán cada vez más desechados como "`sal
insípida,`" que no sirve para nada en la religión,
y que ciertamente es pisoteada por los hombres;
pues gran parte de las personas en el mundo comprende
lo suficiente como para saber lo que profesamos,
así como lo que debemos hacer y ser en diversas cosas.
Por lo tanto, caminemos sabiamente ante todos, y no seamos "`causa de tropiezo`",
ni motivo de ofensa ni a judíos ni a gentiles, ni a la iglesia de Dios;
de modo que podamos ser como "`una ciudad asentada
sobre un monte que no se puede esconder;`" es decir,
que no desee ocultarse,
sino que los habitantes de la tierra puedan ver nuestras buenas obras, y a partir de ahí,
tengan motivos para dar gloria al Padre que está en los cielos.

=== Anécdota de la Vida de Thomas Ellwood

Mientras estaba en Londres,
asistí a una pequeña reunión de los Amigos que se
llevaba a cabo en la casa de un tal Humphry Bache,
un orfebre en Tower-street.
Era entonces una época muy conflictiva, no por parte del gobierno,
sino por la chusma de muchachos y gente grosera que, con el cambio de los tiempos,
al regreso del rey, se tomaban la libertad de ser muy abusivos.

Una vez concluida la reunión,
una cantidad considerable de esta gente revoltosa se agolpó en la puerta,
listos para recibir a los Amigos cuando salieran, no sólo con palabrotas,
sino también con golpes;
vi que golpeaban sin reparo a algunos de los que habían salido antes que yo,
y yo también esperaba recibir mi parte cuando estuviera entre ellos.
Pero, contrariamente a mi expectativa, cuando salí, se dijeron unos a otros:
"`Déjenlo en paz; no se metan con él; él no es Cuáquero,
te lo garantizo`". Esto me golpeó y me afectó más
que si hubieran lanzado sus puños contra mí,
como hicieron con los demás. Me inquietaba pensar cuál era el motivo,
o qué vieron estas personas groseras en mí que les hizo pensar que no era Cuáquero.
Tras un detenido análisis de mí mismo, respecto a mi vestimenta y conducta,
no pude encontrar explicación,
salvo que en ese momento llevaba en mi cabeza un
gran gorro de invierno de terciopelo negro,^
footnote:[Un gorro de invierno que tenía solapas para proteger el rostro del frío.]
que al tener las solapas recogidas,
se veía un tanto superior al atuendo común de un Cuáquero;
y esto me hizo perder el gusto por mi gorro.

=== Samuel Bownas

Samuel Bownas recibió una educación religiosa,
ya que sus padres eran Amigos íntegros y celosos,
quienes sufrieron mucho por su fidelidad hacia su Hacedor.

Cuando era niño,
su madre a menudo aprovechaba las oportunidades para
exhortarlo a llevar una vida santa y a temer a Dios,
como el único camino para obtener Su favor y bendición. Ocasionalmente,
le relataba algunas circunstancias de los sufrimientos de su padre en tiempos de persecución,
quien había fallecido antes de que su hijo Samuel cumpliera un mes.
Cuando ella lo llevaba a las reuniones,
donde a menudo daba un testimonio público del poder y la bondad del Señor, él notaba,
siendo muy pequeño,
la ternura y contrición de corazón que prevalecía entre los presentes,
y le preguntaba por qué razón lloraban tanto, y por qué lloraba ella.
Sin embargo, cuando fue colocado como aprendiz,
aunque bajo la tutela de un Amigo honesto y amoroso,
creció sin considerar mucho la religión, ni mostrar interés por ella,
volviéndose adicto a los placeres de la época.
Cuando estaba en las reuniones, por falta de un compromiso adecuado de la mente,
solía desperdiciar esas preciosas oportunidades de crecimiento religioso durmiendo;
ni tomaba muy en cuenta la predicación, aunque allí era abundante.
De este modo transcurrieron dos o tres años de su tiempo como aprendiz,
con un escaso sentido interno de Dios o de la religión. En realidad,
él era considerado un joven ingenioso y sensato (pues
se tomaba mucha libertad para disertar),
pero a menudo, en su cama, meditaba sobre su modo de vida con repulsión,
aunque caía una y otra vez en el mismo proceder.

Nadie podía acusarle de ningún vicio grave; pero era mu y dado a las bromas,
a las conversaciones necias y a giros ingeniosos para provocar alegría,
cosas que el apóstol nos dice que no son convenientes.^
footnote:[Efesios 5:4]
A menudo se daba cuenta de esto una vez que todo había terminado,
y que "`el término de la alegría es congoja`"^
footnote:[Proverbios 14:13]. Sin embargo, el Señor, que es rico y grande en misericordia,
incluso con los rebeldes, lo visitó de una manera tan extraordinaria, la cual, sin duda,
recordó con gratitud durante toda su vida,
ya que parece haber sido el medio para despertarlo a la conciencia de su condición,
e impresionarlo con la más profunda convicción de
la necesidad de un cambio de corazón y vida.

En la reunión de un primer día, Anne Wilson, una joven que estaba presente,
predicó. Ella sentía un gran celo, y viendo que Samuel la observaba,
con gran energía lo señaló con su dedo y pronunció
las siguientes palabras con mucho poder:
"`Un Cuáquero de tradición, llegas a la reunión de la misma manera que sales de ella,
y te vas como llegaste; pero no eres mejor por haber venido.
¿Qué harás al final?`"
Este lenguaje llegó tan profundamente en ese momento, que como Saulo,
podría decirse que fue golpeado como si hubiera caído al suelo,
siendo aguijoneado en lo más profundo del corazón;
y volviendo su mente hacia el interior, clamó en lo secreto: "`Señor,
¿qué puedo hacer para remediarlo?`"
Entonces una voz habló dentro de él diciendo:
"`Vuélvete a mí y yo te ayudaré`". Encontró tal consuelo fluyendo a través de él,
que las lágrimas brotaron en abundancia.
Desde ese día experimentó que la afirmación de las Escrituras era cierta:
que "`lo que de Dios se conoce`" y la verdadera religión "`es manifestado en ellos`".

Tras esta importante circunstancia,
su conducta e incluso su semblante se vieron bastante alterados,
pues su alma estaba postrada bajo un pesado ejercicio,
de modo que no podía ni comer ni dormir como solía hacerlo.
Sin embargo, escribe,
que su trabajo nunca tuvo tanto éxito en sus manos como durante aquel tiempo,
ni su mente estuvo menos interesada.

Él anhelaba que llegara el día de su próxima reunión, y cuando llegaba la hora,
su mente rápidamente se centraba y se fijaba en el gran Objeto de adoración y dependencia,
y sentía en ello un gozo y una satisfacción poco comunes.
Confiando en la fortaleza y la salvación del Señor,
quien había comenzado a revelar Su poder en él de manera maravillosa,
parecía que su entendimiento se abría,
y todas sus facultades estaban tan sensibles que se percibía a sí mismo como otro hombre.
Una dulzura divina y espiritual lo acompañó noche y día durante algún tiempo.
Las Escrituras también se hicieron maravillosamente claras y sencillas ante su vista,
y las verdades del Evangelio de las que ellas hablaban,
las comprendió y abrazó enseguida.
De manera que, en un corto tiempo,
el Señor lo cargó con la inquietud de predicar esas verdades a otros;
y mediante la fidelidad en ese servicio, su ministerio fue de bendición para muchos.

=== Humphrey Smith

Humphrey Smith,
un valioso ministro de nuestro Señor y Salvador Jesucristo y que sufrió
pacientemente por causa de su Evangelio--hasta el encarcelamiento y la
muerte--pronunció un breve e impresionante discurso dirigido "`A todos
los padres de niños sobre la faz de toda la tierra,`" el cual fue impreso
junto con sus escritos recopilados alrededor del año 1683.
Contiene algunas valiosas observaciones a modo de exhortación,
algunas de las cuales se adjuntan a continuación; sin embargo,
las partes que están más relacionadas con el propósito de esta compilación,
son aquellas en las que el escritor menciona ciertas circunstancias o incidentes,
relacionadas con su propia conducta y experiencia en sus primeros años de vida.
Estas son vívidas ilustraciones que reflejan que la sencillez de corazón
y sensibilidad de conciencia conforman la mejor base en la juventud,
y pueden ser fácilmente forjadas y dirigidas para los más sublimes propósitos.
Para aquellos que admiran la sobriedad de conducta y los hábitos tranquilos y moderados,
que por lo general se encuentran entre los hijos de los Amigos,
los siguientes extractos pueden ser interesantes y útiles;
éstos pueden explicar y reforzar algunos puntos de
vista prácticos que esta Sociedad siempre ha adoptado,
y pueden esclarecer de qué manera estos puntos de vista son el resultado
de su "`gran principio:`" la Vida de Dios en el alma del hombre.

Resulta casi innecesario señalar que Humphrey Smith no tenía conocimiento
alguno de los Amigos en la época de la que habla aquí;
de hecho,
él se volvió un predicador público entre los más destacados profesantes de aquel tiempo,
antes de unirse a nuestra Sociedad.

Esto sé con certeza, que en muchos tiernos bebés y niños pequeños hay una semilla mansa,
inocente e inofensiva de Dios, que no quiere la muerte de nadie;
y tienen una luz de Cristo que "`alumbra a todo hombre que viene al mundo`"^
footnote:[Juan 1:9], la cual está dentro de ellos.
Cristo dijo: "`Dejad a los niños venir a mí, y no se lo impidáis`",
porque de aquellos que van a Él, quien es manso y humilde de corazón,
"`es el reino de Dios.`"
Por lo tanto,
deben permitirles que vayan y se aferren a Aquel que es manso y humilde en el corazón;
"`porque lo que se conoce acerca de Dios es evidente dentro de ellos.`"^
footnote:[Romanos 1:19 LBLA]
Cristo, la Luz, amaba a los niños pequeños, y dijo:
"`Si no os volvéis y os hacéis como niños,
no entraréis en el reino de los cielos`". Por tanto,
si aman el bien de sus hijos--tanto del alma como del cuerpo--asegúrense de llevarlos
y mantenerlos en todas las cosas hacia el Testigo de Dios en su interior,
y Él los juzgará y reprenderá por cualquier mal que hayan hecho, y los guardará del mal,
más de lo que ustedes puedan lograr por medio de cualquier otra reprensión. Él +++[+++enséñenles]
les mostrará que la disciplina que ustedes aplican por cualquier mal es justa,
cuando se hace con verdadera moderación, sin exceder la ofensa cometida,
ni procede en lo más mínimo, de un impulso de la naturaleza airada en ustedes.

A fin de que ustedes consideren mis palabras y lleguen
a la moderación y a la sabiduría de Dios,
para caminar de manera ejemplar delante de sus hijos,
y ser para ellos modelos de seriedad, mansedumbre y sobriedad,
pondré delante de sus ojos algunas verdades claras
y simples de mi propia experiencia cuando era niño.

Mi corazón estaba muy conmovido por la ternura,
y las lágrimas eran mi comida y bebida noche y día. A menudo
mi corazón era refrescado con el amor de Dios,
cuando me volvía a ese don que viene de Cristo, el Varón de dolores.
Pero muchos menospreciaban mis lágrimas y rebajaban mi estado de tristeza,
sin saber lo que me pasaba,
como decían. Muchos esfuerzos se emplearon para sacarme de esa condición,
y a medida que crecía, para hacerme correr hacia las cosas del mundo.
Y así, por la naturaleza violenta, feroz e iracunda que gobernaba en otros,
mi quietud era perturbada, lo cual, también engendró en mí ira y enojo contra ellos.
Esto puede ser una advertencia para ustedes; sin embargo,
había algo de Dios en mí que no fue completamente vencido.

Las primeras palabras según las Escrituras que penetraron
mi corazón y permanecieron en mí,
fueron: "`A los hambrientos colmó de bienes,
y a los ricos envió vacíos;`" palabras que quedaron como impresas y selladas en mi corazón.

El amor de Dios prevalecía enormemente en mi pequeño y tierno corazón;
y por eso era mucho más grande el dolor que sentía cuando,
por la mente terrenal y la naturaleza apresurada e iracunda en mis padres y en otros,
era forzado incluso a salir de ese amor, y provocado a la ira,
a la pesadumbre y al descontento, y así, no se me permitía ir ni permanecer en Cristo,
quien dice: "`Yo soy la Luz`";
cuya luz sentía que era mansa y humilde en mí corazón. Por lo tanto,
mi aflicción muchas veces era grande,
y la ira y el apresuramiento comenzaron a tener entrada en mí. Y al darme cuenta de esto,
y encontrar que el amor hacia Dios era mucho más precioso que cualquier cosa del mundo,
y al sentir una esperanza en Él, incluso cuando era sólo un niño pequeño,
a menudo oraba a Dios.
Sí, con lágrimas oraba fervientemente y mi corazón se abría por Su amor.
A veces también clamaba a Él en secreto sobre mis rodillas,
cuando podía hallar un lugar en el que nadie pudiera verme ni saberlo.
Algunas veces, mientras caminaba, cuando venía a mi corazón,
yo (por decirlo así) rogaba y clamaba con muchas lágrimas,
y tenía confianza para dirigirme a Dios, como hacia un amigo cercano,
aunque en mucha sumisión y temor, como alguien indigno,
porque había pecado contra Él. Y para estas cosas
no tenía a nadie que me sirviera de ejemplo,
ni de quien pudiera aprenderlas; y como no conocía a nadie que hiciera lo mismo,
no me atrevía a decírselo a nadie,
ni por qué lloraba tan a menudo cuando alguien me veía;
porque encontré que todos menospreciaban esa condición y eran insensibles a mi estado.

Y así, no teniendo a nadie que fuera sensible a esa tierna Semilla de Dios en mí,
que me enseñara a abrazarla, o que me ayudara a permanecer en ella,
la parte malvada y terrenal que había sido engendrada en mí,
era nutrida por esa naturaleza en la que estaban mis líderes;
de modo que a medida que crecía en años,
esa naturaleza mala crecía más en mí--siendo mi padre más diligente que
la mayoría de los hombres en trabajar y ocuparse de las cosas terrenales--por
lo que la tierna Semilla de Dios quedó velada en mí,
y en años posteriores llegué a ser como un hijo de ira, desobediente a Dios.

Escribo esto para que les sirva de ejemplo y de advertencia,
a fin de que no lleven a sus hijos al mismo alejamiento,
tormento y condenación al que yo fui llevado, especialmente,
porque pocos son los que después vuelven a Dios de
todo corazón y entran por la puerta angosta.
Así que, instrúyanlos en el temor del Dios vivo,
para que en lo postrero tengan consuelo en ellos,
y para que ellos crezcan en la sabiduría de Dios,
de tal modo que tengan dominio sobre las cosas externas y terrenales,
que el Señor o ustedes encomienden en sus manos.

Por lo tanto, para que les vaya bien a ellos y a ustedes,
y para que Dios les haga bien a la postre,
que todos sus hijos sean en todo lugar instruidos
"`en el camino que deben andar`" el cual es Cristo.
Él dice: "`Yo soy la Luz`", y Su luz en ellos les dejará ver que no deben mentir,
ni hablar malas palabras, ni ser violentos unos contra otros.
En esta luz ellos llegan a conocer a Dios y escuchar Su voz,
porque Dios habla por medio de Aquel que es la Luz.
Dios llamó a Samuel, siendo él todavía un niño,
y Elí le dijo al niño que respondiera al llamado del Señor.
Y el niño que respondió al llamado del Señor reprendió al
anciano sacerdote Elí. Los hijos de Elí eran hijos de Belial,
y no conocían a Dios, y +++[+++es notable]
fueron los primeros sacerdotes que tomaron diezmos por la fuerza,
y sufrieron una muerte antes de tiempo bajo los juicios de Dios, al igual que su padre,
quien no los reprendió.

Además,
tengan cuidado de no causar ni permitir que sus hijos hablen muchas palabras vanas,
deleitándose en oírlos parlotear cuando no es necesario; porque así,
después su lengua se vuelve un miembro que no puede ser refrenado,
inflamado por el infierno;^
footnote:[Santiago 3:6]
como yo lo experimenté y sufrí la ardiente indignación del Señor. Las
palabras de sus hijos y las de ustedes como padres deben ser pocas,
sazonadas con sal, a fin de que puedan dar gracia a los oyentes;
porque debemos darle cuenta a Dios por cada palabra ociosa.
Muchos niños pequeños no llegarían a hablar tantas palabras vanas y malas,
que corrompen las buenas costumbres, si no fueran provocados a ello,
y si no vieran que la gente se deleita en oírlos hablar palabras sutiles y astutas.
Algunos padres incluso,
envían a sus hijos a escuelas para que sean educados en sutileza y astucia,
y aprendan cómo ser oponentes muy difíciles de vencer por otros.
Luego dicen que sus hijos pueden vivir de su ingenio y previsión o habilidad,
y valerse por sí mismos, a menudo engañando a los demás. Sin embargo,
en algunos de ellos hay un principio tan sencillo, honesto y sincero en sus corazones,
que no pueden ser llevados a esa ligereza de lengua,
aunque se hayan esforzado mucho por alcanzarla.
Éstos, a veces, no han podido defender su propia causa cuando era justa,
sino que han sido vencidos por otros que tienen más de la sutileza de la serpiente; sí,
han permanecido honestos y simples, y el Señor preserva al simple.^
footnote:[Salmo 116:6]
En esto también he tenido mucha experiencia.

Porque, siendo muy joven, vi con mucha claridad la vanidad de las palabras innecesarias,
y por mucho tiempo fui muy reacio a hablar;
y como en esto y en algunas otras cosas me diferenciaba mucho de los demás niños,
muchos pensaron que era un tonto, como dice los que desprecian "`lo insensato de Dios`"^
footnote:[1 Corintios 1:25]. Por ello, se usaron muchos medios para forzarme a hablar,
y muchas provocaciones una y otra vez, y sin embargo,
casi nada me hacía decir una palabra, porque veía que era innecesario.
Tampoco podía preguntarle a un hombre cómo estaba, cuando veía que estaba bien,
ni podía responder a esas preguntas innecesarias.
Cuando crecí un poco y me enviaban a hacer algún pequeño encargo,
daba mi mensaje con muy pocas palabras,
de modo que las personas pensaban que yo nunca llegaría a ser como un hombre.

Cuando tenía unos diez años, mi padre en la carne a veces me enviaba al mercado,
y pasaba mucho tiempo antes de que él y todos los demás
pudieran obligarme a pedir más de lo que valía el artículo.
Si él no me fijaba un precio,
yo determinaba uno en mi mente según lo que veía en el mercado,
y muy a menudo yo era el que vendía más barato, no estando dispuesto a pedir demasiado,
y por lo tanto, era frecuentemente llamado tonto y burro.
Pero habría sido más fácil para mí si nunca me hubieran sacado
de ese estado en el que Dios me estaba enseñando a hacer a otros
lo que yo quisiera que otros me hicieran a mí.

También temía golpear a alguien, sino que más bien cedía a los que me golpeaban,
y por eso fui maltratado por muchos de mis iguales.
Era difícil para mí quitarle la vida a cualquier animal,
y me oponía mucho a mi padre y a mi madre cuando me mandaban a hacerlo,
aunque sólo fuera matar a un perrito o a un gatito, o algo similar.
Oh, mi vida se afligía al hacerlo y me vi obligado a endurecer
mucho mi corazón antes de poder hacer una cosa así,
aunque fuera por orden de mis padres.
Esto puede servir de advertencia a todos los padres,
para que no sean la causa del endurecimiento del corazón de sus hijos,
y luego digan que son "`chicos duros`";
porque eso que endurece el corazón lo separa de Dios quien es amor, y de Cristo,
quien vino a salvar la vida, y así, no se experimenta el sacrificio de Dios,
el cual está en el corazón quebrantado;
pero el Señor está con el de corazón contrito y humillado.
Tengan cuidado también de no provocar a sus hijos a la inquietud,
ni los molesten cuando están dispuestos a estar tranquilos;
porque muchos no se contentan con ver a sus hijos sobrios y quietos,
sino que los provocan a la ligereza y a los placeres vanos,
cuando ellos preferirían ser sobrios como corderos.
Porque está escrito: "`En descanso y en reposo seréis salvos`"^
footnote:[Isaías 30:15], y procuren "`tener tranquilidad`"^
footnote:[1 Tesalonicenses 4:11], y "`meditad en vuestro corazón, y callad`"^
footnote:[Salmo 4:4].

Cuando era niño, a menudo me sentaba en silencio por largos períodos de tiempo,
reflexionando muchas cosas en mi mente, y a medida que crecía, si no era interrumpido,
me sentaba en silencio por una hora o varias, ya fuera esperando en el Señor Su consejo,
o tratando de entender qué impulso en mí era el que debía guiarme.
Y si cabalgando por un camino me daba cuenta de que lo correcto en mí no me estaba guiando,
me regresaba y abandonaba ese viaje.
A mi tiempo sentado en silencio, mi padre a menudo lo llamaba "`contemplar`",
y con frecuencia me reprendía con dureza por ello, diciendo, a modo de reproche,
que seguramente estaba contemplando convertirme en un gran predicador.
Mi madre se acercó a mí probablemente cientos de veces,
tanto cuando era niño como cuando era adolescente, y con lástima,
ponía sus manos sobre mí y me pedía que no me sentara a contemplar de esa manera,
porque sin duda me convertiría en un tonto;
sin comprender cuál era mi condición. Al sentirme habitualmente perturbado y afligido;
a veces, los primeros-días o cuando podía,
me iba a los bosques o a un lugar apartado para que nadie me pudiera encontrar,
y allí esperaba en silencio tres o cuatro horas;
y a veces el amor de Dios me quebrantaba y Su palabra ablandaba mi corazón,
y sentía entonces lo mismo que ahora se ha convertido en mi vida; porque ahora sé,
que los que esperan en el Señor "`tendrán nuevas fuerzas`"^
footnote:[Isaías 40: 31];
y que aunque esté escrito que el Señor estaba cansado
de los sacrificios del pueblo y de sus palabras^
footnote:[Malaquías 2:17], aun así,
nunca fue escrito que el Señor se cansara de los que esperaban en Él.

Por lo tanto, ustedes deberían permitirles a sus hijos esperar en Dios,
o al menos estar en silencio,
porque "`lo que se conoce acerca de Dios es evidente dentro de ellos`"^
footnote:[Romanos 1:19 NBLH]. El Señor no se ha dejado sin un testimonio en cada conciencia,
porque Cristo ha sido dado como un Testigo, y Su luz resplandece en sus corazones.
Él dice: "`Venid a Mí`" y "`Aprended de Mí`";
porque Él es el Pastor y Obispo de las almas, el cual "`enseña a todos provechosamente`"^
footnote:[Isaías 48:17]. Y Él es ese verdadero Profeta del que habló Moisés,
y cualquiera que no quiera oírlo, su alma será cortada.
Efectivamente,
mi alma fue cortada de la vida cuando fui forzado a dejar de oír Su voz en mí;
la voz de Aquel que es un Varón de dolores y como un cordero mudo.
Por lo tanto, tengan cuidado de no provocar a sus hijos a escuchar a un extraño,
o a otro maestro aparte de Aquel que es un ministro vivo dentro del velo.
Porque el velo está sobre el corazón,
en donde he encontrado al Maestro que nunca será quitado.^
footnote:[2 Corintios 3: 15-16]
Todos los maestros externos pueden ser quitados,
y los sacerdotes y los hombres pueden morir,
pero este Maestro permanece como sacerdote para siempre,
constituido así por el poder de una vida indestructible.^
footnote:[Hebreos 7: 16]

Así que, todos los que llegan conocer algo de Dios en ellos,
también llegan a aprender a sentarse en silencio
y quietud para recibir instrucción de Dios.
Este don no es algo nuevo, inventado por la voluntad del hombre,
o que han aprendido unos de otros, sino que es lo mismo que guiaba a los profetas,
y que estaba en mi corazón de parte de Dios,
incluso cuando era niño. Y ahora afirmo que nunca habría
salido de ese estado degenerado al que fui empujado,
si no hubiera aprendido a esperar y ser obediente a la luz de Cristo
que estaba en mí desde niño. Y todos ustedes pueden ver lo mismo,
a saber,
que siempre ha habido algo en ustedes que los reprendía en secreto por el pecado,
y que les mostraba los pecados de su juventud.
Esa es la luz de Cristo, el hijo de Dios, quien, de tal manera amó al mundo,
que dio a su Hijo como Luz al mundo; dicha luz está en la conciencia de un niño,
y testificará contra él después de que haya hecho lo malo,
y su semblante decaerá como el de Caín. Pero antes de hacer lo malo no se avergüenza,
como Adán no se avergonzaba, siendo inocente.

Esta era mi maestra cuando no conocía a ninguna otra, e incluso antes de saber lo que era.
Este es el don que viene de Dios y no es dado a los
niños por los hombres o por el aprendizaje humano.
Pero los hombres por sus discursos elocuentes y vanos engaños pueden
fácilmente alejar a los niños de la Semilla que está en ellos,
y así quebrantar el mandamiento de Cristo, quien dijo: "`No salgáis`"^
footnote:[Mateo 24:26]. Y cuando ellos son desviados
tras los "`Helo aquí`" y "`Helo allí`",
lejos de la Roca que es Cristo,
y del cimiento seguro que Dios ha puesto y que ningún hombre puede poner otro,
entonces menosprecian esta preciosa piedra angular,
rechazando esa luz que resplandece en sus corazones para darles el conocimiento de Dios.
De este modo, son propensos a seguir fábulas artificiosas, imaginaciones,
sectas y opiniones, y a ser esparcidos por toda montaña seca, estéril y oscura,
en las que el Señor sabe que estuve por mucho tiempo, sin saber dónde hallar descanso.

Porque tras haber sido apartado de mi verdadero Guía y apagados en mí sus tiernos movimientos,
por los cuales al principio podía orar en el Espíritu,
conforme a la medida en que el Espíritu me ayudaba en mi debilidad con gemidos y lágrimas,
luego, después de que crecí, me enseñaron a decir oraciones,
algunas que otros habían aprendido de libros, y me impusieron decirlas cada noche.
Pero yo sentía que era como una retama seca, en lugar de un panal de miel.
Y así, siendo enseñado a usar formas, y a ocuparme de las cosas y maestros externos,
la luz dentro de mí se oscureció,
al igual que mi comprensión del amor del Hijo de Dios derramado en mi corazón.

Siendo a veces sensible a esto, comencé, cuando era muy joven,
a buscar sacerdotes y sermones, pensando que había encontrado la verdad allí. Pero, ¡ay!,
esto me hizo más daño que todo lo demás,
y me alejó más que nunca de mi Maestro y de la búsqueda
sincera de Dios para encontrarlo cerca de mí. También engendró
en mí abundancia de la astucia de la serpiente--sobre todo,
porque siendo consciente de la gran carencia que tenía,
recibía sus hermosos discursos con mucha avidez y ferviente deseo,
creyéndoles que ese era el camino a la paz.
Así crecí mucho en ese conocimiento que hincha,
y eso realmente incrementó mi aflicción. Así fui engañado por ellos;
el Señor Dios sabe que no miento, sino que hablo la verdad con claridad,
sin tener resentimiento contra ninguno de ellos.
Esta es la verdad de mi corazón: que fue más difícil para mí dejar,
negar y experimentar redención de eso que aprendí de y entre los sacerdotes,
que dejar los frutos de todo el pecado en el que alguna vez caí por las tentaciones.

Por lo tanto, permitan que el Señor Dios sea el maestro de sus hijos,
quien les ha dado vida y aliento,
pues no pueden proporcionarles ni dirigirlos a un mejor maestro.
Dejen que Él los conduzca^
footnote:[Salmo 43:3]
y los guíe en Su temor; porque al hacerlo,
ellos verán que deben ser fieles y diligentes hacia ustedes en todas las cosas.
Y no necesitan exigirles muchas otras cosas, no sea que los contristen;
más bien sean ejemplos de justicia para ellos en todas sus palabras y acciones.
Si ustedes no tienen la posibilidad de enviarlos a la escuela a aprender a leer, aun sí,
ellos ya tienen la luz de Cristo en sus corazones,
y eso les hablará claramente acerca del Padre, porque "`el viajero, por torpe que sea,
no se extraviará`"^
footnote:[Isaías 35:8]. Y aunque los envíen a la escuela
por mucho tiempo para aprender a leer y a escribir,
y con lo que aprenden escudriñan las Escrituras, lo cual es bueno, aun así,
ellos deben ir a Cristo la Luz para tener vida, y deben aprender de Él y seguirlo,
a fin de experimentarlo en ellos como la esperanza de gloria,
y el camino para salir del pecado e ir al Padre,
obedeciéndole en todas las manifestaciones de Su voluntad.
Entonces les irá bien y recibirán bendición de Dios,
y serán una bendición para sus padres que temen al Señor,
y al final descansarán en paz y reposo en el pacto eterno de Dios.

=== Enfermedad de John Woolman

En la historia de su vida,
John Woolman brinda el siguiente relato del poder sanador
del Señor manifestado de manera notable sobre él;
y es uno de los muchos relatos que podrían exponerse
para animar al pobre que sufre en su lecho abatido.
Aunque pueda tener en sí mismo "`sentencia de muerte`",^
footnote:[2 Corintios 1: 9]
que confíe en el Dios viviente y esté rendido a sobrellevar y a hacer Su voluntad;
porque "`bienaventurados los que guardan sus mandamientos,
para tener derecho al árbol de la vida`".^
footnote:[Apocalipsis 22:14 RVG]

Le plació al Señor visitarme con pleuresía;
y después de haber permanecido acostado por unos días,
y sintiendo que el padecimiento era muy grave,
medité en cómo terminaría. Desde hacía tiempo, mediante varios ejercicios,
había sido destetado de las cosas placenteras de esta vida; y ahora pensaba que,
si era la voluntad del Señor ponerle fin a mis labores y
recibirme bondadosamente en los brazos de Su misericordia,
la muerte sería aceptable para mí; pero si Su voluntad era refinarme más bajo aflicción,
y hacerme (en cierta medida) útil en Su iglesia, no deseaba morir.
Puedo decir con gratitud, que en este caso sentí que una rendición se obraba en mí,
y no me sentí inclinado a mandar a llamar a un doctor;
creyendo que si era la voluntad del Señor utilizar medios externos para levantarme,
algunos Amigos solidarios serían enviados para ministrarme;
lo cual sucedió. Aunque me atendían cuidadosamente,
aun así el padecimiento a veces se sentía tan pesado,
que pensaba que no me iba a recuperar.
Una noche en particular, el dolor de mi cuerpo era grande;
mis pies se enfriaron y el frío subió desde mis piernas hacia mi cuerpo;
y en ese momento no me sentía inclinado a pedirle
a mi cuidadora que le pusiera algo cálido a mis piernas,
pues pensaba que mi fin se acercaba.
Tras pasar diez horas bajo esta condición, cerré mis ojos,
pensando en que quizás ahora sería liberado de mi cuerpo;
pero en esos terribles momentos,
mi mente fue vívidamente abierta para contemplar la iglesia,
y se engendraron en mí fuertes compromisos por el bienestar eterno de mis semejantes.
Sentí en el manantial del amor puro, que debía permanecer por un tiempo más en el cuerpo,
cumpliendo según mi medida, lo que queda de las aflicciones de Cristo,
y ocupándome del bienestar de la iglesia;
después de lo cual le pedí a mi cuidadora que aplicara calor a mis pies, y reviví.
