== Capítulo IV

=== Extractos de la Vida de James Gough Acerca del Estado de nuestra Sociedad

"`Como Dios dijo: Habitaré y andaré entre ellos, y seré su Dios, y ellos serán mi pueblo.
Por lo cual, salid de en medio de ellos, y apartaos, dice el Señor,
y no toquéis lo inmundo; y yo os recibiré, y seré para vosotros por Padre,
y vosotros me seréis hijos e hijas, dice el Señor Todopoderoso.`"
2 Corintios 6:16-17

Por medio de este llamado nuestros honorables predecesores, en el principio,
fueron separados del espíritu y de los caminos del mundo,
y animados a rehusar tocar lo inmundo, o cualquier cosa que brotara de una fuente impura,
a pesar de la persecución que ese rechazo pudiera costarles;
sabiendo que Aquel a quien ellos obedecían y en quien confiaban los sostendría
a través de toda oposición. Esto lo experimentaron cumplido con gozo inefable,
y lo testificaron al mundo, muchos de ellos tanto con su vida como con su muerte.
En aquella época,
las reuniones de los Amigos eran más eminentemente favorecidas con el poder divino,
ya que vivían más entregados a Cristo,
y en consecuencia rebosaban más de Su amor fluyendo en sus corazones.

Recuerdo, cuando era niño,^
footnote:[James Gough nació en el año 1712.]
a algunos cuyos rostros parecían infundir temor,
y despertar en los observadores seria contemplación;
como "`la sal de la tierra,`" sazonando a aquellos entre quienes caminaban
con un sentido de la Verdad que vivía y predominaba en ellos.
Esos felices hombres y mujeres dejaron la viña del Señor (a través de
sus fieles esfuerzos y con la divina bendición sobre ellos) bien cercada,
limpia y colmada de los excelentes frutos del Espíritu de Cristo,
habiendo recogido las piedras que había en ella.

En mi primer viaje +++[+++a Irlanda, alrededor del año 1737],
aún vivían en la mayor parte de la nación donde se habían establecido reuniones,
algunos Amigos de la buena y vieja estirpe, tanto ministros como ancianos,
que amaban a Dios y a la humanidad, y que eran estimados y amados,
pues eran amables y sinceros,
como también fieles y cautelosos en todas las ramas de nuestro testimonio cristiano,
estrechamente unidos en tierno amor unos con los otros para
apoyar y mantener en buen orden las cosas en la iglesia.
Su piadoso cuidado en esto era como un cerco alrededor del rebaño,
que los mantenía en estrecha unidad y seguridad,
de modo que los jóvenes en la mayoría de los lugares eran en general instruidos
en la inocencia de modales y en la sencillez de costumbres y palabras.
Con el paso del tiempo, estos hombres y mujeres dignos,
en cuyos corazones el amor de Dios y de Su pueblo se había
arraigado profundamente por un largo crecimiento,
finalizaron uno tras otro honorablemente su curso,
dejando tras de sí un distinguido aroma.
Pero cuando fueron removidos, muy pocos de los jóvenes, o de los demás,
les sucedieron en la misma línea,
a fin de ocupar con propiedad los lugares que habían quedado disponibles.

De entre los que quedaron, por un lado,
un número considerable conservaba la antigua sencillez del lenguaje y de las costumbres,
y censuraban rigurosamente cualquier desviación de ello,
gloriándose en esto como si fuera la única prueba y distintivo de discipulado;
mientras sus corazones se habían ido tras su propia avaricia,
persiguiendo con afán y acumulando codiciosamente riquezas temporales.
Por otro lado,
una gran parte de los jóvenes y otros estaban creciendo en la auto indulgencia,
conformándose al mundo y lanzándose de cabeza a las tentaciones de la época.
Sin embargo, en medio de esta marea de negligencia y rebeldía,
permanecía en la mayor parte de los lugares, un remanente de Amigos de corazón sincero,
unos pocos valiosos ministros y ancianos,
pero en estos últimos veinte años ha ocurrido un gran cambio para mal.
¡El amor de Dios se enfría en muchos! ¡Cómo menosprecian los deberes cristianos! ¡Cuán
escasa es la asistencia a las reuniones entre semana para la adoración a Dios,
así como a aquellas que se celebran para nuestro cuidado mutuo en el cuerpo!
De modo que ahora se puede decir de muchos, como en los lamentables días de antaño:
"`Las calzadas de Sion tienen luto, porque no hay quien venga a las fiestas solemnes.`"

De nuevo, cuánta inquietud en las reuniones,
cuántos indicios externos de apatía espiritual, de mentes ausentes o errantes,
de descuido del solemne deber de la adoración que debemos a nuestro gran Creador.
¡Cuánto mirar alrededor o adormecimiento! ¡Cuántas transgresiones
contra nuestro testimonio cristiano en sus diversas ramas,
cuánta debilidad en la conducta e inconsistencia con ese divino principio que profesamos!
Una vez más,
cuántos en estos difíciles días retroceden arrastrando
con ellos a otros hacia las vanidades de la época,
hacia una conformidad con el mundo, tanto en el vestir como en el hablar,
hacia la compañía de quienes se complacen en la misma propensión,
al punto de que las costumbres sencillas y honestas de los
Amigos sinceros y afectuosos están cayendo en desuso,
haciendo que algunos se avergüencen de ellas.
De estas libertades perjudiciales han procedido matrimonios mixtos,
visitas a los sacerdotes en busca de consejo, confusión en las familias,
aflicción y angustia en los padres--heridas dolorosas para nuestra Sociedad cristiana.

Si examinamos nuestra Sociedad en esta nación,^
footnote:[Irlanda]
y echamos un vistazo a los que se visten de manera sencilla y a los que no,
veremos cuántos tienen sus mentes fuertemente arraigadas en este mundo presente,
dedicando todos sus talentos a él,
despreciando el consejo de Cristo que nos dirige
a "`buscar primeramente el reino de Dios.`"
De ahí que, en algunos lugares,
¡qué reuniones tan pobres y sin vida! ¡Qué poco arde el fuego sagrado
del amor divino! ¡Qué poco brilla la gloria de Dios!
No queda entre ellos un ministro vivo,
y apenas un solo miembro vivo del cuerpo de Cristo que se preocupe
por los demás y los cuide con ternura para su propio bien;
sus lámparas se han apagado, y apenas queda aceite en una sola vasija.
De esta manera, algunas reuniones han muerto y desaparecido;
y otras parecen hallarse en un estado lánguido y enfermizo,
mostrando pocas probabilidades de sobrevivir por mucho tiempo,
a menos que recurran a tiempo al gran y buen Médico,
que puede y quiere restaurar la vida, la salud,
la integridad y el vigor para levantar "`jueces como al principio,
y consejeros como eran antes.`"^
footnote:[Isaías 1:26]

=== Relato de Thomas Chalkley sobre su infancia

No puedo olvidar los tratos de Dios conmigo en mis años más tiernos.
Cuando tenía entre ocho y diez años,
mis padres me enviaron a una escuela a casi dos millas de distancia.
Por lo general iba solo a la escuela;
y muchas y diversas fueron las pruebas por las que atravesé
debido a las golpizas y apedreadas que recibía por las calles,
(pues la gente reconocía la religión que yo profesaba,
debido a la señal de sencillez que mis padres^
footnote:[Thomas Chalkley afirma:
"`Nací de padres honestos y religiosos quienes tuvieron mucho cuidado de mí,
y me criaron en el temor del Señor. Con frecuencia me aconsejaban
ser sobrio y me reprendían por la holgazanería,
y tuvieron mucho cuidado de cortar de raíz ese espíritu ligero propio de la juventud;
de modo que tengo motivos para bendecir a Dios por medio de Cristo,
en nombre de mis tiernos padres.`"]
ponían sobre mí,) algunos me decían que no era más pecado matarme que matar a un perro.

Por este tiempo, el Señor comenzó a obrar fuertemente en mi mente mediante Su gracia,
tanto que no podía evitar amonestar a aquellos muchachos
que tomaban el nombre del Señor Dios en vano;
recordándoles el tercer mandamiento: "`No tomarás el nombre de Jehová tu Dios en vano;
porque no dará por inocente Jehová al que tomare
su nombre en vano,`" y lo dicho por Cristo:
"`De toda palabra ociosa que hablen los hombres,
de ella darán cuenta en el día del juicio;`" por
lo que algunos se burlaban de mí y me ridiculizaban,
y otros,
en algunas ocasiones se abstenían de esas malas palabras cuando yo los reprobaba.

En una ocasión, recuerdo que me encontraba entre varios hombres,
y uno de ellos--a quien yo había reprendido antes--les contó a los demás lo sucedido.
Luego se volvió hacia mí y dijo que yo no era cristiano,
y me preguntó cuándo decía el Padrenuestro.
Yo le pregunté si él lo decía,
y respondió que sí. Entonces le pregunté cómo podía llamar a Dios Padre, y, sin embargo,
ser tan malvado como para jurar y tomar el nombre de Dios en vano,
cosa que yo lo había oído hacer muchas veces.
Le cité lo que Cristo dijo a los judíos: "`Vosotros sois de vuestro padre el diablo,
y los deseos de vuestro padre queréis hacer;`" y añadí que
los que hacían las obras del diablo no podían,
según la doctrina de Cristo, llamar verdaderamente a Dios Padre.
Entonces, al ser convencidos en sus consciencias de que lo que yo decía era cierto,
se quedaron en silencio, y se maravillaron de que yo, siendo tan joven,
hablara de esa manera.
Recuerdo que experimenté mucha paz y satisfacción. Desde entonces,
estos hombres me dejaron en paz.

=== Anécdota de William Penn

William Penn, durante una estación de intenso frío,
poco tiempo después de su llegada a América,
cuando se describen que los campos estaban cubiertos de hielo,
se alojó una noche en Merion.
Allí, un niño de unos doce años, hijo del dueño de la casa donde se alojaba,
siendo un muchacho muy curioso y poco acostumbrado a ver un huésped como William Penn,
se escabulló sigilosamente hasta la puerta de la habitación y subió
por una escalera que estaba en el exterior de la casa,
la cual era una sencilla cabaña de troncos.
Al asomarse por el agujero de la cerradura, quedó profundamente impresionado,
al contemplar a este gran hombre sobre sus rodillas
al lado de la cama y al oír con claridad lo que oraba,
pues daba gracias por haber recibido provisión en aquella región salvaje.
Este hecho dejó una impresión tan fuerte en la mente del joven,
que no se borró ni siquiera en su vejez.

=== El Profesor Inmutable

Tomado de los Memorias de Benjamin Bang

Una vez concluida la reunión semestral de Dublín, en el tercer mes de 1683,
tuve la intención de regresar a Inglaterra, y para ello,
vendí mi caballo y me preparé para el viaje; pero como el viento era desfavorable,
no pude partir.
Además, sentí dentro de mí un freno,
pues se me presentó ante la vista un servicio que debía cumplir; al cual me rendí,
aunque muy en contra de mi inclinación. Sentí sobre
mí el peso de llevar a cabo una reunión en Tralee,
en el condado de Kerry.
De modo que salí de Dublín,
participando de las reuniones que se celebraban mientras realizaba mi recorrido,
y llegué a Cork, y de ahí a Tralee (un viaje de unos 254 kilómetros),
donde tuve un tiempo agradable:
muchos corazones se suavizaron y la presencia del Señor se hizo sentir.
Después visité varias reuniones en la provincia de
Leinster y luego me dirigí nuevamente hacia el norte.
Mientras iba de Antrim a Grange,
vi diez o doce hombres en el camino que caminaban muy solitarios;
y estas palabras brotaron de mi corazón: "`Estas son ovejas que no tienen pastor.`"
Cuando llegué donde ellos estaban, disminuí mi paso y les pregunté: "`¿Qué hay de nuevo?`"
Los hombres se quedaron asombrados ante la pregunta y respondieron:
"`No sabemos de nada nuevo.`"
Proseguí en voz baja y les dije: "`¿Se dirigen a alguna reunión?`" Ellos respondieron:
"`Nuestro ministro ha sido silenciado,
pues hemos recibido órdenes de que ningún disidente puede reunirse,
así que ahora no tenemos maestro.`"
Esto me hizo recordar lo que había sentido compartir
en una reunión nocturna que tuve en Antrim,
donde recibí un trato grosero, a saber:
"`El tiempo se acerca en que serán echados como paja aventada de las eras del verano,
y no quedará rastro del lugar de su reunión.`" Durante ese tiempo, todos los disidentes,
excepto los Amigos, habían dejado de reunirse.

Continué hablando con los hombres y les dije: "`El asalariado huye, porque es asalariado,
y no le importan las ovejas;`" refiriéndome al pasaje de Juan 10: 11-13. Además,
les mostré cuán bienaventurados son los que llegan al conocimiento de ese Maestro,
que no les será quitado.
Dios dijo que Él mismo enseñaría a Sus hijos,
y que los hijos del Señor son enseñados por el Señor.^
footnote:[Ver Juan 6:45, e Isaías 54:13]
Además, les indiqué que ellos podían leer en la primera epístola de Juan 2:27,
donde dice: "`Pero la unción que vosotros recibisteis de él permanece en vosotros,
y no tenéis necesidad de que nadie os enseñe;
así como la unción misma os enseña todas las cosas,`" etc.
De igual manera en Tito 2:11-12:
"`Porque la gracia de Dios que trae salvación se ha manifestado a todos los hombres,
enseñándonos.`"
De esta manera me esforcé por llevarlos de sus maestros asalariados
a la enseñanza de Dios y de Cristo en ellos mismos,
mediante la cual podían llegar al conocimiento de Dios,
y caminar en los caminos de Su salvación;
porque "`a cada uno le es dada la manifestación del Espíritu para provecho.`"^
footnote:[1 Corintios 12:7]
Les aconsejé volver sus mentes hacia el interior,
y prestar atención a su operación secreta, mediante la que hallarían,
por medio de una experiencia viva, que refrena y reprueba las malas palabras y acciones;
y que, al volverse a ella, hallarían que los guía a toda verdad;
junto con muchas más palabras para este efecto.
Ellos quedaron muy satisfechos con este discurso, y mientras partían,
declararon que jamás en sus vidas habían oído estas cosas expuestas con tanta claridad.

=== La Mejor Ancla para un Marinero

Tomado del Diario de Thomas Chalkley

Al cabo de unos meses, le dije a mi esposa, a mi padre y a los padres de ella,
que consideraba mi deber cruzar el océano e ir a vivir a América.
Mi padre estuvo de acuerdo, aunque con ternura de corazón,
al considerar que iba a estar muy lejos de él. También lo
expuse en la reunión mensual de los Amigos en Horslydown,
de la cual yo era miembro, y ellos consintieron,
aunque con algo de pesar por tener que separarse de nosotros.
Nos dieron su certificado para hacer saber a nuestros
hermanos que estábamos en amor y unidad con ellos,
y que caminábamos fieles a nuestra profesión. Cuando estuvimos en condiciones de partir,
acordamos el transporte de nuestros bienes y sirvientes
en una embarcación con destino a Maryland.
Cuando el barco llegó a Gravesend y estábamos listos para partir,
varios de nuestros queridos amigos y familiares nos acompañaron hasta el barco,
a bordo del cual tuvimos una buena reunión. Nos despedimos
solemnemente unos de los otros,
como si no esperáramos vernos más en este mundo.
¡Fue verdaderamente un tiempo solemne!
Oramos los unos por los otros, y luego nos despedimos.
Nuestro barco zarpó esa misma tarde y llegamos a Margate Road, donde anclamos.
El viento se levantó con mucha fuerza y sopló tempestuosamente,
de modo que rompió nuestro cable y perdimos nuestra mejor ancla de proa,
siendo arrastrados violentamente hacia las arenas de Goodwin.
Soltamos nuestra ancla de emergencia y otras tres más, que era todo lo que teníamos,
pero no lograban detener la nave;
ante lo cual el capitán le ordenó a los carpinteros que
se colocaran junto al mástil mayor con sus hachas al hombro,
listos para cortarlo cuando él diera la orden.

Las personas a bordo del barco (pues habían muchos pasajeros) estaban bastante angustiadas,
esperando sólo la muerte.
Uno de los pasajeros llegó llorando y dijo que nuestra situación era crítica.
El doctor también llegó, del mismo modo, diciendo: "`¡Oh señor Chalkley,
somos hombres muertos!`"
Entonces pensé en mis adentros en subir a la cubierta
para ver de qué se trataba el asunto,
y estando en la cubierta me dirigí donde el capitán, que tenía la sonda en la mano,
y tras sondear exclamó: "`¡Señor, ten misericordia de nosotros! ¡Perdimos el barco,
lo perdimos, lo perdimos!`"
Fue entonces cuando comprendí que estábamos muy cerca de las arenas de Goodwin,
donde muchos barcos se han perdido con toda su tripulación.

Bajo esta conciencia de peligro, mandé a llamar a todos los pasajeros a la cabina,
y les dije que pensaba que sería bueno que nos sentáramos quietos, todos juntos,
mirando a Dios y esperando en Él, para ver qué era lo que Él quería hacer por nosotros;
y que si llegaba la muerte, la recibiéramos en el mejor estado de ánimo posible,
para no ser sorprendidos en gran manera.
Y mientras estábamos así, calmados en nuestras mentes,
una inquietud se apoderó de mi querida esposa, quien oró a Dios el Padre,
en el poder y sentido vivo de Su Hijo, y Él oyó desde Su santa morada,
y respondió a su oración,
pues inmediatamente después el viento disminuyó y nuestras anclas nos sostuvieron.

Esta fue una gran liberación que no puede ser olvidada.
Cuando al fin vimos la tan ansiada mañana, estábamos muy cerca de los bancos de arena,
y el mar se alzaba prodigiosamente rompiendo sobre ellos con gran fuerza,
de modo que nos vimos obligados a dejar nuestros cables y anclas,
y dirigirnos a Deal lo mejor que pudimos.

=== Confianza en la Providencia

Del mismo Autor

Tras haber terminado mis asuntos en Inglaterra,
me embarqué en la goleta Dove rumbo a Filadelfia,
pues me había sido asignada tanto en este viaje como en el anterior.
Como el viento estaba calmado y era escaso, nuestras provisiones empezaron a escasear.
Éramos unas doce personas en la embarcación,
y sólo nos quedaba un trozo de carne en el barril.
Por varios días, los vientos soplaron en dirección contraria,
haciendo que las personas empezara a murmurar y a contar historias funestas de gente que,
por falta de provisiones, llegaron a comerse unos a otros.
Como el viento seguía en contra nuestra, continuaron murmurando más y más,
hasta que finalmente lo hicieron contra mí,
ya que la embarcación y la carga estaban bajo mi cuidado;
de modo que mi ejercicio interno era grande por causa de ello.
Pues ni yo ni ninguno en el barco habíamos imaginado
que el viaje se prolongaría el doble de lo previsto.
Pero como fue así, consideré con seriedad el asunto,
y con el fin de frenar sus murmuraciones,
les dije que no sería necesario echar suertes (que era lo esperado
en tales casos) para saber quién de nosotros moriría primero,
pues yo estaba dispuesto a ofrecer libremente mi vida por el bien de ellos.
Entonces uno dijo: "`Dios te bendiga, pero yo no me comeré ninguna parte de ti.`"
Otro dijo que prefería morir antes de comerme; y así dijeron los demás.

Puedo decir con verdad que, en ese momento, no estimaba mi vida,
y que mi propuesta era seria y sincera.
Mientras me apoyaba sobre la borda del barco,
considerando cuidadosamente la propuesta hecha a la tripulación,
y volviendo mi mente hacia Aquel que me creó,
un gran delfín subió a la superficie del agua, y me miró a la cara.
Llamé a los demás para que lanzaran un anzuelo al mar y lo atraparan: "`Porque,
he aquí uno que viene a redimirme,`" les dije.
Ellos arrojaron el anzuelo al mar y el pez lo tomó en seguida, y lo pescaron.
El delfín era más largo que yo; creo que medía alrededor de dos metros,
el más largo que haya visto jamás.

Esto nos mostró claramente, que no debemos desconfiar de la providencia del Todopoderoso.
Las personas se calmaron tras ese acto de la Providencia y dejaron de murmurar.
Pescamos lo suficiente como para comer en abundancia
hasta que llegamos a los Cabos de Delaware.
De ese modo vi que era bueno depender del Todopoderoso y confiar en Su eterno brazo,
el cual, nos preservó de manera particular hasta llegar hasta nuestro puerto deseado.
¡Bendito sea Su grande y glorioso nombre por Cristo para siempre!

=== Richard Davies

Cuando Richard Davies viajaba a Pembrokeshire por motivos religiosos,
junto con su compañero Thomas Ellis, convocaron una reunión en Newcastle,
en Carmarthenshire,
y algunos amigos los acompañaron hasta ahí. Varios magistrados
del lugar asistieron a la reunión y se comportaron muy corteses.
Richard Davies dice:

El peso y el deber de la reunión recayeron especialmente sobre mí, pues,
aunque nuestro amigo Thomas Ellis había sido reconocido como diácono,
y como un predicador eminente entre los Independientes,
su boca apenas se había abierto en testimonio entre los Amigos.
Él era un hombre entendido en las cosas de Dios,
y no se apresuraba a ofrecer una ofrenda hasta llegar a sentir un mayor
peso sobre él. Mientras yo declaraba al pueblo en lengua galesa,
estaba de pie frente a una gran ventana que daba a la calle,
y allí estaba un hombre de mente malvada, que tenía una gran escopeta.
Metió el cañón del arma a través de la ventana, y juró que si yo decía una palabra más,
sería hombre muerto.
Pero, alabado sea Dios, fui guardado en Aquello que está por encima del temor del hombre,
y el Señor me sostuvo en dominio sobre todo.
Sólo había dos mujeres sentadas en la ventana, y el cañón del arma pasó entre ambas.
Una de ellas puso su espalda frente al cañón y dijo en galés,
cuando el hombre repitió la amenaza: "`Primero moriré yo.`"
Uno en la reunión se acercó al hombre, le quitó el arma,
y ese hombre malvado entró a la reunión y se quedó en silencio.
La buena presencia del Señor estuvo con nosotros, tuvimos una buena reunión,
y puedo decir: "`Los que confían en Jehová son como el monte de Sion, que no se mueve.`"^
footnote:[Salmo 125:1]
Tal como fue dicho en el pasado: "`Como Jerusalén tiene montes alrededor de ella,
así Jehová está alrededor de su pueblo,`" para ser
el pronto auxilio en todo momento de necesidad.

=== El Coronel de la Caballería Montada

Durante la guerra de independencia de los Estados Unidos,
una parte del ejército estadounidense acampó cerca
de la casa de reunión en Gunpowder Falls,
lo cual, no obstante,
no impidió que los Amigos llevaran a cabo las reuniones
de adoración. Entre estas tropas había un coronel de caballería,
cuya ira contra los Amigos alcanzó tal grado, que un día, mientras recorría la zona,
se le ocurrió la más absurda y cruel resolución,
de matar a filo de espada a los Amigos que estaban
reunidos entonces en el lugar de adoración;
considerándolos nada mejor que un grupo de traidores.
Llevando a sus hombres cerca del lugar,
les ordenó detenerse con el fin de planear la ejecución de su terrible objetivo.
En ese momento, se produjo una pausa aterradora y silenciosa,
en la que sintió su mente tan poderosamente golpeada con una convicción,
que no sólo le hizo retirar su tropa,
sino que empezó a concebir sentimientos muy favorables hacia a la Sociedad.
Y al continuar cediendo a esas convicciones,
más adelante se unió en comunión con los Amigos,
y permaneció fiel al principio de la Verdad profesada por ellos.

Los viajes de Sutcliff

=== Extracto de una Carta de Anthony Benezet a John Pemberton

Es asombroso ver cuánta influencia el amor al mundo, su estima y amistad,
y el deseo de acumular riquezas, han tenido sobre muchos en nuestra Sociedad,
donde vemos a muchos (junto con sus hijos) viviendo con delicadeza y ostentación,
y en conformidad con el mundo, quienes, en otros aspectos,
parecen vivir bajo algunas impresiones de bien.
No obstante,
no pueden dejar de ser conscientes de los lamentables
efectos sobre el bienestar religioso de sus hijos,
quienes, por ello, como menciona el apóstol, caen en las trampas y deseos perjudiciales,
muchas veces para su perdición;
a pesar también de que la naturaleza de nuestra profesión,
y la conformación al ejemplo y preceptos de nuestro Señor,
establecen una prohibición rotunda sobre tal condición.

"`No os hagáis tesoros en la tierra,`" dice nuestro bendito Salvador.
"`¡Cuán difícilmente entrarán en el reino de Dios los que tienen riquezas!,`" etc.
"`¡Ay de vosotros,
ricos!`" "`No os conforméis...mas transformaos,`" para que estén mejor
preparados para seguir a Aquel que los ha llamado al camino de la Cruz,
para ser soldados en Su santa milicia.
Aprendan de Aquel que es manso y humilde; que, siendo Señor de todo,
eligió tomar la forma de siervo, caminó a pie, se alimentó de panes de cebada, etc.
Algunos mandatos, menos propensos a influir en el corazón,
los recibimos con toda la fuerza de sus expresiones,
como en el caso de no hacer juramentos, etc.
Mientras que otros, cuya naturaleza dañina es más evidente,
y que han sido prohibidos con igual empeño por nuestro
Salvador (como acumular tesoros,) no les damos importancia.
Una circunstancia que ocurrió no hace mucho tiempo,
me hizo hacer algunas reflexiones dolorosas sobre este tema tan importante.

Un Amigo murió,
y se dice que dejó sesenta o setenta mil libras a un número de hijos y nietos,
quienes ya estaban tan enaltecidos por la fortuna que poseían,
que parecían listos para alzar el vuelo por encima
de la Verdad en conformidad con el mundo,
sus amistades, modas, etc.
Esto sucedió en pleno invierno,
en uno de esos días de frío intenso que todos hemos experimentado como muy duros,
incluso para quienes están mejor provistos de combustible, ropa adecuada, etc.
Mientras caminaba, observé a ancianos y a otras personas tambaleándose por las calles,
o de pie en el frío, en busca de unos cuantos peniques apenas para subsistir;
muchos de ellos, sin duda, con pocas provisiones de combustible o de mantas,
cobijas o colchones, artículos entonces sumamente escasos y costosos.

Comparé la situación y la necesidad de estas personas mayores con la riqueza
superflua y la vida refinada de los hijos del hombre rico recientemente fallecido,
y no pude evitar asombrarme del egoísmo y capricho del corazón humano.
Me pregunté: ¿Son ambos hijos del mismo Padre, igualmente bajo su cuidado?
¿Acaso no se les ordena, y de hecho profesan,
amarse los unos a los otros como se aman a sí mismos?
¿Por qué no destinan al menos tres cuartas partes de esa riqueza,
y tres cuartas partes de la riqueza de otros cuáqueros ricos,
para procurar un lugar de refugio y bienestar,
y provisión moderada para tales personas débiles y mayores?
Para que, en los últimos días de sus vidas,
puedan hallarse en una situación más adecuada para pensar en su fin y prepararse para él,
y disfrutar de un estado moderado de comodidad.

¿Vivir así es honesto ante Dios y ante los hombres?
¿Es hacer justicia como mayordomos de la riqueza que se nos ha encomendado?
¿Es amar a nuestro prójimo como a nosotros mismos?
Si los seres humanos son verdaderamente nuestros hermanos,
¿aprobará el buen Padre de familia que uno acapare tanto
y lo utilice para alimentar las corrupciones de su descendencia;
mientras que otros se hallan en gran desventaja por falta de ayuda?

La carta antes citada no puede considerarse propiamente una anécdota,
aunque la circunstancia que se expone en ella parece haber sido la causa
de esas consideraciones que forman la mayor parte de ella.

El notable individuo que la escribió, no era un filántropo teórico ni ostentoso,
sino un cristiano en el sentido más fiel de la palabra.
Él había aprendido (no en la escuela de la tradición o conformidad al mundo),
a rendir sus talentos, tiempo y bienes al servicio de sus semejantes,
y ello por amor a Cristo.
En una reseña biográfica publicada sobre él,
se describen algunos rasgos poco comunes de benevolencia.
Se sabe incluso que llegó a quitarse su propio abrigo en las calles,
para dárselo a otro que tenía gran necesidad de vestido.
Pero su provechosa vida y esfuerzos, en toda ocasión,
parecen reflejar un corazón bajo la influencia,
freno y dirección del mejor de los principios, es decir,
la voluntad de Dios dada a conocer por el Espíritu de Su Hijo.

=== Una Vejez Tranquila y Provechosa

Tomado del Diario de Thomas Chalkley

En Virginia, cerca del río James, conocí a un anciano Amigo llamado William Porter.
Él tenía noventa y dos años,
y en ese entonces tenía una hija de dos años. Unos años después, lo volví a ver,
y estaba desyerbando maíz indio con una azada.
Entonces tenía alrededor de ciento seis años, y más de setenta hijos, nietos y bisnietos.
Varios Amigos y yo fuimos a verlo, y nos predicó un sermón muy corto pero conmovedor,
que, según recuerdo, decía casi textualmente de la siguiente manera: "`Amigos,
ustedes han venido a verme en el amor de Dios.
Dios es amor y los que permanecen en Dios permanecen en amor.
Doy gracias a Dios porque siento Su divina vida cada día y cada noche.`"
Vivió para ver casada a su hija antes mencionada; y murió a la edad de ciento siete años.

=== William Penn y la Niña Descalza

Mientras William Penn vivía en Pennsylvania,
emprendió un viaje por la provincia y territorios como ministro del evangelio.
Entre los lugares que visitó bajo este cargo estaba Haverford;
y se cuenta una anécdota que le sucedió en su camino ahí, que es digna de relatar.

Una Amiga llamada Rebecca Wood,
acostumbraba de niña a caminar desde Derby (donde vivía) hasta la reunión de Haverford.
Un día, mientras iba por el camino, fue alcanzada por un Amigo que iba a caballo,
y que resultó ser William Penn.
Al acercarse a ella, le preguntó hacia dónde se dirigía,
y con su característico buen carácter, le pidió que se montara detrás de él,
y llevando su caballo a un lugar más conveniente, ella se subió y se fueron juntos.
Como no llevaba zapatos ni medias,
sus piernas y pies desnudos colgaban al costado del caballo del gobernador.

Aunque durante esa época William Penn era tanto gobernador como propietario,
no consideró indigno de su parte ayudar a una pobre niña descalza en su
camino a la reunión. A pesar de las reglas y costumbres del mundo,
estos pequeños actos de bondad hacia personas de un estrato social más bajo,
estaban tan lejos de rebajarlo ante los ojos de los que gobernaba, que,
quizás no haya habido nunca un gobernador que gozara de
mayor estima por parte de los gobernados que William Penn.

Los Viajes de Sutcliff

=== John Woolman y el Petirrojo

Algo que marcó mi infancia me sucedió yendo a casa de un vecino,
cuando vi en el camino a un petirrojo sentado en su nido.
Al acercarme, ella se alejó, pero como tenía polluelos,
volaba cerca del lugar y con muchos chillidos manifestaba su preocupación por ellos.
Me quedé allí y le tiré piedras, hasta que una la alcanzó y cayó muerta.
Al principio me agradó la hazaña, pero al cabo de unos minutos me sobrecogió el horror,
pues, por diversión,
había matado a una criatura inocente que cuidaba de sus
crías. Me quedé contemplándola tendida en el suelo,
y pensé que esas crías, a las que ella había cuidado tanto,
ahora morirían pues no tenían una madre que las alimentara.
Después de unas dolorosas consideraciones sobre el asunto, trepé al árbol,
tomé los pajaritos y los maté,
creyendo que eso era mejor que dejarlos desfallecer y morir miserablemente;
y creí que en este caso se cumplía aquel proverbio de las Escrituras que dice:
"`Las misericordias de los impíos son crueles.`"^
footnote:[Proverbios 12:10 RVG]
Luego continué con mi encargo,
pero por varias horas no pude dejar de pensar en las crueldades que había cometido,
y estaba muy afligido.
Así, Aquel cuyas misericordias están sobre todas Sus obras,
ha colocado un principio en la mente humana que impulsa
a obrar en bondad hacia todo ser viviente;
y al ser atendido de manera íntegra, la persona se vuelve tierna de corazón y compasiva;
pero al ser rechazado con frecuencia y por completo,
la mente se cierra en una disposición contraria.

Este pequeño suceso, registrado en la vida de John Woolman,
bien puede verse reflejado en la experiencia de muchos jóvenes lectores, quienes,
en una irresponsable travesura juvenil,
pueden haber actuado de manera similar en varias ocasiones.
Para estos, el lenguaje de una suave exhortación puede no ser tan efectivo,
como el sencillo tono de este extracto aleccionador, que, se cree,
no fallará en alcanzar el corazón sensible y despertar la
susceptibilidad en las conciencias de la mayoría. Cabe destacar,
como algo notable, que este jovencito,
quien a una temprana edad había manifestado la fuerza y el crecimiento del árbol corrupto,
al permitir que el hacha del juicio y la reprensión divinos fuera puesta a la raíz,
pronto se convirtió, por el predominio del poder ablandador de la Verdad,
en un eminente ejemplo y defensor de la benevolencia cristiana hacia toda la raza humana,
así como de la ternura en el trato hacia la creación animal.
A menudo, en el amor puro de Dios,
abogaba ante los que oprimían tanto al hombre como a la bestia,
y mediante la elocuencia persuasiva de su conducta,
testificaba que su espíritu estaba unido al Padre
de los espíritus y Preservador de toda carne.

=== Thomas Chalkley y Las Cartas

Yo amaba la música, bailar y jugar a las cartas,
y era perseguido por los juicios de Dios en lo secreto de mi alma, debido a ello.

Recuerdo que, sin que mis padres se dieran cuenta, había comprado una baraja de cartas,
con la intención de usarla cuando fuera a visitar a mis parientes en el campo,
donde había libertad en la familia para hacerlo, en un lugar llamado Woodford,
adonde a veces me permitían ir.
Fui a verlos durante la época llamada Navidad y, de camino,
asistí a una reunión en Wanstead,
en la que un ministro de Cristo declaró contra el mal del juego,
particularmente contra el uso de las cartas,
y que el tiempo que la gente pretendía guardar santo por causa de Cristo,
muchos lo gastaban principalmente en maldad, deportes y juegos;
que incluso algunos aparentaban ser religiosos; y que, en general,
se cometía más pecado y maldad durante ese tiempo, que en cualquier otra época del año;
de modo que se servía al diablo en lugar de honrar a Cristo.

De esta reunión fui a la casa de mis parientes,
donde el párroco de la parroquia cercana iba a pasar la noche.
Él solía jugar a las cartas con ellos en ocasiones.
Al acercarse el momento en que debíamos comenzar a jugar,
mi tío llamó al doctor (como lo llamaba), a mí y a mi primo,
para que fuéramos a jugar una partida de cartas.
Ante esta invitación, sentí fuertes convicciones de no aceptarla, pues era mala;
y en secreto clamé al Señor para que me guardara fiel a Él. Alzando mis ojos,
vi una Biblia en la ventana, y me alegré al verla.
La tomé, me senté y leí para mí,
regocijándome grandemente de haber sido preservado de la trampa.
Luego, mi tío llamó de nuevo, y le dijo al párroco: "`Ven doctor,
pues veo que mi sobrino tiene mejores cosas que hacer.`"
Entonces me miró a mí y dijo que él también tenía mejores cosas que hacer.
De este modo, su diversión quedó arruinada por ese momento,
y la mía en esa práctica se descartó para siempre,
porque nunca más (que recuerde) volví a jugar a las cartas, y tan pronto regresé a casa,
tiré al fuego mi paquete de cartas nuevo e intacto.
De esto estoy seguro, el uso de las cartas acarrea malas consecuencias,
y desvía la mente del cielo y de las cosas celestiales; por esta razón,
todos los cristianos deben evitarlas como instrumentos de Satanás.
Y como bailar con música generalmente tiende al mismo fin,
también debe ser rechazado.

=== El Instrumento de Dios

James Wilson estaba en una reunión en Londres junto con Thomas Wilson,
donde había una gran concurrencia de personas, y entre ellas dos de alto rango social,
que se sentaron muy atentas mientras un Amigo hablaba,
y parecía que les gustaba lo que se decía. Pero cuando
Thomas se levantó--siendo un anciano,
calvo y de apariencia humilde--lo menospreciaron, y uno de ellos le dijo al otro: "`Ven,
mi señor, vámonos, ¿qué puede decir este anciano tonto?`"
"`No,`" dijo el otro, "`quedémonos, pues este es el profeta Jeremías, escuchémoslo.`"
Entonces, a medida que Thomas hablaba, la vida se levantó y el poder tomó el dominio,
lo cual enterneció a uno de ellos de una manera extraordinaria.
Las lágrimas brotaban abundantemente de sus ojos, y en vano luchó por ocultarlas.
Después de que Thomas se sentó,
aquel hombre se levantó y manifestó el deseo de ser perdonado por Thomas y por el Todopoderoso
por haber despreciado uno de los más grandes de Sus instrumentos bajo el cielo,
o en Su creación.

El Diario de Samuel Neale.

=== Exhortación Para Buscar al Señor Desde Temprano

La temprana experiencia de aquellos que han brillado como estrellas fijas
en el glorioso firmamento del poder invisible de Dios--quienes se han
mantenido firmes en la fuerza y constancia de aquella santa fe,
que Él se complace en comunicar mediante los brotes de Su amor, gracia,
misericordia y verdad en sus almas--siempre resultará preciosa
y aceptable para los espíritus de aquellos que,
en alguna medida, han sido partícipes de la misma esperanza celestial.

Algunos detalles acerca del convencimiento de Thomas Thompson de Skipsea, en Yorkshire,
se han considerado dignos de tener un lugar en estas páginas.

El lector podrá notar que, en inserciones biográficas como estas,
se da preferencia al incidente y al hecho antes que a los ejercicios mentales,
conflictos o experiencias espirituales,
pues corresponde más al diseño y al título de esta obra.
No obstante, puede obtenerse profunda enseñanza de la mayoría de los relatos,
y a menudo se pueden levantar reflexiones al recordarlos,
que también pueden servir de guías para el sabio y recto de corazón,
especialmente entre los jóvenes.
Si se examina con seriedad y sinceridad,
incluso por aquellos que no pertenecen a la misma profesión religiosa,
un breve testimonio como el de Thomas Thompson puede resultar
de gran interés. Porque a través de narrativas como esta,
uno puede llegar a conocer, en cierta medida,
la eficacia de esa influencia secreta (que no es de nosotros,
pero está en nosotros) por la cual todos los hombres
deberían ser guiados tanto en corazón como en conducta,
y sin la cual toda religión no es más que un nombre vacío.

Con respecto a este digno hombre de Dios--su carácter,
servicios y sufrimientos por causa de la consciencia--se puede decir mucho.
Baste decir que vivió hasta los 73 años, y que así como vivió, murió,
en la plena y completa posesión de esa paz, seguridad y gozo en el Señor Dios de su vida,
que es la porción de Sus fieles hijos, los seguidores de Jesucristo.

Cuando era joven, le plació al Señor inclinar mi corazón a buscarle;
y cuando tenía alrededor de ocho años, Su palabra resonó en mí, diciendo:
"`El hacha está puesta a la raíz de los árboles; por tanto,
todo árbol que no da buen fruto es cortado y echado en el fuego.`"
Entonces,
fueron engendrados en mí deseos de ser hallado como
uno de aquellos árboles que dan buen fruto.
Asimismo, el Señor me reveló muchas cosas que eran malas,
generalmente practicadas por personas como yo en ese entonces, como jurar,
mentir y hablar de una manera profana.
No solo me reveló que eran malas, sino que, mediante Su misericordia,
levantó en mi corazón una repulsión y aborrecimiento hacia ellas.
En la medida que me mantuve fiel a ese principio que manifestaba
que tales cosas eran contrarias a la voluntad de Dios,
fui preservado del mal,
aunque aún no sabía que era el Señor quien estaba tan cerca de mí y luchando conmigo.

Luego empecé a ir a escuchar con frecuencia sermones y a seguir
a los predicadores que eran considerados como los más conscientes
y capaces de la región donde yo vivía. Yo anhelaba tener una Biblia,
pues nunca había tenido una para leer, y cuando mis padres lo supieron,
rápidamente me consiguieron una.
Cuando comencé a leerla,
fui profundamente afectado por el relato de cómo Dios hablaba con su pueblo--con Noé,
Abraham, Isaac, Jacob,
etc.--y consideraba bienaventurados a aquellos que tenían tal familiaridad con Dios;
sin comprender que Él todavía era un Dios "`cercano
y no lejano`" para todos los que en verdad lo buscan.
Durante muchos años me esforcé con fervor por alcanzar entendimiento,
pero mi mente estaba enfocada hacia lo externo,
pues no conocía la luz de Cristo como mi guía,
con la que Él ha alumbrado a todos los hombres.
Buscaba a los ministros que eran considerados los más capaces y piadosos,
y también amaba la compañía de los más piadosos,
sabios y profesantes que me era posible conocer,
y me deleitaba conversando de las cosas de Dios.

Pero, ¡ay!--a medida que crecía y aumentaba en conocimiento,
mi corazón ya no se mantenía tan cerca del Señor como antes,
ni mis deseos hacia Dios eran tan fervientes,
ni tan grande mi cuidado de caminar en santidad de vida delante de Él,
para dar así frutos para Su alabanza.
Porque comencé a caer en un falso reposo, creyendo que todo estaba bien conmigo,
ya que conocía las Escrituras y podía repetir mucho de los sermones y
la exposición de los capítulos que los sacerdotes utilizaban entonces.
Además, los sacerdotes me hablaban con palabras lisonjeras,
intentando recubrirme con lodo suelto,^
footnote:[Ezekiel 13:10]
diciendo que yo era un muchacho prometedor y que
no debía dudar de que todo iría bien conmigo, etc.
Sin embargo, el Señor en Su infinito amor y tierna compasión hacia mi alma,
volvió a levantar Su testigo en mi corazón,
permitiéndome ver que mi alma aún carecía de algo, y que no todo estaba bien conmigo,
aunque entonces podía hablar mucho de Dios, de Cristo y la fe.

Entonces, gracias a la misericordia,
se engendraron nuevamente en mí algunos deseos hacia el Señor;
y mi alma no hallaba satisfacción en lo que oía de los sacerdotes,
aunque iba de uno a otro, como de monte a collado, buscando reposo,
pero sin hallarlo para mi alma cansada,
que seguía sin encontrar satisfacción y tenía hambre del Pan de vida.^
footnote:[Juan 6:33]
Luego asistí a algunas reuniones del pueblo llamado independientes;
pero tampoco allí pude encontrar lo que le faltaba a mi alma, a saber, la vida de Jesús,
sin cuyo disfrute yo no podía estar satisfecho.
Así que, cansado de ir de un lugar a otro,
al poco tiempo los dejé y comencé a retirarme en mi mente, deleitándome en estar solo,
meditando en las cosas de Dios o leyendo los libros que exponían las experiencias
de aquellos que habían tenido alguna claridad del camino de vida.

En la primera parte del año 1652,^
footnote:[Thomas Thompson, teniendo entonces unos 21 años.]
le plació al Señor enviar a Su fiel y valiente siervo y mensajero, el querido George Fox,
a estas regiones; pero no tuve entonces la oportunidad de verlo, aunque lo deseaba mucho.
Sin embargo, alguno de mis familiares que estuvieron con él,
me contaron de su manera de vivir, y también de su doctrina.
Me dijeron que en su comportamiento era muy reservado,
que no usaba palabras innecesarias ni sostenía conversaciones
que no condujeran a la edificación,
que no hacía acepción de personas, que era muy moderado en su comida y bebida,
y que su vestimenta aunque sencilla, era modesta.
En cuanto a su doctrina,
que dirigía a las personas a la luz de Cristo en sus conciencias, para guiarlos a Dios.
Al escuchar estas cosas, aunque por boca de otros,
agradó al Señor obrar de manera poderosa en mi espíritu,
llevándome a un maravilloso estado de retiro,
y mi mente fue verdaderamente vuelta hacia el interior,
para esperar en Él y desear Sus enseñanzas.

De este modo, poco a poco, el Señor fue manifestando una cosa tras otra,
hasta que fui destetado de mis antiguos amores; y mediante la obra y el poder de Dios,
el yo fue negado, y en muchas cosas fui humillado hasta la cruz;
de modo que varios de mis vecinos y familiares se maravillaban al verme tan cambiado,
y algunos decían que yo estaba fuera de mis cabales.
Pero sus palabras me importaban poco;
porque mientras obedecía al Señor hallaba paz y satisfacción,
y el regreso del amor de Dios a mi seno, que por tanto tiempo había estado buscando.
En la medida que rendía algo por causa de la Verdad, encontraba paz,
y se me daba más fuerzas; así que puedo decir con verdad:
Es bueno mantenerse en el consejo de Dios y rendirse por completo para servirle,
porque Él es bueno para con los que confían en Él,
y los que le sirven fielmente no perderán su recompensa.

Sucedió entonces que, alrededor del sexto o séptimo mes del año 1652,
oímos hablar de un pueblo que se había levantado en o por los alrededores de Malton,
al que llamaban Cuáqueros;
fue la primera vez que oí que se le daba ese nombre a un pueblo.
La mayoría de la gente hablaba mal de ellos;
pero cuando pregunté exactamente de qué se les acusaba
que justificara levantar tales calumnias,
no encontré a nadie que pudiera acusarlos con justicia de algo malo.
Sólo decían que era un pueblo fantasioso y arrogante, y que quemaban sus encajes,
lazos y otras cosas superficiales que solían usar,
y que caían en extraños episodios de estremecimientos y temblores.

Estos informes incrementaron mis deseos de verlos y conocerlos;
y en el octavo mes del mismo año, escuché que los Cuáqueros iban a llegar a Bridlington,
por lo que me alegré mucho en mi espíritu, esperando tener una oportunidad de verlos.
Al quinto día siguiente,
escuché que habían llegado a Frodingham--se trataba de William Dewsbury,
fiel obrero y ministro del evangelio.
Como yo estaba empleado en el trabajo de mi amo en Brigham, no pude ir durante el día,
de modo que me propuse ir de noche.
Me hubiera gustado ir con algunos de mis conocidos, pero como la noche era muy oscura,
nadie quiso acompañarme, y entonces me fui solo.
Al entrar en la sala donde estaba William, lo hallé escribiendo,
y el resto de las personas que lo acompañaban estaban sentadas en profundo silencio,
pareciendo estar muy retirados en sus mentes, vueltos a Dios;
sus semblantes eran serios y firmes, lo cual me predicó,
y confirmó lo que había creído antes, que ellos eran el pueblo del Señor.

Después de un corto tiempo, William dejó de escribir,
y como mucha gente del pueblo comenzó a entrar,
comenzó a declarar la Verdad en el poder y sabiduría de Dios.
Y ¡ah, cuán refrescada fue mi alma,
y cómo fue alcanzado el testigo de Dios en mi corazón! No lo puedo expresar con mi pluma.
Nunca antes había escuchado ni sentido algo similar,
porque hablaba como alguien que tiene autoridad, y no como los escribas; de modo que,
aunque todo el mundo lo hubiera negado,
yo habría testificado que se trataba de la eterna Verdad de Dios.
Y en ese mismo mes,
mi boca fue vívidamente abierta para declarar el nombre
del Señor y predicar el arrepentimiento a la gente;
y la obra del Señor prosperaba en las manos de sus fieles siervos;
y experimenté un freno para mi lengua,
y tuve mucho temor de ofenderlo a Él en pensamiento, palabra u obra.
La palabra del Señor estaba en mí: "`No harás tus propias obras,
ni pensarás tus propios pensamientos,
ni hablarás tus propias palabras en mi día santo.`"^
footnote:[Isaías 58:13]
Aunque padecí y atravesé muchos grandes ejercicios,
el Señor sustentó mi espíritu y me llevó adelante, mientras me mantuve fiel a Él,
para alabanza de Su propio nombre.

La Vida de Thomas Thomson

=== George Whitehead

George Whitehead, (de quien ya se ha hecho alguna mención,
y de quien puede decirse con propiedad y certeza que era
un siervo muy digno de la iglesia) relata que,
estando en una reunión del pueblo llamado Cuáqueros
(la primera reunión de ellos a la que asistía),
cuando tenía unos dieciséis años,
prestó especial atención al gran poder y obra del
Señor que cubría y estaba sobre la asamblea,
quebrantando los corazones de muchos en gran aflicción, lloro y contrición.

Una joven en particular salió muy afligida de la reunión,
a la que él siguió con mucha seriedad y preocupación para observar su triste estado.
Y al verla sentada en el suelo,
con la cabeza inclinada y el rostro vuelto hacia la tierra (sin considerar a nadie más),
y al oír cómo lloraba amargamente, diciendo: "`¡Señor, límpiame! ¡Oh Señor, límpiame!`",
su alma--declara George--fue afectada más profundamente
que por todo lo que había oído en la reunión,
y mucho más que por todas las predicaciones que jamás había oído de un hombre.
Él creyó que se trataba de la "`tristeza que es según Dios`" por el pecado cometido,
y que produce arrepentimiento no fingido.
Esta verdadera obra del poder y Espíritu de Dios sobre el
corazón de ella operaba también en el corazón de otros,
haciendo que incluso sus cuerpos temblaran ante la presencia
del Señor y Su llamado al interior de sus almas.

Estas cosas causaron una profunda y seria impresión en la mente de George Whitehead,
e hicieron que se sintiera seguro de que el Señor estaba obrando
en medio de ese pequeño y despreciado pueblo de modo peculiar,
y de que Él estaba por reunirlos y levantarlos para que fueran un pueblo para Sí Mismo,
para manifestar en ese día la naturaleza espiritual de la adoración del evangelio,
la cual en los tiempos primitivos de la iglesia no
se había establecido en esas formas muertas,
que fueron ideadas después por la sabiduría del hombre.

Cabe mencionar además que George Whitehead,
después de que fue completamente convencido y persuadido de volver
su atención a aquello que mostraba su condición interna,
tuvo un encuentro con George Fox en una reunión. "`Me hallaba entonces,`" afirma,
"`muy bajo, serio, con la mente inclinada, dispuesto a ver y a gustar por mí mismo,
para mi propia satisfacción interna.
Vi y sentí que su testimonio era de peso y profundidad,
y que procedía de la vida y la experiencia, que daba evidencia de revelación divina,
y tendía a llevar a un sentimiento y conciencia internos de la vida y el poder de Cristo,
y de su obra santificadora en el corazón. Su hablar
no fue acompañado de elocuencia estudiada,
oratoria o humana sabiduría, sino en la sencillez del evangelio,
para dirigir las mentes a la luz y la vida de Cristo.`"

En aquel día en que la luz y la verdad brotaban de la oscuridad,
las reuniones de aquellos que habían sido reunidos en la adoración pura se celebraban,
como declara el mismo escritor,
"`a menudo y con frecuencia en silencio,`" o con
solo pocas palabras pronunciadas entre ellos;
pues las mentes de los presentes estaban centradas y fijas en la divina Palabra de Vida,
ejercitadas en gran manera delante del Señor,
esperando los tiempos de refrigerio que vienen de la presencia del Señor.^
footnote:[Hechos 3:19]
Así, a Su manera, en Su fuerza y en Su tiempo,
fueron eficazmente capacitados para despojarse del cuerpo de pecado,
y llegar a ser verdaderamente renovados en el espíritu de sus mentes.
De modo que, de entre ellos,
le plació al Señor engendrar una generación de verdaderos testigos--ministros
aptos de Aquello que moraba abundantemente en ellos,
y que era como "`ríos de agua viva.`"^
footnote:[Juan 7:38]

=== Realidades que Infunden Temor Reverente

Aunque podría decirse que nada o poco de lo insertado en este texto
tiene la intención de sacudir las creencias del cristiano más racional,
a continuación se incluirán dos asombrosas y extraordinarias anécdotas,
relatadas por ese hombre experimentado y siervo de Cristo, Thomas Chalkley,
las cuales son dignas de credibilidad y autenticidad;
y se incluyen especialmente para aquellos jóvenes miembros de nuestra sociedad.

Thomas Chalkley, en su regreso de América,
donde había estado ejerciendo como ministro en varios lugares,
relata el siguiente pasaje en su diario:

Por ese tiempo nuestro doctor tuvo un sueño que él mismo me contó así:
Soñó que desembarcaba en una ciudad grande y espaciosa,
cuyos edificios eran altos y las calles anchas.
Mientras subía por una calle,
vio un gran letrero en el que decía con letras grandes y doradas: "`Vergüenza.`"
A la puerta de la casa a la que pertenecía el letrero,
estaba una mujer con una jarra en su mano, quien le preguntó: "`Doctor, ¿quieres beber?`"
Él respondió: "`Con todo mi corazón,
hace tiempo que no bebo más que agua,`" (nuestro vino y sidra se habían terminado,
pues habíamos navegado por mucho tiempo), y bebió un buen trago, que, según dijo,
lo alegró. Así subió por la calle, tambaleándose de un lado a otro,
cuando un tipo de mal aspecto que venía detrás de
él le dio una palmada en el hombro y le dijo,
que lo arrestaba en nombre del gobernador del lugar.
Él preguntó la causa, diciéndole: "`¿Qué hice?`"
El tipo le respondió: "`Robaste la lata de la mujer.`"
En efecto, tenía la jarra, y entonces fue llevado ante el gobernador,
que era un perro grande y negro,
el más grande y más feroz que jamás había visto en su vida.
Un antiguo compañero suyo testificó en su contra, fue hallado culpable,
y su sentencia fue ir a la cárcel y permanecer ahí para siempre.

Me contó este sueño con tal precisión y con tal énfasis que me afectó con una gran tristeza,
e hizo que mi corazón se conmoviera dentro de mí; porque desde mi perspectiva,
el sueño parecía ser verdadero y su interpretación fiel.^
footnote:[Daniel 2:45 LBLA]
Entonces le dije que él era un hombre inteligente y que podía ver claramente,
que la interpretación de ese sueño respondía con exactitud a su estado y condición,
y se lo interpreté de esta manera: "`Ese lugar grande y espacioso,
con edificios altos y calles anchas, es tu grande y altiva profesión religiosa.
El letrero en el que estaba escrito '`vergüenza`', que viste,
y la mujer a la puerta con la jarra en su mano, ciertamente representa ese grande,
lamentable y vergonzoso pecado de la embriaguez, que sabes que es tu mayor debilidad.
El hombre de mal aspecto que te arrestó en los territorios del diablo, es la muerte,
que ciertamente arrestará a todos los mortales.
El gobernador que viste, representado por el gran perro negro, es sin duda el diablo,
que después de que sus siervos le han servido al máximo,
los atormentará eternamente en el infierno.`"
Entonces el doctor se levantó rápidamente y dijo: "`¡Dios me libre!
No es más que un sueño.`" Pero yo le dije que era un sueño muy revelador,
y una advertencia del Todopoderoso que a veces le habla al hombre mediante sueños.

Alrededor de este tiempo, mientras navegábamos por la Bahía de Lime,
(unos días después del sueño del doctor), nos ocurrió un lamentable accidente.
Nos encontramos con una embarcación holandesa en
la Bahía de Lime un poco más arriba del Start,
los saludamos y ellos hicieron lo mismo.
Dijeron que venían de Lisboa y se dirigían a Holanda.
Estaba cargada con vino, aguardiente, frutas y provisiones similares.
Como nosotros teníamos poco más que agua para beber (porque
nuestro viaje había sido más largo de lo que esperábamos),
enviamos nuestro bote de remos a bordo para comprar
un poco de vino para beber con nuestra agua.
Nuestro doctor,
un comerciante que era pasajero y un marinero subieron
al otro barco y se quedaron ahí tanto tiempo,
que algunos de ellos se embriagaron con el vino,
a pesar de que se les había advertido que tuvieran cuidado.
Cuando regresaban se les lanzó una cuerda, pero ellos, embriagados por el exceso de vino,
no pudieron usarla con destreza,
por lo que volcaron el bote de remos que quedó boca abajo con el doctor debajo
de él. El comerciante pudo aferrarse de una de las cuerdas principales,
con la cual salvó su vida.
Como el marinero no había bebido tanto como los otros dos,
subió rápidamente a la base del bote,
flotó sobre el agua hasta que lograron bajar y lanzar nuestro otro bote de remos,
cosa que se hizo rápidamente, y lo subimos a bordo.
Pero el doctor se ahogó antes de que llegara el bote.
El marinero que se sentó sobre el bote lo vio hundirse, pero no pudo ayudarlo.

Ese fue el mayor ejercicio que atravesamos en todo nuestro viaje;
y mucho más porque el doctor llevaba una vida y conducta malas,
y era muy dado al exceso en la bebida.
Cuando él subió abordo de la mencionada embarcación,
el capitán mandó traer una jarra de vino, y dijo: "`Doctor, ¿quieres beber?`"
Él respondió: "`Sí, con todo mi corazón, porque hace mucho que no bebo vino.`"
Bebió un buen trago,
lo que lo alegró (como había dicho en su sueño). Y a pesar de la
advertencia que tan claramente se le había mostrado tres días antes,
y de las muchas promesas que le había hecho a Dios Todopoderoso--algunas
de las cuales yo mismo fui testigo,
cuando estaba bajo fuertes convicciones--ahora estaba lamentablemente
vencido y ebrio cuando se ahogó.

Esto es, considero,
una viva demostración de la tierna misericordia y del justo
juicio del Todopoderoso sobre los pobres mortales.
Consideré que era digno de ser registrado para la posteridad,
como una advertencia a todos los amantes del vino y de los licores fuertes.
Este ejercicio fue tan grande para mí, que por varios días no pude sobreponerme.
Y un día, mientras meditaba en mi mente sobre estas cosas relacionadas con el doctor,
se me mostró que Dios y sus siervos estaban limpios del asunto, y por tanto,
que su sangre cayó sobre su propia cabeza,
ya que había sido fielmente advertido de sus malos caminos.
Esto sucedió alrededor del año 1699.

La otra circunstancia que aparece en el diario de Thomas Chalkley es la siguiente:

En este año (1722), estuve en el entierro de nuestro Amigo Jonathan Dickenson,
en el que tuvimos una gran reunión. Él era un hombre muy querido por sus Amigos y vecinos.
Durante esta reunión,
fue traído a mi memoria un suceso que él me solía contar estando con salud,
y que creo que es digno de ser dejado por escrito hasta el fin de los tiempos,
y es como sigue:

Sucedió en Port Royal, Jamaica, que dos jóvenes que estaban en una cena con Jonathan,
y con muchas otras personas reconocidas del mundo,
estaban conversando sobre los terremotos;
pues en ese lugar había habido uno anteriormente que fue muy terrible,
y destruyó muchas casas y familias.
Estos dos jóvenes discutían que los terremotos, como todas las demás cosas,
ocurrían como producto de la naturaleza,
negando la existencia de un poder sobrenatural o de una Deidad; tanto así que varios,
sorprendidos por tan malvado discurso, se avergonzaron de su compañía y se fueron.

En ese instante la tierra empezó temblar, moviéndose con una fuerza sumamente grande,
como si la tierra misma estuviera horrorizada ante
tal traición contra su Soberano y Creador,
cuyo estrado es.
Mientras la tierra se estremecía así,
las personas que se habían quedado estaban tan sorprendidas,
que algunas corrieron en una dirección y otras en otra;
pero estos dos jóvenes ateos permanecieron en el
mismo lugar y Jonathan Dickenson se quedó con ellos,
creyendo que la providencia del Todopoderoso Dios podía preservarlo ahí si a Él le placía,
y que si no, sería inútil salir huyendo.
Pero la mano de Dios azotó a estos dos jóvenes, de modo que cayeron al suelo; y,
según me contó Jonathan, a uno de ellos lo puso en una cama, y al otro en un sillón,
pero nunca más hablaron, sino que murieron poco tiempo después.

Este fue el impresionante final de esos dos jóvenes:
un terrible ejemplo para todos los ateos, licenciosos y malvados seres vivientes.
¡Oh!
Que los jóvenes puedan ser advertidos,
para que la mano de Dios puede estar sobre ellos para bien,
y se ocupen con ternura de su salvación.

Una vez, una compañía de irlandeses llegó a Pall Mall cuando George Fox estaba ahí,
pero la reunión ya se había disuelto y George Fox se había retirado a su aposento.
Pero al oír a una de esas personas groseras--un coronel--decir
que él mataría a todos los Cuáqueros,
George Fox bajó y le dijo: "`La ley dice: '`Ojo por ojo, diente por diente`';
pero tú amenazas con matar a todos los Cuáqueros,
aunque ellos no te hayan hecho daño.`" Y añadió: "`Aquí te mostraré el evangelio:
Aquí está mi cabello, aquí está mi mejilla,
y aquí está mi hombro,`" volviéndose hacia él para que pudiera golpearlo si así lo deseaba.
Esto sorprendió tanto al coronel, que él y sus compañeros se quedaron asombrados,
y dijeron: "`Si este es tu principio, según dices ahora,
nunca hemos visto algo igual en nuestras vidas.`"
A lo cual George Fox dijo: "`Lo que soy en palabras, lo soy en la vida.`"
Entonces el coronel se comportó cordialmente;
aunque cierto embajador que había permanecido fuera, y luego había entrado,
dijo que este coronel irlandés era un hombre tan temerario,
que no se había atrevido a entrar con él, por temor a que hiciera un gran daño.
La Historia del Pueblo Llamado Cuáqueros por W. Sewel.
Los dolorosos sufrimientos y la amarga persecución que tuvieron que padecer quienes
se unieron en los comienzos de nuestra Sociedad en la fe y práctica religiosas,
no necesitan ser desarrollados aquí. Nuestros historiadores, especialmente Sewel y Gough,
pueden ser consultados por quienes deseen familiarizarse
con la naturaleza y el alcance de estos hechos,
así como con la paciencia,
la fortaleza y la mansedumbre cristianas manifestadas por
nuestros precursores en la profesión de la fe.
Extraordinaria, sin embargo,
fue muchas veces la influencia de estos temperamentos
celestiales sobre aquellos que los contemplaban,
como se muestra en el ejemplo previo; ese apoyo y fortaleza sobrenaturales,
que recibían quienes eran fieles a Cristo su Señor,
a menudo alcanzaban y tocaban los corazones de sus opositores.
Magistrados en el estrado se mostraban favorables a quienes estaban a punto de condenar,
y adoptaban la misma conducta y creencia que antes había estado dispuestos a reprobar.
Los carceleros y otros reconocían y abrazan esas verdades que ellos habían despreciado.
Y no es de extrañar, si se considera,
que estos modelos de "`espíritu humilde y apacible`"^
footnote:[1 Pedro 3:4 RVG]
prescrito por el evangelio, habían sido, en muchas ocasiones,
miserables esclavos de sus propias inclinaciones y pasiones corruptas.
Algunos de ellos, además,
de esa naturaleza fiera y bulliciosa que no tolera la más mínima provocación;
pero que después, tan golpeados por los terrores del Señor por causa de sus pecados,
tan humillados bajo el poder de la cruz de Cristo,
llegaron a revestirse del pacífico e inofensivo espíritu del Cordero,
sobrellevando todos los ultrajes de sus enemigos con una mente tranquila,
y con un comportamiento amable y compasivo.
Tales hechos no se exponen con el fin de atribuir estos excelentes
"`frutos de justicia`" a una denominación o grupo en particular,
sino más bien para exaltar ese poder y gracia celestiales que,
mediante el único y gran Sacrificio por el pecado, han sido comprados para todos,
y de los cuales con toda certeza pueden participar, en una u otra medida,
todos los que estén dispuestos a recibirlos,
sea cual sea la condición en la que se encuentren,
o la dispensación por la que estén atravesando.
El relato que sigue es parecido al anterior,
y ayuda a reforzar las observaciones expuestas.
