== Capítulo V

[.centered]
=== La Ley y el Evangelio

[.embedded-content-document]
--

Una vez, una compañía de irlandeses llegó a Pall Mall cuando George Fox estaba ahí,
pero la reunión ya se había disuelto y George Fox se había retirado a su aposento.

Pero al oír a una de esas personas groseras--un coronel--decir
que él mataría a todos los Cuáqueros,
George Fox bajó y le dijo: "`La ley dice: '`Ojo por ojo, diente por diente`';
pero tú amenazas con matar a todos los Cuáqueros,
aunque ellos no te hayan hecho daño.`" Y añadió: "`Aquí te mostraré el evangelio:
Aquí está mi cabello, aquí está mi mejilla,
y aquí está mi hombro,`" volviéndose hacia él para que pudiera golpearlo si así lo deseaba.
Esto sorprendió tanto al coronel, que él y sus compañeros se quedaron asombrados,
y dijeron: "`Si este es tu principio, según dices ahora,
nunca hemos visto algo igual en nuestras vidas.`"
A lo cual George Fox dijo: "`Lo que soy en palabras, lo soy en la vida.`"
Entonces el coronel se comportó cordialmente;
aunque cierto embajador que había permanecido fuera, y luego había entrado,
dijo que este coronel irlandés era un hombre tan temerario,
que no se había atrevido a entrar con él, por temor a que hiciera un gran daño.

[.signed-section-signature]
_La Historia del Pueblo Llamado Cuáqueros por W. Sewel._

--

[.centered]
=== El Trompetista

Los dolorosos sufrimientos y la amarga persecución que tuvieron que padecer
quienes se unieron en los comienzos de nuestra Sociedad en la fe y práctica religiosas,
no necesitan ser desarrollados aquí. Nuestros historiadores,
especialmente Sewel y Gough, pueden ser consultados por quienes deseen
familiarizarse con la naturaleza y el alcance de estos hechos,
así como con la paciencia,
la fortaleza y la mansedumbre cristianas manifestadas por
nuestros precursores en la profesión de la fe.

Extraordinaria, sin embargo,
fue muchas veces la influencia de estos temperamentos
celestiales sobre aquellos que los contemplaban,
como se muestra en el ejemplo previo; ese apoyo y fortaleza sobrenaturales,
que recibían quienes eran fieles a Cristo su Señor,
a menudo alcanzaban y tocaban los corazones de sus opositores.
Magistrados en el estrado se mostraban favorables a quienes estaban a punto de condenar,
y adoptaban la misma conducta y creencia que antes había estado dispuestos a reprobar.
Los carceleros y otros reconocían y abrazan esas verdades que ellos habían despreciado.
Y no es de extrañar, si se considera,
que estos modelos de "`espíritu humilde y apacible`"^
footnote:[1 Pedro 3:4 RVG]
prescrito por el evangelio, habían sido, en muchas ocasiones,
miserables esclavos de sus propias inclinaciones y pasiones corruptas.
Algunos de ellos, además,
de esa naturaleza fiera y bulliciosa que no tolera la más mínima provocación;
pero que después, tan golpeados por los terrores del Señor por causa de sus pecados,
tan humillados bajo el poder de la cruz de Cristo,
llegaron a revestirse del pacífico e inofensivo espíritu del Cordero,
sobrellevando todos los ultrajes de sus enemigos con una mente tranquila,
y con un comportamiento amable y compasivo.
Tales hechos no se exponen con el fin de atribuir estos excelentes
"`frutos de justicia`" a una denominación o grupo en particular,
sino más bien para exaltar ese poder y gracia celestiales que,
mediante el único y gran Sacrificio por el pecado, han sido comprados para todos,
y de los cuales con toda certeza pueden participar, en una u otra medida,
todos los que estén dispuestos a recibirlos,
sea cual sea la condición en la que se encuentren,
o la dispensación por la que estén atravesando.
El relato que sigue es parecido al anterior,
y ayuda a reforzar las observaciones expuestas.

[.embedded-content-document]
--

Un cierto trompetista, entrando en una reunión de Amigos,
comenzó a tocar su trompeta de manera insolente,
con el fin de ahogar la voz del que predicaba; esto, sin embargo,
tuvo el efecto contrario, y avivó más el celo del predicador,
de modo que continuó como si nada le estorbara.
Finalmente, el trompetista, para recobrar su aliento, se vio obligado a dejar de soplar,
pero gobernado aún por un espíritu maligno,
después de una breve pausa comenzó a tocar de nuevo; pero sin importar qué hiciera,
no pudo apartar al predicador de su discurso,
aunque impidió que el auditorio escuchara lo que se decía. De esta manera se cansó tanto,
que se vio obligado a descansar de nuevo para respirar, por lo que,
a pesar de su perversa voluntad, oyó lo que el predicador decía,
lo cual era tan penetrante que el trompetista quedó profundamente afectado,
y estallando en lágrimas, confesó su crimen y se convirtió en un verdadero penitente.

[.signed-section-signature]
William Sewel

--

[.centered]
=== William Caton

William Caton fue un ejemplo vivo de la eficacia de la gracia divina,
y un eminente instrumento en la mano del Señor para promover
Su propia obra de reforma y justicia en la tierra.
Vivió en un período muy temprano de los anales de nuestra Sociedad;
y algunos extractos de su diligencia, celo y devoción en la causa a la que se unió,
pueden ser recordados para beneficio de la generación presente.

Cuando tenía unos catorce años, fue acogido por la familia del Juez Fell en Swarthmore,
en Lancashire.
Sin embargo, mucho tiempo antes de esto,
su corazón había sido visitado con las impresiones de la bondad divina,
bajo cuya influencia, mientras meditaba en las obras de Su Creador,
a menudo se sentía conmovido y embargado por la ternura,
y en ocasiones refrenado de los malos hábitos propios de los niños. Al cabo de un tiempo,
el testigo de Dios en él llegó a despertarse más plenamente,
por lo que sus pecados fueron puestos en orden delante de él. Y aunque al principio,
como una becerra indómita que no está acostumbrada al yugo, intentaba salirse de él,
y mediante una actitud despreocupada y desenfrenada apagaba el bien dentro de él;
el amor de Dios hacia él era tal,
que era perseguido con juicio cada vez que era sorprendido por el mal.
Algunas veces, en efecto,
se retiraba a un lugar apartado para esperar en el
Señor y meditar en Sus maravillosas obras,
y en esa práctica encontraba frecuentes refrescamientos para el alma.

La primera visita de George Fox a la familia Fell, en este momento,
parece haber sido la ocasión que abrió y amplió grandemente su perspectiva,
y que estableció su mente sobre la Roca de la verdadera religión, Jesucristo;
cuyo reino de gracia y verdad comenzó desde entonces a establecerse en su corazón,
y las facultades de su entendimiento, junto con las inclinaciones de su voluntad,
a ser en cierta medida sometidas y santificadas.
Sin embargo,
tuvo que atravesar muchos conflictos y experiencias antes de que pudiera
decirse que su alma había sido en cierta medida redimida de la tierra,
y liberada del espíritu terrenal,
"`hecha nueva en Cristo Jesús,`" y establecida en la fe y la santidad.
Durante ese tiempo,
habla de que sus estudios escolares se habían convertido en una carga, y de que,
hallándose afligido y abatido de espíritu,
era incapaz de terminar sus ensayos y versos en latín, etc.

Las gloriosas visitaciones de la bondad del Todopoderoso sobre él,
alrededor de los diecisiete años, fueron tales, que su espíritu se derritió,
y por decirlo así, se quebrantó bajo el sentido de ellas;
grandes fueron los gozos y las consolaciones de los que participó,
y muchas las preciosas promesas que le fueron reveladas y confirmadas.
La frescura del poder celestial que lo acompañaba,
y que también reposaba sobre la familia bajo cuyo techo residía;
la cercanía y el afecto que prevalecía entre ellos, los unos hacia los otros,
su celo y su fe, escribe él, eran mucho más de lo que podía describirse con palabras.
Las reuniones eran muy preciosas para ellos en aquellos días,
tanto que algunos solían pasar parte de la noche esperando en el Señor "`todos unánimes
juntos,`" a menudo después de que el resto de la familia se había ido a la cama.
El consolador y renovador beneficio que cosechaban era muy grande.
"`Porque,`" dice William Caton,
"`si habíamos sufrido alguna pérdida en nuestra condición espiritual durante el día,
estando fuera en nuestros trabajos o cosas similares,
entonces éramos en gran medida restaurados,
mediante el amor y la misericordia de nuestro Dios
que abundaban grandemente para con nosotros.`"

Tales tratos de gracia,
acompañados por la ayuda y cuidado instrumentales que recibió de George Fox,
así como de Margaret Fell y de otros, evidentemente no fueron en vano.
Los designios de la inescrutable Sabiduría con respecto a él,
no fueron perturbados ni retardados, sino que,
mediante la rendición y la confianza en la mano formadora del divino Obrero,
Su bendita obra siguió adelante, y como resultado fue formado un vaso honorable,
apto para el uso del Maestro,
llevando la inscripción "`SANTIDAD A JEHOVÁ.`" Un fiel y apto soldado,
que ya no estaba a su propia disposición,
sino que fue rápidamente llamado a un cargo prominente en el servicio de su Líder;
fuerza, valor y denuedo le fueron otorgados en cada instancia,
la preservación y la paz fueron su porción,
y el nombre de su Dios fue en verdad glorificado a través de él.

Cerca del año 1655, teniendo entonces no más de dieciocho años,
comenzó su labor como ministro de ese buen Espíritu que
fue "`derramado`" sobre él "`abundantemente por Jesucristo.`"^
footnote:[Tito 3:6]
Su diligencia en el deber de este sagrado oficio resulta difícil de creer;
recorriendo gran parte de este reino principalmente o por completo a pie,
a menudo en pleno invierno, y durante el tiempo más crudo de la persecución. Sin duda,
su predicación iba acompañada de su propia evidencia en los corazones de sus oyentes;
como él mismo escribe,
"`la palabra del Señor crecía poderosamente y muchos eran añadidos a la fe.`"
Como breve ilustración de una parte de sus labores
en este primer año de su compromiso público,
se mencionan algunos distritos o lugares que delimitaron sus viajes,
sin hacer referencia al trayecto intermedio.

De Swarthmore viajó a Norwich, de allí a Londres, Kent, Calais en Francia, Yarmouth,
Sunderland, Lancashire, Shields; de Flushing a Middleburg, Rotterdam, etc.
Luego a Yorkshire, por Durham hasta Lancashire, Berwick, Edinburgh, Glasgow, Stirling,
etc., y de regreso por Northumberland, Durham y Westmoreland hasta Swarthmore.
Algunas de esas visitas no fueron de corta duración, como podría suponerse.
Al referirse a un viaje posterior, menciona:
"`Me faltaría tiempo para describir con detalle el
extraordinario buen servicio que tuvimos,
a veces en casas del campanario,^
footnote:[Me parece necesario señalar que la palabra
"`iglesia`" que está en las Sagradas Escrituras,
nunca se ha aplicado a un templo externo o edificio,
sino más bien a un grupo de creyentes, ya sea en general o en particular.]
otras en calles y mercados,
etc.`" además de sus compromisos privados y públicos entre sus compañeros profesantes.
Pero cada año restante de su vida hasta su término,
estuvo quizás igualmente marcado por la presteza en cumplir con los encargos del Señor,
por ocuparse fielmente con ese don que le había sido encomendado,
y por la diligente atención al ministerio que había recibido en el Señor para cumplirlo.^
footnote:[Colosenses 4:17]

Tomando en consideración el propósito de estas páginas,
parece adecuado terminar el relato de William Caton con algunas observaciones
que él hizo en su diario sobre este importante tema del ministerio.
Como están vinculadas con su propia experiencia,
pueden ilustrar vívidamente para el entendimiento de algunos,
el estado de completa dependencia y vacío al que
deben ser llevados los ministros del evangelio,
antes de que el Señor les dé "`palabra y sabiduría,`"
y les sea abierto "`puerta para la palabra.`"^
footnote:[Lucas 21: 15, Colosenses 4:3]

[.embedded-content-document]
--

Tuve muchas reuniones preciosas y numerosas en
el condado +++[+++dice William Caton refiriéndose a Kent],
y el Señor estuvo muy a mi lado, quien me proveyó abundantemente de Su palabra y poder;
tanto,
que en diversas ocasiones me quedaba admirando de la plenitud
que recibía de Él. Y no era sólo yo quien estaba admirado,
sino muchos más,
que al ver con el ojo de la razón mi tabernáculo terrenal u hombre exterior,
no esperaban gran cosa de mí, siendo entonces de apenas unos veinte años,
ni había sido muy activo en la religión hasta que fui convencido de la Verdad de Dios.
Con todo,
el Señor se complació en abrir en mí y por medio de mí muchas cosas celestiales,
para que pudiera comunicarlas a la multitud, que algunas veces era tan numerosa,
que estaba listo a decir dentro de mí:
"`¿De dónde conseguiré pan para satisfacer a estos?`"
Y cuando contemplaba mi propia debilidad e insuficiencia,
me sentía a punto de desfallecer;
pero cuando miraba solo al Señor y ponía mi confianza enteramente en Él,
me sentía fuerte y valiente.
Pues el Señor me había mostrado esto mediante Su eterna luz,
durante una época en que me lamentaba por mi propia debilidad y
gemía bajo el peso de la carga del servicio y la obra del Señor,
diciendo, o pensando dentro de mí:
¡Oh! tales y tales (refiriéndome a los más aptos y sabios
de los hermanos) están tan preparados y provistos,
que no necesitan preocuparse por el servicio al que sean llamados.
Pero en cuanto a mí, soy tan simple, soy tan débil,
y nunca tengo nada preparado de antemano, ni casi nunca sé,
al entrar en una reunión de cientos de personas, qué voy a decir, o si diré algo o nada.

Incluso cuando estaba lleno de esos y otros razonamientos similares,
el Señor me mostró, cómo a "`los que tenían mucho no le sobró,
ni le faltó al que tenía poco,`" tal como sucedió con los israelitas
de antaño. Porque los hermanos que eran sabios y eminentes,
que habían recibido mucho del Señor, he aquí que se les requería mucho más;
de modo que de todo lo que tenían, nada les sobraba,
sino lo que debían emplear en la obra y el servicio a Dios.
En cuanto a mí, que era tan pequeño ante mis propios ojos,
y tan vil y despreciable ante los ojos de otros, no tenía motivos para quejarme;
pues aunque a menudo no sabía qué iba a decir al entrar a una reunión;
aun en esos momentos, al Señor le placía darme su palabra tan abundantemente,
que por medio de Él me era posible hablar dos, o tres,
o en ocasiones hasta cuatro horas a la congregación, con poca o ninguna pausa.
Y muchas veces me sucedió que, así como no sabía lo que iba a decir antes de una reunión,
tampoco podía recordar después de la reunión lo que había hablado en ella.
Sin embargo, tenía abundancia y plenitud, aunque asistía a reuniones diariamente y,
no sólo eso, sino también por las noches.
El Señor me daba siempre una provisión fresca de
ese buen tesoro que provee cosas nuevas y cosas viejas.

Ahora,
estas cosas las cuento--+++[+++continúa William Caton--y el lector sin duda creerá su afirmación,
así como la del compilador de este relato,
cuyo objetivo es el mismo]--no para mi propia alabanza, más bien digo: "`No a mí,
no a mí, que no tengo sino lo que he recibido, sea la alabanza al Señor,
quien es el dador de toda buena dádiva y de todo don perfecto.`"
Puedo decir con verdad, que lo que recibí de Él, lo entregué a Su pueblo;
y me regocijé en el Señor, a pesar de mis grandes viajes y sufrimientos,
todos los cuales fueron fáciles de sobrellevar por medio de Él;
ni fueron demasiado para mí,
con todos los riesgos y peligros que atravesé por mar y por tierra,
comparados con el poder y la presencia del Todopoderoso,
que tan dulce y eminentemente me acompañó durante aquellos días.

--

[.centered]
=== William Bennit y la Joven Asesina

William Bennit, unos de los primeros y eminentes miembros de nuestra Sociedad,
estuvo preso por motivos de consciencia en la cárcel de Bury, en el año 1668.
Un día, se dirigió seriamente a una joven, que era una delincuente,
y le preguntó si a lo largo de su vida no había transgredido muchas veces su conciencia;
si no había sentido a menudo frenos secretos y reprensiones interiores,
y se había turbado en su mente debido al mal cometido.

Esto lo hizo de una manera tan convincente,
que ella no sólo asintió a lo que le había mostrado,
sino que su amonestación alcanzó tanto el corazón de la joven, que vio claramente,
que si no hubiera sido tan testaruda y desobediente a esas reprensiones interiores,
con toda probabilidad no habría llegado a una caída
tan miserable como la que padecía entonces.
Porque el hombre que no desea el conocimiento de los caminos de Dios y se aparta de Él,
queda desamparado y no puede guardarse del mal,
aun de aquel que antes habría aborrecido en grado sumo, y habría dicho con Hazael:
"`¿Acaso es tu siervo, un perro, para que haga tan enorme cosa?`"^
footnote:[2 Reyes 8:13 RVG]

La sana amonestación de W. Bennit obró de tal manera sobre la mente de la joven,
que ella,
que nunca había conversado con los Cuáqueros y era
completamente ignorante de la doctrina de ellos,
llegó a comprender que "`la gracia de Dios que trae
salvación`" era lo que ella había resistido a menudo,
y que esa gracia no la había abandonado del todo,
sino que en ese momento la estaba haciendo consciente de la grandeza de
su transgresión. Esta consideración pesó tan poderosamente sobre ella,
que de ser una pecadora muy grave, se convirtió en una verdadera penitente,
y con un corazón lleno de tristeza le clamaba al Señor que
se complaciera en no esconder Su rostro de ella.
Y continuando en este estado de humillación y sincero arrepentimiento,
y perseverando en la súplica, con el tiempo sintió una medida de alivio;
y finalmente alcanzó una segura esperanza de perdón
mediante la preciosa sangre del inmaculado Cordero,
que vino al mundo a salvar a los pecadores y llamarlos al arrepentimiento,
y que también murió por los pecados del mundo.

Ella dio pruebas manifiestas de este cambio en su juicio frente al juez Hale, quien,
habiendo oído de cuán arrepentida estaba, deseaba con ansias perdonarla,
e intencionalmente hizo que se insertaran en la acusación
las palabras "`voluntaria y deliberadamente,`" para que,
aprovechándose de eso,
pudiera negar el cargo y así anular la acusación. Pero cuando se le preguntó
según la forma "`culpable o no culpable,`" rápidamente contestó:
"`Culpable.`"
Esto asombró al juez,
quien le dijo que parecía que no había considerado debidamente lo que había dicho;
ya que no era fácil de creer que una persona como ella--que tal vez había tratado
bruscamente a su hijo--lo hubiera matado "`voluntaria y deliberadamente.`"
Aquí el juez le abrió una puerta trasera para evitarle la pena de muerte.
Pero en ese momento el temor de Dios había ganado tanto lugar en el corazón de ella,
que ninguna manipulación serviría, ninguna hoja de higuera podría servirle de cubierta,
porque ahora sabía, que eso habría sido añadir pecado al pecado;
'`cobijarse con cubierta, y no del Espíritu de Dios.`'^
footnote:[Isaías 30:1]
Por tanto ella le indicó de manera clara al tribunal,
que en verdad había cometido intencionalmente el malvado acto,
para ocultar así la vergüenza de haber dado a luz un niño fuera del matrimonio;
y que habiendo pecado tan gravemente y estando afectada entonces por el verdadero arrepentimiento,
por ningún medio podía excusarse,
sino que estaba dispuesta a sufrir el castigo que exigía la ley;
no podía sino reconocerse culpable,
pues de otra manera ¿cómo podría esperar el perdón de Dios.

Esta confesión libre y franca, pronunciada con un rostro serio,
afectó tanto al juez que las lágrimas le corrían por el rostro, y muy entristecido dijo:
"`Mujer, nunca me había topado con un caso como este.
Tal vez tú, que eres joven y hablas tan piadosamente,
como quien ha sido golpeada en el corazón por el arrepentimiento,
aún podrías hacer mucho bien en el mundo; pero ahora me obligas a que, _ex officio_,^
footnote:[Obligación bajo la que está alguien en virtud de su oficio.]
pronuncie la sentencia de muerte contra ti, ya que no admites ninguna excusa.`"
Manteniéndose firme en lo que había dicho, el juez pronunció la sentencia de muerte.
Y más tarde, cuando fue llevada al lugar de ejecución,
pronunció un conmovedor discurso al pueblo, exhortando a los espectadores,
especialmente a los jóvenes, a tener el temor de Dios ante sus ojos,
a atender a Sus secretas reprensiones contra el mal,
para no afligir ni resistir al buen Espíritu del Señor;
pues al no haber atendido ella misma esto a tiempo, la había hecho correr en el mal,
y así, continuando de maldad en maldad había llegado a este funesto fin.
Pero dado que había confiado firmemente en la infinita misericordia de Dios,
y creía verdaderamente que sus pecados, aunque rojos como la sangre,
habían sido lavados por la sangre pura de Cristo, su Redentor,
podía partir de esta vida con contentamiento.

De esta manera predicó en el patíbulo una doctrina
muy consonante con la de los llamados Cuáqueros,
y dio pruebas conmovedoras de que su alma inmortal estaba por entrar en el paraíso,
como la del ladrón en la cruz muchos siglos antes.

[.centered]
=== George Fox y Oliver Cromwell

George Fox, en el transcurso de sus viajes en la obra del ministerio, llegó a Drayton,
en Leicestershire, alrededor del año 1654.
Tras dejar su lugar natal, pasó por uno o dos pueblos,
pero no había llegado muy lejos cuando fue aprehendido por un grupo
de soldados a caballo y llevado ante el coronel Hacker.
En ese momento, corrían rumores de un complot contra Oliver Cromwell, de modo que,
aunque George Fox pudo justificarse lo suficiente en este aspecto,
como no se atrevía prometer hacer de su casa una prisión,
dejando de asistir a las reuniones religiosas,
fue enviado a Londres para ser presentado ante el Protector.

El Protector, al tener conocimiento de él, requirió que firmara un documento,
prometiendo no tomar armas contra él ni contra el gobierno actual.
G+++.+++ Fox lo hizo en un escrito,
en el que declara que él había sido enviado por Dios para dar testimonio
contra toda violencia y contra las obras de las tinieblas,
para volver a las personas de las tinieblas a la luz,
y llevarlos del motivo de la guerra y pelea al evangelio pacífico.
Después de un tiempo, el mensajero regresó y lo llevó a Whitehall.
Siendo conducido al aposento donde se hallaba el Protector, George Fox dijo:
"`Paz sea en esta casa,`" y le pidió que se mantuviera en
el temor de Dios para que pudiera recibir sabiduría de Él,
y por medio de ella pudiera ser ordenado y ordenar
todas las cosas bajo su mano para la gloria de Dios.
También conversó mucho con él acerca de religión,
y durante ese tiempo Cromwell se condujo muy moderadamente,
pero dijo que G. Fox y sus amigos disputaban con los ministros.
G+++.+++ Fox le dijo que eran ellos los que contendían con él y sus amigos;
pues él no podía sostener a tales ministros tal como eran, ni podía darles de comer,
viendo que no eran como Cristo lo había ordenado, sino que contra tales, los profetas,
Cristo y los Apóstoles declararon expresamente en contra de los codiciosos y avaros,
que predican por ganancia deshonesta, etc.
También dijo, que todos los cristianos tenía las Escrituras,
pero carecían del poder y del Espíritu de quienes las habían dado;
y que esa era la razón por la que ellos no estaban en comunión con el Hijo,
ni con el Padre, ni con las Escrituras, ni unos con otros.
Mientras hablaba de esta manera, Cromwell dijo varias veces: "`Muy bueno.`"
"`Es verdad.`"

G+++.+++ Fox intercambió más palabras con él, pero al ver que la gente entraba,
retrocedió un poco, y mientras se volvía,
Cromwell lo cogió por la mano y con lágrimas en sus ojos dijo: "`Ven de nuevo a mi casa,
porque si tú y yo pasáramos una hora juntos al día,
estaríamos más cerca el uno del otro;`" y añadió que no
le deseaba más mal del que deseaba a su propia alma.
A esto G. Fox replicó, que si él lo hacía, perjudicaría su propia alma;
y le pidió que le prestara atención a la voz de Dios
para que pudiera permanecer en Su consejo,
y obedecerlo; y que si lo hacía, eso lo guardaría de la dureza de corazón,
pero que si no escuchaba la voz de Dios, su corazón se endurecería.^
footnote:[Salmo 95:8]
Esto alcanzó al protector tanto, que dijo que era cierto.

Luego G. Fox salió, y el capitán Drury le dijo mientras lo seguía,
que el señor protector había dicho que quedaba en libertad y que podía ir donde quisiera.
Entonces fue llevado a un gran salón, donde los caballeros del protector iban a cenar.
George preguntó por qué había sido llevado ahí,
y le dijeron que lo había ordenado el protector, para que cenara con ellos.
Pero George, en su modo de hablar, les pidió que le dijeran al protector,
que él no comería un bocado de su pan, ni bebería un sorbo de su bebida.
Cuando Cromwell lo oyó, dijo:
"`Ahora veo que ha surgido y se ha levantado un pueblo que no puedo ganar con regalos,
ni honores, ni oficios, ni cargos;
pero con las otras sectas y pueblos sí puedo hacerlo.`"
En respuesta a eso le fue dicho,
que los Cuáqueros habían abandonado todo lo que era de ellos,
y que no era probable que buscaran tales cosas de él.

[.centered]
=== El Campeón de Lucha

[.embedded-content-document]
--

En Londres se acostumbra, en verano,
cuando se acerca la noche y los artesanos dejan de trabajar,
a que muchos hombres fornidos se reúnan en los campos
para probar su habilidad y su fuerza en la lucha;
y generalmente una multitud de personas se queda mirando en un círculo.
Sucedió entonces que Edward Burrough pasó por el lugar donde estaban luchando,
y de pie entre los espectadores vio cómo un sujeto fuerte
y hábil ya había arrojado al suelo a otros tres,
y estaba esperando a un cuarto campeón, si alguno se atrevía a entrar.
Finalmente, como nadie fue suficientemente audaz para intentarlo,
E+++.+++ Burrough entró en el espacio de pelea,
rodeado comúnmente por personas de todo tipo de condición;
y al mirar al luchador con un semblante serio, el hombre se sorprendió mucho,
porque en lugar de un antagonista brioso se encontró con un joven sobrio y solemne.
Todos estaban atónitos ante esta escena,
esperando ansiosamente saber cuál sería el resultado de este combate.
Sin embargo, E. Burrough se proponía una pelea completamente diferente.
Pues después de haber peleado contra la maldad espiritual
que una vez había prevalecido sobre él,
y haber vencido en alguna medida por la gracia de Dios,
ahora se esforzaba por pelear contra ella en otros,
y por volverlos de la maldad de sus caminos.

Con esta intención les comenzó a hablar muy seriamente a los espectadores,
y alcanzó los corazones con un poder tan penetrante,
que fue escuchado por esta variada multitud con no menos atención que admiración,
pues su discurso procuraba volverlos de las tinieblas a la luz,
y del poder de Satanás a Dios.
Para lograrlo luchó con palabras convincentes,
mostrando que Dios no se había quedado sin testimonio,
sino que le había dado al hombre una medida de Su gracia,
y alumbrado a todos con la luz de Cristo.
De esta forma predicó con celo, y aunque muchos consideraron eso una rareza,
tuvo tal efecto, que algunos fueron convencidos de la Verdad.
Pues Burrough era una quebrantador de corazones de piedra, y por eso,
no fue injustamente llamado, por cierto autor,
"`hijo del trueno,`" aunque a su debido tiempo,
también pronunciaba palabras de consuelo a los que
tenían un corazón quebrantado y un espíritu contrito.

[.signed-section-signature]
William Sewel

--

[.centered]
=== Gilbert Latey y el lord D`'Aubigny

Gilbert Latey, oriundo de Cornwall, se formó allí en el oficio de sastre,
el cual continuó ejerciendo al establecerse en Londres.
Llevaba una vida y conducta sobrias, y al sentir respiraciones del alma por el Señor,
buscó a aquellos que eran los más celosos en ese tiempo.
El Señor, al mirar la integridad de su corazón,
lo prosperó de tal manera que alcanzó gran reputación en el mundo;
teniendo un buen negocio en su oficio,
y siendo empleado y respetado por muchas personas de la
más alta posición y alcurnia entonces en el reino.
Sin embargo, en medio de todos estos goces externos,
su mente y sus deseos seguían puestos en hallar paz con el Señor,
en el conocimiento de Su Verdad pura y forma de adoración.
Estando en esta condición de búsqueda,
siguió a quienes le parecían los más puros en sus profesiones,
pero sin mucha satisfacción;
hasta que se encontró con Edward Burrough en una reunión en Londres;
y al ser dirigido por este fiel ministro a la única Guía a la paz verdadera,
sin consultar con carne ni sangre,
se rindió a la "`visión celestial,`" tomando la cruz y menospreciando el oprobio,
considerando todas las cosas como escoria y basura, para "`ganar a Cristo,
y ser hallado en Él.`"^
footnote:[Filipenses 3: 8-9]

No había pasado mucho tiempo alistado bajo el estandarte del Señor,
profesando y confesando Su bendita Verdad,
cuando le plació al Señor poner sobre él una dura prueba,
como cortar la mano derecha o sacar el ojo derecho.
Pues, teniendo un gran negocio en el mundo,
y por ello relacionado con personas de alta posición y alcurnia,
que deseaban que sus vestiduras fueran adornadas
con gran gasto y exceso de encajes y lazos,
llegó a estar bajo una consciente inquietud que lo
llevó a rechazar este aspecto superfluo de su oficio,
y también a no permitir que sus criados pusieran
tales adornos en los atuendos de los grandes.
Por causa de esto, algunos decían que había enloquecido, o que pronto estaría;
sus clientes adinerados, que vestían a la moda, en general lo abandonaron,
y su negocio decayó tanto, que teniendo muchos criados, se vio obligado a despedirlos.
No sabía si él mismo, que había tenido un negocio tan próspero,
acabaría siendo el siervo de algún otro del oficio,
y trabajar como jornalero para ganarse su pan.
Esta prueba fue muy grande,
pues llegó a ser despreciado por los hijos de su propia madre y, por así decirlo,
desterrado de la casa de su padre.
Sin embargo esperando con paciencia el tiempo del Señor, fue sostenido durante la prueba,
y fortalecido para preferir dejarlo todo antes que perder su paz con su Hacedor.

Así aquel que nunca abandona a los que confían en Él y le son fieles,
sostuvo su espíritu con alegre rendición bajo todos sus ejercicios,
y no solo proveyó para todas sus necesidades,
sino que también lo capacitó para suplir las necesidades de otros;
lo cual hizo de varias maneras,
especialmente mediante su influencia entre las personas
de rango y alta posición en el mundo.
Cabe agregar que,
poco tiempo después de haber rendido sacrificio al Señor en obediencia a Su voluntad,
como se mencionó anteriormente,
el Señor lo ordenó como ministro de esas preciosas verdades y consuelos,
a las cuales había mostrado tan grande estima y valor.

Este mismo hombre, piadoso y útil,
comenzó desde temprano a usar su influencia y relaciones
con personas distinguidas para el beneficio de otros,
especialmente de aquellos de la misma "`familia de la fe;`" para quienes
procuraba hallar alivio ante los grandes sufrimientos que les tocaba padecer.
En una ocasión, consideró presentarse ante el lord D`'Aubigny, quien,
con la ascensión de Charles II,
llegó a Inglaterra con la madre de la reina y era su "`gran limosnero.`"^
footnote:[Gran limosnero:
Cargo oficial en la corte real encargado de distribuir limosnas
y asistencia a los necesitados en nombre del monarca.
Su función combinaba autoridad,
representación de la corona y responsabilidad sobre la caridad oficial.]
Este lord tenía gran influencia y poder en la isla de Malta,
donde dos Amigas habían sido confinadas en la prisión de la Inquisición,
y tratadas con crueldad y dureza por testificar del evangelio de la gracia de Dios,
y advertir a las personas que se volvieran al Señor. Gilbert obtuvo acceso a él,
y halló que era un hombre de buen carácter; y aunque era un sacerdote ordenado,
y los Amigos durante esa época eran casi en todas partes difamados y maltratados,
fue muy amable y abierto en su trato con Gilbert; y solía razonar con él,
como Félix con Pablo,
sobre los principios de la verdad y el camino del Señor.

En una ocasión,
conversando con Gilbert, el lord D`'Aubigny dijo:
"`No importa cuánto tiempo hable contigo, tú me hablarás del Espíritu de Dios,
de la gracia de Dios, de Sus obras y operaciones,
y del amor de Dios del cual ustedes han sido hechos testigos mediante Jesucristo,
lo cual considero que, en cierta medida, puede ser verdadero; sin embargo,
¿no crees que es bueno tener algo externo que represente eso que tanto aman?`"
A lo que Gilbert respondió que la Sustancia de todas las cosas había llegado,
"`Cristo en nosotros, la esperanza de gloria;`" y que todos los tipos,
representaciones y sombras externos debían llegar
a su fin y ser absorbidos en nuestro bendito Señor,
quien dijo a sus discípulos que era necesario que él se fuera, porque: "`Si no me fuera,
el Consolador no vendría a vosotros; mas si me fuere,
os lo enviaré;`" y "`cuando el Espíritu de verdad venga,
Él os guiará a toda verdad;`" y también dijo que Aquel que estaba +++[+++entonces]
con ellos, estaría en ellos.
De modo que, al ser todo esto experimentado,
ya no se necesitaba nada externo que lo representara o que los hiciera recordar, pues Él,
al estar tan cerca del hombre y de la mujer, era el recordatorio diario de los santos.

Después de esto, se separaron;
pero Gilbert solía visitarlo y le recordaba que mostrara compasión
a los Amigos que sufrían bajo confinamiento por causa de consciencia,
muy lejos de sus amigos y de su tierra natal.
En otra ocasión, al ir a visitarlo, le pidió a Gilbert que lo siguiera;
y lo condujo a la capilla de la reina,
donde viendo Gilbert a las personas sobre sus rodillas
y las candelas encendidas sobre el altar,
se detuvo y le preguntó al lord D`'Aubigny qué pretendía al pedirle entrar ahí;
"`porque,`" dijo: "`sabes que no puedo inclinarme ante nada.`"
A lo que él respondió: "`Sígueme, y nadie te hará daño o se meterá contigo.`"
Entonces, Gilbert lo siguió a través de la capilla hasta una habitación detrás del altar,
donde estaba otro de los sacerdotes de la reina; y habiendo ahí algunos altares menores,
el lord D`'Aubigny le dijo a Gilbert: "`Nunca me has visto con mi hábito sacerdotal,
pero ahora lo harás.`" Y mientras se preparaba,
el poder del Señor obró de tal manera en Gilbert,
que subió a un lugar que llamaban altar privado,
y la palabra del Señor vino a él para predicarles.
Entre muchas declaraciones, dijo:
"`Nosotros tenemos un altar del cual no tienen derecho a comer.`"
Entonces el sacerdote de la reina preguntó: "`¿De qué altar hablas?`"
Gilbert respondió:
"`El altar del que hablo es aquel en el que los santos
elevan sus oraciones al Dios viviente.`"^
footnote:[Ver Apocalipsis 8:4]
Entonces, el sacerdote respondió: "`Amigo,
no hay estado más alto alcanzable que del que hablas;`" y así se despidieron.

[.centered]
=== Persecución en Bristol en 1682

Está registrado en la historia de nuestra sociedad religiosa una lúgubre
escena de la persecución que se abrió en Bristol en el año 1682;
cuyos diversos pormenores, aunque no puedan detallarse aquí,
quizás puedan ser aludidos brevemente,
en particular por uno o dos incidentes relacionados con ellos.

Las reuniones de los Amigos eran gravemente interrumpidas, sus casas allanadas,
y se cometían casi todo tipo de actos de violencia y abuso,
principalmente por instigación de un cruel alguacil.
Es cierto que, en aquel entonces,
las reuniones de otros disidentes protestantes eran también perturbadas;
pero parece que no eran tan persistentes en su testimonio religioso, y por ello,
no eran tan repudiados con los insolentes ataques, a los que este pueblo,
debido a su constancia y su negativa a resistir se veían sujetos.
A los personajes más viles se les permitía y se les animaba a cometer
toda clase de "`desenfreno de disolución,`" sin distinción de sexo,
edad o condición. Incluso hombres y mujeres ancianos
eran arrastrados a prisión con violencia y golpes,
y los niños pequeños eran golpeados en la cabeza hasta quedar aturdidos,
y luego llevados a la prisión de Bridewell,
y aterrorizados ante la posibilidad de ser azotados,
a menos que prometieran no asistir más a las reuniones.

Pero el odio y las amenazas que se utilizaron, incluso contra esta clase de sufrientes,
no lograron doblegar su constancia.
Apenas quedó una piedra sin mover en sus intentos de afligir a
los Amigos y disuadirlos de reunirse para adorar a su Hacedor.
Estos disturbios continuaron hasta que casi todos los hombres fueron llevados a prisión;
allí, sin embargo, sus persecuciones no cesaron,
sino que se incrementaron considerablemente debido a las privaciones y malos tratos.
Estaban tan hacinados,
que apenas había suficiente espacio para que pudieran acostarse por la noche en el suelo;
y en otros aspectos, su salud y sus vidas estaban en tal peligro,
que cuatro médicos de Bristol consideraron necesario emitir un certificado al respecto.
Tras esto,
las reuniones religiosas de los Amigos de Bristol
continuaron celebrándose principalmente por mujeres,
quienes también fueron aprehendidas,
hasta que finalmente pocos o ninguno salvo niños que permanecían
con los sirvientes en las casas de sus padres,
quedaron libres.

Es muy notable, sin embargo, que los niños antes mencionados, menores de dieciséis,
llevaran a cabo ahora lo que a sus padres no podían--se reunían para la adoración divina,
y permanecían fieles sin desmayar, a pesar de todos los insultos de una chusma malvada,
de la que sufrieron en gran medida.
Diecinueve de ellos fueron llevados a la Casa de
Corrección y permanecieron allí por un tiempo,
aunque no estaban dentro del alcance de la ley;
y cuando se les amenazaba con azotarles si volvían a la reunión, tal era su celo que,
menospreciando todo reproche y abuso, permanecieron firmes en su deber.
Esta persecución duró hasta el año siguiente,
al igual que en muchos otros lugares de la nación por la misma época.

Pero el ejemplo anterior de los sufrimientos de esta Sociedad en los
primeros tiempos no debe considerarse de ningún modo como un caso extremo.
Aquellos que lean los registros de sus sufrimientos--muchos de los cuales
aparecen en su historia o en las memorias de individuos entre ellos--serán
fácilmente convencidos de la veracidad de lo escrito.

La narración anterior concluirá con un relato sobre la muerte del carcelero,
quien fue el principal instrumento de crueldad hacia los sufrientes luego de ser encarcelados.
Algunos de los prisioneros habrían trabajado de buena
gana en la prisión para ganarse algo para su sustento,
pero él no lo permitió. Otros prisioneros se enfermaron de la fiebre manchada,^
footnote:[La fiebre manchada es una enfermedad bacteriana
que se propaga mediante las picaduras de piojos,
pulgas y garrapatas infectados.]
y algunos murieron a causa de ella; con todo,
nada de esto suavizó el corazón endurecido del carcelero.
Finalmente sufrió un golpe muy duro,
porque se enfermó y una terrible angustia mental se apoderó de él,
y en su aflicción pidió a los llamados Cuáqueros que oraran
por él y que lo perdonaran por lo que había hecho.
A lo que respondieron que lo perdonaban, pero que tenía que pedirle perdón a Dios.
Pero su angustia seguía aumentando, y cuando los médicos ordenaron que lo sangraran,
dijo que ninguna medicina le haría bien, porque su enfermedad era otra cosa,
y que ningún hombre podía ayudarlo,
pues su día de visitación había pasado y no había esperanza de
misericordia de Dios para él. Los Amigos le dijeron que ellos deseaban,
si era la voluntad de Dios, que pudiera encontrar un "`lugar para el arrepentimiento.`"^
footnote:[Hebreos 12:17]
Pero cualquier palabra que se le dijera, animándolo a buscar paz y misericordia,
él repetía que su día de visitación había terminado y que no tenía fe para creer.
Permaneció alrededor de un mes en esta lamentable condición,
y murió sin ninguna señal visible de perdón;
pero el juicio de ello debe ser dejado a Dios.

[.centered]
=== Gilbert Latey y el Osbispo

En el año 1679, Gilbert Latey, mientras iba de camino a Londres desde Cornwall,
donde había ido a visitar su lugar natal, llegó a Exeter.
Allí consideró apropiado visitar al obispo,
cuya mesura y amabilidad se habían extendido de manera
general hacia los Amigos en su diócesis,
y quien le había hecho varios favores a Gilbert respecto
a los Amigos que sufrían en esas regiones.
El obispo lo recibió con gran amabilidad y abrazándolo expresó su bendición. Después,
lo llevó a una habitación privada y le dijo:
"`No todos deben saber cuánto afecto hay entre nosotros.`"
Y luego le preguntó a Gilbert qué vino debía darle,
a lo que él respondió que le había dado lo que era mejor.
"`Te ruego,`" dijo el obispo, "`¿qué quieres decir con eso?`"
Gilbert le respondió: "`Me has dado tu cariño que es mejor que el vino.`"
"`Entonces,`" dijo el obispo, "`si es así, te ruego que te sientes a mi lado, y,
si no es molestia,
dime hasta dónde has viajado o hasta dónde piensas viajar por esta
región.`" A lo cual Gilbert respondió hasta dónde había viajado,
y le contó sobre las averiguaciones que había hecho respecto a la condición de
sus amigos a lo largo y ancho de la diócesis mientras pasaba por el territorio,
cómo habían sido tratados en los tribunales eclesiásticos,
y sobre la moderación mostrada por los oficiales hacia los Amigos.
"`Bien,`" dijo el obispo, "`y estoy seguro de que no halagarás a nadie,
por lo tanto dime, ¿qué reputación tengo yo donde tú has estado?`"
Ante esto Gilbert respondió, que no tenía sino buenas noticias que dar;
después de lo cual el obispo le agradeció tanto por sus averiguaciones como por su informe.
Tras reconocer su amabilidad y favores, Gilbert se despidió poco después.

Como Gilbert Latey siempre tuvo acceso directo al obispo,
y también la libertad de dirigirse a él por carta cuando surgiera la ocasión,
en el año 1683 le escribió en nombre de sus Amigos.
La respuesta es digna de un obispo cristiano, y la inclusión, junto con lo anterior,
puede mostrar de manera evidente que,
en un período en que este reino parecía estar dividido
por el espíritu de partidismo y una amarga intolerancia,
aún podían encontrarse instancias, aunque raras,
incluso entre los personajes más prominentes de esa época,
de principios cristianos que impregnaban su conducta y conversación con sinceridad,
misericordia y caridad.

[.embedded-content-document.letter]
--

[.salutation]
Sr. Latey,

Yo habría confirmado recibo de su cordial carta,
pero esperé hasta que concluyeran nuestras sesiones de la corte,
para ver qué procedimientos se iban a realizar en contra de alguno de su persuasión;
y no he oído de ninguno.
No encuentro un caso reciente contra ellos en ninguno de mis tribunales,
pues he interrogado a mis oficiales al respecto.
Lo que los jueces de paz hayan hecho en sus reuniones mensuales, lo desconozco;
pero estoy seguro de que aquellos que viven tranquila y pacíficamente en la tierra,
no son perturbados por ninguna orden mía;
y creo que los jueces son suficientemente amables con quienes no los provocan.
Nunca fui, ni estaré, a favor de la persecución, sino que procuraré,
por cualquier medio cordial,
que quienes han errado sean conducidos al camino de la Verdad,
y que todos podamos disfrutar unos de otros en el cielo.
Ahora me encuentro algo indispuesto; escribir me resulta penoso.
Que Dios Todopoderoso te bendiga.

[.signed-section-closing]
Tu verdadero y cordial amigo,

[.signed-section-signature]
Thomas Exon

[.signed-section-context-close]
Exeter, 24 de Marzo, 1683

--

[.centered]
=== Popularidad

[.offset]
George Fox, hablando de sus viajes en América, dice:

[.embedded-content-document]
--

Fuimos a Narraganset, a unas veinte millas de Rhode Island,
y el gobernador +++[+++de Rhode Island]
fue con nosotros.
Tuvimos una reunión en casa de un juez,
donde los Amigos nunca habían tenido ninguna antes.
La reunión fue muy numerosa, pues, en general, llegó la gente del campo,
también personas de Connecticut y de lugares vecinos.
Había cuatro jueces de paz.
La mayor parte de estas personas nunca antes había escuchado a los Amigos; sin embargo,
fueron profundamente conmovidos, y hay entre ellos un gran deseo de la verdad.
De modo que, la reunión fue de gran provecho.
¡Bendito sea el Señor para siempre!

En otro lugar escuché que algunos de los magistrados decían entre ellos,
que si tuvieran suficiente dinero, me contratarían para ser su ministro.
Esto fue donde no nos comprendían lo suficiente, ni a nuestros principios.
Pero cuando lo supe, les dije que ya era tiempo de que me fuera;
porque si sus ojos estaban tan puestos en mí, o en cualquiera de nosotros,
no buscarían a su propio Maestro.
Porque esto, a saber, la contratación de ministros, había sido la ruina de muchos,
al impedirles incrementar sus propios talentos;
mientras que nuestra labor es llevar a cada uno a su Maestro en sí mismos.^
footnote:[1 Juan 2: 27]

--

[.offset]
A lo anterior, se puede añadir uno o dos extractos de una carta del mismo autor,
como sigue:

[.embedded-content-document]
--

En los días de los apóstoles, cuando algunos decían ser de Pablo y otros de Apolos,
y de otros, Pablo los juzgó como carnales;
y los exhortó y amonestó para que su fe no estuviera fundada en
los hombres ni en las palabras de la sabiduría de los hombres,
sino en el poder de Dios.^
footnote:[1 Corintios 2:5]
Él dijo que no conocería las palabras de ellos, sino el poder entre ellos;
porque el reino de Dios no consiste en palabras, sino en poder.^
footnote:[1 Corintios 4:19-20]
Así también debe ser ahora.
La fe de cada uno debe estar fundada en el poder de Dios, y no en los hombres,
ni deberían basarse los discursos en palabras elocuentes.
Porque hemos visto por experiencia,
que cuando comienzan a exaltar a los hombres y ponen su fe en ellos, aquellos,
que quieren que la fe de las personas se funde en ellos,
aman la popularidad y no dirigen la fe de las personas
a estar fundada en el poder de Dios.
Tales no predican a Cristo, sino a sí mismos.
No pueden exaltar a Cristo; y cuando caen,
arrastran tras sí a una gran multitud de personas.
Aquellos cuya fe descansa en los hombres, crearán sectas; de esa fe,
Cristo no es el autor; y si alguna vez lo fue,
se han desviado y han naufragado en cuanto a la fe.
Todos los que están en la verdadera fe, la cual está fundada en el poder de Dios,
los juzgarán como carnales,
y juzgarán esa parte carnal en ellos que dice ser de Pablo o de Apolos;
para que su fe esté en el poder de Dios, y para que puedan exaltar a Cristo,
el autor de la fe.

Por lo tanto, todos deben conocerse unos a otros en el Espíritu, la vida y el poder,
y poner sus ojos en Cristo; esto mantiene a todos en humildad.
Porque los ojos de todos deben ser puestos en Jesús,
y todo hombre y mujer justos deben vivir por su fe,^
footnote:[Hebreos 10: 38]
de la cual Cristo es el autor y consumador.
Mediante esta fe todo hombre puede ver a Dios, que es invisible; esta fe da la victoria.
Así, cuando la fe y la esperanza de cada uno están en el poder de Dios,
todos tienen unidad, victoria y acceso al trono de gracia de Dios;
en tal fe agradan a Dios.
Por medio de esta fe son salvos, obtienen buen testimonio,
y someten todos los montes que hay entre ellos y Dios.

--

[.centered]
=== Dos visitas en casa de Isaac Penington

[.embedded-content-document]
--

Durante la estancia de mi padre en Londres +++[+++dice Thomas Ellwood],
en la época de las guerras civiles,
entabló amistad con la señora Springett--quien en ese entonces era viuda,
y luego se casó con Isaac Penington, caballero--y para mantener esa relación,
a veces iba a visitarlos a su casa de campo, como en Datchet y en Causham,
cerca de Reading.
Y cuando mi padre se enteró de que ellos se habían mudado a su propiedad en Chalfont,
Buckinghamshire, como a quince millas de Crowell, fue un día a visitarlos,
y regresar por la noche, llevándome con él.

Cuando llegamos ahí nos sorprendió mucho:
primero oír y luego comprobar que se habían vuelto Cuáqueros;
un pueblo del cual no teníamos conocimiento, y un nombre que, hasta entonces,
apenas habíamos oído.

Un cambio tan grande--de su comportamiento espontáneo,
elegante y pomposo que anteriormente les habíamos visto,
a una seriedad tan estricta con la que nos recibieron en ese momento--nos
sorprendió bastante y defraudó nuestra expectativa de tener una visita
tan placentera como las que solíamos tener y nos habíamos prometido.
Y como había otros forasteros con ellos,
parientes de Isaac Penington que habían llegado esa mañana desde Londres a visitarlos,
mi padre no tuvo la oportunidad, mediante una conversación privada con ellos,
de entender la razón o motivo de ese cambio.

Por mi parte, busqué, y eventualmente hallé la manera de estar en compañía de su hija,
a quien encontré recogiendo flores en el jardín, acompañada de su criada,
que también era Cuáquera.
Pero cuando me dirigí a ella,
de mi manera acostumbrada con la intención de entablar
una conversación basándome en nuestra antigua relación,
aunque me trató de forma cortés, la seriedad de su mirada y comportamiento,
a pesar de lo joven que era, me infundieron tal temor,
que no me vi con suficiente dominio de mí mismo como
para buscar más conversación con ella.
Por lo tanto,
pidiéndole disculpas por mi atrevimiento al haberme entrometido en sus paseos privados,
me retiré, pero no sin algo de confusión mental.

Nos quedamos a cenar, la cual fue muy agradable y no careció de nada,
salvo de las risas y grata conversación,
que no pudimos tener ni con ellos ni entre nosotros mismos por causa de ellos;
porque la seriedad que estaba sobre sus espíritus y semblantes
detenía la ligereza que se habría levantado en nosotros.
Sin embargo, nos quedamos hasta que el resto del grupo se despidió de ellos,
y luego nosotros también regresamos a casa, no muy contentos de nuestro viaje,
pero sin saber qué reprochar en particular.

Sin embargo, esa visita tuvo un buen efecto sobre mi padre,
quien entonces era juez de paz,
porque lo predispuso a tener una opinión y una conducta más favorables
hacia ese pueblo cuando se cruzaran en su camino.

Un tiempo después de eso, mi padre,
habiendo oído más sobre el pueblo llamado Cuáqueros,
y deseando recibir información sobre sus principios,
hizo otra visita a Isaac Penington y a su esposa en su casa llamada Grange,
en Peter`'s Chalfont,
y me llevó a mí y a mis hermanas con él.

Fuimos allá en el décimo mes del año 1659,
donde nos recibieron muy amablemente y nos quedamos algunos días; al menos un día más,
porque mientras estábamos ahí se convocó una reunión
en un lugar que estaba como a una milla de la casa,
a la cual fuimos invitados y fuimos gustosos.
Se llevó a cabo en una casa de campo llamada The Grove,
que antes había sido la residencia de un noble y tenía un salón muy grande,
el cual las personas llenaron completamente.

A esa reunión asistió Edward Burrough, junto con otros predicadores,
como Thomas Curtis y James Nayler; pero en ese momento nadie habló salvo Edward Burrough.
Me tocó estar sentado en un taburete junto a él,
al lado de una mesa larga en la que él se había sentado,
y bebí sus palabras con gran anhelo; porque ellas no solo alcanzaron mi entendimiento,
sino que también calentaron mi corazón con un cierto fuego,
que hasta ese día nunca había sentido a través del ministerio de ningún hombre.
Cuando la reunión terminó, nuestros amigos nos llevaron de nuevo a su casa;
y después de la cena, siendo la puesta del sol muy tardía en aquella época del año,
llamaron a los sirvientes de la familia (que eran
Cuáqueros) y todos nos sentamos en silencio.
Pero no teníamos mucho tiempo sentados,
cuando Edward Burrough comenzó a hablar entre nosotros.
Y aunque no habló por mucho tiempo, lo que dijo tocó, según supongo,
el nervio religioso de mi padre, como dice el dicho.
Y él,
habiendo sido religioso desde joven (aunque no tenía
una estrecha unión con ninguna persuasión),
y valorándose a sí mismo por el conocimiento que estimaba
tener de las diferentes doctrinas de cada denominación,
pensó que en ese momento tenía una buena oportunidad para mostrar su conocimiento,
y entonces, comenzó a poner objeciones contra lo que había sido dicho.

El tema de la conversación era la gracia universal
y gratuita de Dios para con toda la humanidad.
A eso él se opuso con el principio calvinista de la predestinación particular y personal.
Pero en su intento de defender esa indefendible doctrina,
muy pronto se halló más perdido de lo que esperaba.
Edward Burrough no le dijo mucho al respecto,
aunque lo que dijo fue directo al grano y convincente.
Pero luego intervino James Nayler,
y manejó el tema con tanta perspicacia y evidente demostración,
que su razonamiento me pareció irresistible; y supongo que mi padre lo vio así,
lo que hizo que rápidamente estuviera dispuesto a dejar la conversación.
En cuanto a Edward Burrough, era un joven vivaz, con facilidad para hablar,
y podría haber sido, por todo lo que yo sabía en ese entonces, un erudito,
lo que hizo que admirara menos su forma de razonar.
Pero lo que salió de la boca de James Nayler tuvo mayor impacto sobre mí,
porque se veía como un simple y humilde hombre de campo,
con la apariencia de un agricultor o de un pastor.
Al ver que mi papá no había sido capaz de mantener la discusión a su favor,
ellos tampoco estuvieron dispuestos a llevarla en extremo al suyo; sino que,
tratándolo con suavidad y gentileza, después de un rato dejaron la conversación,
y luego nos retiramos a nuestras respectivas habitaciones.

La mañana siguiente nos preparamos para regresar a casa, a saber, mi padre,
mi hermana menor y yo;
porque mi hermana mayor se había ido antes en una diligencia a Londres.
Y cuando comenzamos a salir, después de habernos despedido de nuestros amigos,
ellos nos acompañaron a la puerta,
donde Edward Burrough nos habló unas pocas palabras a cada uno individualmente,
según el sentido que tenía de nuestras diferentes condiciones.
Y luego de que nos fuimos, cuando ellos habían vuelto a entrar,
los Penington le preguntaron qué pensaba de nosotros.
Él les respondió (como ellos me contaron después) de esta manera: "`En cuanto al anciano,
está establecido en sus opiniones; y la joven es superficial e indiferente;
pero el joven ha sido alcanzando, y le puede ir bien si no lo pierde.`"
Y sin duda, las palabras que me había hablado,
o más bien el Espíritu por medio del cual las había hablado,
se apoderó de mí tan fuertemente, que sentí que me invadieron la tristeza y la angustia,
aunque no entendía con claridad por qué estaba angustiado.
No sabía qué me afligía, pero sabía que era algo fuera de lo normal,
y mi corazón estaba muy pesado.
Me di cuenta de que no le sucedía lo mismo a mi padre, ni a mi hermana;
porque mientras cabalgaba detrás del coche, podía escucharlos conversar placenteramente.
Pero ellos no pudieron discernir lo que me estaba pasando, porque al ir a caballo,
me mantuve fuera de su vista.

--
