== Capítulo V

=== La Ley y el Evangelio

Una vez, una compañía de irlandeses llegó a Pall Mall cuando George Fox estaba ahí,
pero la reunión ya se había disuelto y George Fox se había retirado a su aposento.

Pero al oír a una de esas personas groseras--un coronel--decir
que él mataría a todos los Cuáqueros,
George Fox bajó y le dijo: "`La ley dice: '`Ojo por ojo, diente por diente`';
pero tú amenazas con matar a todos los Cuáqueros,
aunque ellos no te hayan hecho daño.`" Y añadió: "`Aquí te mostraré el evangelio:
Aquí está mi cabello, aquí está mi mejilla,
y aquí está mi hombro,`" volviéndose hacia él para que pudiera golpearlo si así lo deseaba.
Esto sorprendió tanto al coronel, que él y sus compañeros se quedaron asombrados,
y dijeron: "`Si este es tu principio, según dices ahora,
nunca hemos visto algo igual en nuestras vidas.`"
A lo cual George Fox dijo: "`Lo que soy en palabras, lo soy en la vida.`"
Entonces el coronel se comportó cordialmente;
aunque cierto embajador que había permanecido fuera, y luego había entrado,
dijo que este coronel irlandés era un hombre tan temerario,
que no se había atrevido a entrar con él, por temor a que hiciera un gran daño.
La Historia del Pueblo Llamado Cuáqueros por W. Sewel.

=== El Trompetista

Los dolorosos sufrimientos y la amarga persecución que tuvieron que padecer
quienes se unieron en los comienzos de nuestra Sociedad en la fe y práctica religiosas,
no necesitan ser desarrollados aquí. Nuestros historiadores,
especialmente Sewel y Gough, pueden ser consultados por quienes deseen
familiarizarse con la naturaleza y el alcance de estos hechos,
así como con la paciencia,
la fortaleza y la mansedumbre cristianas manifestadas por
nuestros precursores en la profesión de la fe.

Extraordinaria, sin embargo,
fue muchas veces la influencia de estos temperamentos
celestiales sobre aquellos que los contemplaban,
como se muestra en el ejemplo previo; ese apoyo y fortaleza sobrenaturales,
que recibían quienes eran fieles a Cristo su Señor,
a menudo alcanzaban y tocaban los corazones de sus opositores.
Magistrados en el estrado se mostraban favorables a quienes estaban a punto de condenar,
y adoptaban la misma conducta y creencia que antes había estado dispuestos a reprobar.
Los carceleros y otros reconocían y abrazan esas verdades que ellos habían despreciado.
Y no es de extrañar, si se considera,
que estos modelos de "`espíritu humilde y apacible`"^
footnote:[1 Pedro 3:4 RVG]
prescrito por el evangelio, habían sido, en muchas ocasiones,
miserables esclavos de sus propias inclinaciones y pasiones corruptas.
Algunos de ellos, además,
de esa naturaleza fiera y bulliciosa que no tolera la más mínima provocación;
pero que después, tan golpeados por los terrores del Señor por causa de sus pecados,
tan humillados bajo el poder de la cruz de Cristo,
llegaron a revestirse del pacífico e inofensivo espíritu del Cordero,
sobrellevando todos los ultrajes de sus enemigos con una mente tranquila,
y con un comportamiento amable y compasivo.
Tales hechos no se exponen con el fin de atribuir estos excelentes
"`frutos de justicia`" a una denominación o grupo en particular,
sino más bien para exaltar ese poder y gracia celestiales que,
mediante el único y gran Sacrificio por el pecado, han sido comprados para todos,
y de los cuales con toda certeza pueden participar, en una u otra medida,
todos los que estén dispuestos a recibirlos,
sea cual sea la condición en la que se encuentren,
o la dispensación por la que estén atravesando.
El relato que sigue es parecido al anterior,
y ayuda a reforzar las observaciones expuestas.

Un cierto trompetista, entrando en una reunión de Amigos,
comenzó a tocar su trompeta de manera insolente,
con el fin de ahogar la voz del que predicaba; esto, sin embargo,
tuvo el efecto contrario, y avivó más el celo del predicador,
de modo que continuó como si nada le estorbara.
Finalmente, el trompetista, para recobrar su aliento, se vio obligado a dejar de soplar,
pero gobernado aún por un espíritu maligno,
después de una breve pausa comenzó a tocar de nuevo; pero sin importar qué hiciera,
no pudo apartar al predicador de su discurso,
aunque impidió que el auditorio escuchara lo que se decía. De esta manera se cansó tanto,
que se vio obligado a descansar de nuevo para respirar, por lo que,
a pesar de su perversa voluntad, oyó lo que el predicador decía,
lo cual era tan penetrante que el trompetista quedó profundamente afectado,
y estallando en lágrimas, confesó su crimen y se convirtió en un verdadero penitente.

William Sewel

=== William Caton

William Caton fue un ejemplo vivo de la eficacia de la gracia divina,
y un eminente instrumento en la mano del Señor para promover
Su propia obra de reforma y justicia en la tierra.
Vivió en un período muy temprano de los anales de nuestra Sociedad;
y algunos extractos de su diligencia, celo y devoción en la causa a la que se unió,
pueden ser recordados para beneficio de la generación presente.
Cuando tenía unos catorce años, fue acogido por la familia del Juez Fell en Swarthmore,
en Lancashire.
Sin embargo, mucho tiempo antes de esto,
su corazón había sido visitado con las impresiones de la bondad divina,
bajo cuya influencia, mientras meditaba en las obras de Su Creador,
a menudo se sentía conmovido y embargado por la ternura,
y en ocasiones refrenado de los malos hábitos propios de los niños. Al cabo de un tiempo,
el testigo de Dios en él llegó a despertarse más plenamente,
por lo que sus pecados fueron puestos en orden delante de él. Y aunque al principio,
como una becerra indómita que no está acostumbrada al yugo, intentaba salirse de él,
y mediante una actitud despreocupada y desenfrenada apagaba el bien dentro de él;
el amor de Dios hacia él era tal,
que era perseguido con juicio cada vez que era sorprendido por el mal.
Algunas veces, en efecto,
se retiraba a un lugar apartado para esperar en el
Señor y meditar en Sus maravillosas obras,
y en esa práctica encontraba frecuentes refrescamientos para el alma.
La primera visita de George Fox a la familia Fell, en este momento,
parece haber sido la ocasión que abrió y amplió grandemente su perspectiva,
y que estableció su mente sobre la Roca de la verdadera religión, Jesucristo;
cuyo reino de gracia y verdad comenzó desde entonces a establecerse en su corazón,
y las facultades de su entendimiento, junto con las inclinaciones de su voluntad,
a ser en cierta medida sometidas y santificadas.
Sin embargo,
tuvo que atravesar muchos conflictos y experiencias antes de que pudiera
decirse que su alma había sido en cierta medida redimida de la tierra,
y liberada del espíritu terrenal,
"`hecha nueva en Cristo Jesús,`" y establecida en la fe y la santidad.
Durante ese tiempo,
habla de que sus estudios escolares se habían convertido en una carga, y de que,
hallándose afligido y abatido de espíritu,
era incapaz de terminar sus ensayos y versos en latín, etc.
Las gloriosas visitaciones de la bondad del Todopoderoso sobre él,
alrededor de los diecisiete años, fueron tales, que su espíritu se derritió,
y por decirlo así, se quebrantó bajo el sentido de ellas;
grandes fueron los gozos y las consolaciones de los que participó,
y muchas las preciosas promesas que le fueron reveladas y confirmadas.
La frescura del poder celestial que lo acompañaba,
y que también reposaba sobre la familia bajo cuyo techo residía;
la cercanía y el afecto que prevalecía entre ellos, los unos hacia los otros,
su celo y su fe, escribe él, eran mucho más de lo que podía describirse con palabras.
Las reuniones eran muy preciosas para ellos en aquellos días,
tanto que algunos solían pasar parte de la noche esperando en el Señor "`todos unánimes
juntos,`" a menudo después de que el resto de la familia se había ido a la cama.
El consolador y renovador beneficio que cosechaban era muy grande.
"`Porque,`" dice William Caton,
"`si habíamos sufrido alguna pérdida en nuestra condición espiritual durante el día,
estando fuera en nuestros trabajos o cosas similares,
entonces éramos en gran medida restaurados,
mediante el amor y la misericordia de nuestro Dios
que abundaban grandemente para con nosotros.`"
Tales tratos de gracia,
acompañados por la ayuda y cuidado instrumentales que recibió de George Fox,
así como de Margaret Fell y de otros, evidentemente no fueron en vano.
Los designios de la inescrutable Sabiduría con respecto a él,
no fueron perturbados ni retardados, sino que,
mediante la rendición y la confianza en la mano formadora del divino Obrero,
Su bendita obra siguió adelante, y como resultado fue formado un vaso honorable,
apto para el uso del Maestro,
llevando la inscripción "`SANTIDAD A JEHOVÁ.`" Un fiel y apto soldado,
que ya no estaba a su propia disposición,
sino que fue rápidamente llamado a un cargo prominente en el servicio de su Líder;
fuerza, valor y denuedo le fueron otorgados en cada instancia,
la preservación y la paz fueron su porción,
y el nombre de su Dios fue en verdad glorificado a través de él.
Cerca del año 1655, teniendo entonces no más de dieciocho años,
comenzó su labor como ministro de ese buen Espíritu que
fue "`derramado`" sobre él "`abundantemente por Jesucristo.`"^
footnote:[Tito 3:6]
Su diligencia en el deber de este sagrado oficio resulta difícil de creer;
recorriendo gran parte de este reino principalmente o por completo a pie,
a menudo en pleno invierno, y durante el tiempo más crudo de la persecución. Sin duda,
su predicación iba acompañada de su propia evidencia en los corazones de sus oyentes;
como él mismo escribe,
"`la palabra del Señor crecía poderosamente y muchos eran añadidos a la fe.`"
Como breve ilustración de una parte de sus labores
en este primer año de su compromiso público,
se mencionan algunos distritos o lugares que delimitaron sus viajes,
sin hacer referencia al trayecto intermedio.
De Swarthmore viajó a Norwich, de allí a Londres, Kent, Calais en Francia, Yarmouth,
Sunderland, Lancashire, Shields; de Flushing a Middleburg, Rotterdam, etc.
Luego a Yorkshire, por Durham hasta Lancashire, Berwick, Edinburgh, Glasgow, Stirling,
etc., y de regreso por Northumberland, Durham y Westmoreland hasta Swarthmore.
Algunas de esas visitas no fueron de corta duración, como podría suponerse.
Al referirse a un viaje posterior, menciona:
"`Me faltaría tiempo para describir con detalle el
extraordinario buen servicio que tuvimos,
a veces en casas del campanario,^
footnote:[Me parece necesario señalar que la palabra
"`iglesia`" que está en las Sagradas Escrituras,
nunca se ha aplicado a un templo externo o edificio,
sino más bien a un grupo de creyentes, ya sea en general o en particular.]
otras en calles y mercados,
etc.`" además de sus compromisos privados y públicos entre sus compañeros profesantes.
Pero cada año restante de su vida hasta su término,
estuvo quizás igualmente marcado por la presteza en cumplir con los encargos del Señor,
por ocuparse fielmente con ese don que le había sido encomendado,
y por la diligente atención al ministerio que había recibido en el Señor para cumplirlo.^
footnote:[Colosenses 4:17]
Tomando en consideración el propósito de estas páginas,
parece adecuado terminar el relato de William Caton con algunas observaciones
que él hizo en su diario sobre este importante tema del ministerio.
Como están vinculadas con su propia experiencia,
pueden ilustrar vívidamente para el entendimiento de algunos,
el estado de completa dependencia y vacío al que
deben ser llevados los ministros del evangelio,
antes de que el Señor les dé "`palabra y sabiduría,`"
y les sea abierto "`puerta para la palabra.`"^
footnote:[Lucas 21: 15, Colosenses 4:3]
Tuve muchas reuniones preciosas y numerosas en
el condado +++[+++dice William Caton refiriéndose a Kent],
y el Señor estuvo muy a mi lado, quien me proveyó abundantemente de Su palabra y poder;
tanto,
que en diversas ocasiones me quedaba admirando de la plenitud
que recibía de Él. Y no era sólo yo quien estaba admirado,
sino muchos más,
que al ver con el ojo de la razón mi tabernáculo terrenal u hombre exterior,
no esperaban gran cosa de mí, siendo entonces de apenas unos veinte años,
ni había sido muy activo en la religión hasta que fui convencido de la Verdad de Dios.
Con todo,
el Señor se complació en abrir en mí y por medio de mí muchas cosas celestiales,
para que pudiera comunicarlas a la multitud, que algunas veces era tan numerosa,
que estaba listo a decir dentro de mí:
"`¿De dónde conseguiré pan para satisfacer a estos?`"
Y cuando contemplaba mi propia debilidad e insuficiencia,
me sentía a punto de desfallecer;
pero cuando miraba solo al Señor y ponía mi confianza enteramente en Él,
me sentía fuerte y valiente.
Pues el Señor me había mostrado esto mediante Su eterna luz,
durante una época en que me lamentaba por mi propia debilidad y
gemía bajo el peso de la carga del servicio y la obra del Señor,
diciendo, o pensando dentro de mí:
¡Oh! tales y tales (refiriéndome a los más aptos y sabios
de los hermanos) están tan preparados y provistos,
que no necesitan preocuparse por el servicio al que sean llamados.
Pero en cuanto a mí, soy tan simple, soy tan débil,
y nunca tengo nada preparado de antemano, ni casi nunca sé,
al entrar en una reunión de cientos de personas, qué voy a decir, o si diré algo o nada.
Incluso cuando estaba lleno de esos y otros razonamientos similares,
el Señor me mostró, cómo a "`los que tenían mucho no le sobró,
ni le faltó al que tenía poco,`" tal como sucedió con los israelitas
de antaño. Porque los hermanos que eran sabios y eminentes,
que habían recibido mucho del Señor, he aquí que se les requería mucho más;
de modo que de todo lo que tenían, nada les sobraba,
sino lo que debían emplear en la obra y el servicio a Dios.
En cuanto a mí, que era tan pequeño ante mis propios ojos,
y tan vil y despreciable ante los ojos de otros, no tenía motivos para quejarme;
pues aunque a menudo no sabía qué iba a decir al entrar a una reunión;
aun en esos momentos, al Señor le placía darme su palabra tan abundantemente,
que por medio de Él me era posible hablar dos, o tres,
o en ocasiones hasta cuatro horas a la congregación, con poca o ninguna pausa.
Y muchas veces me sucedió que, así como no sabía lo que iba a decir antes de una reunión,
tampoco podía recordar después de la reunión lo que había hablado en ella.
Sin embargo, tenía abundancia y plenitud, aunque asistía a reuniones diariamente y,
no sólo eso, sino también por las noches.
El Señor me daba siempre una provisión fresca de
ese buen tesoro que provee cosas nuevas y cosas viejas.
Ahora,
estas cosas las cuento--+++[+++continúa William Caton--y el lector sin duda creerá su afirmación,
así como la del compilador de este relato,
cuyo objetivo es el mismo]--no para mi propia alabanza, más bien digo: "`No a mí,
no a mí, que no tengo sino lo que he recibido, sea la alabanza al Señor,
quien es el dador de toda buena dádiva y de todo don perfecto.`"
Puedo decir con verdad, que lo que recibí de Él, lo entregué a Su pueblo;
y me regocijé en el Señor, a pesar de mis grandes viajes y sufrimientos,
todos los cuales fueron fáciles de sobrellevar por medio de Él;
ni fueron demasiado para mí,
con todos los riesgos y peligros que atravesé por mar y por tierra,
comparados con el poder y la presencia del Todopoderoso,
que tan dulce y eminentemente me acompañó durante aquellos días.

=== William Bennit y la Joven Asesina

William Bennit, unos de los primeros y eminentes miembros de nuestra Sociedad,
estuvo preso por motivos de consciencia en la cárcel de Bury, en el año 1668.
Un día, se dirigió seriamente a una joven, que era una delincuente,
y le preguntó si a lo largo de su vida no había transgredido muchas veces su conciencia;
si no había sentido a menudo frenos secretos y reprensiones interiores,
y se había turbado en su mente debido al mal cometido.
Esto lo hizo de una manera tan convincente,
que ella no sólo asintió a lo que le había mostrado,
sino que su amonestación alcanzó tanto el corazón de la joven, que vio claramente,
que si no hubiera sido tan testaruda y desobediente a esas reprensiones interiores,
con toda probabilidad no habría llegado a una caída
tan miserable como la que padecía entonces.
Porque el hombre que no desea el conocimiento de los caminos de Dios y se aparta de Él,
queda desamparado y no puede guardarse del mal,
aun de aquel que antes habría aborrecido en grado sumo, y habría dicho con Hazael:
"`¿Acaso es tu siervo, un perro, para que haga tan enorme cosa?`"^
footnote:[2 Reyes 8:13 RVG]
La sana amonestación de W. Bennit obró de tal manera sobre la mente de la joven,
que ella,
que nunca había conversado con los Cuáqueros y era
completamente ignorante de la doctrina de ellos,
llegó a comprender que "`la gracia de Dios que trae
salvación`" era lo que ella había resistido a menudo,
y que esa gracia no la había abandonado del todo,
sino que en ese momento la estaba haciendo consciente de la grandeza de
su transgresión. Esta consideración pesó tan poderosamente sobre ella,
que de ser una pecadora muy grave, se convirtió en una verdadera penitente,
y con un corazón lleno de tristeza le clamaba al Señor que
se complaciera en no esconder Su rostro de ella.
Y continuando en este estado de humillación y sincero arrepentimiento,
y perseverando en la súplica, con el tiempo sintió una medida de alivio;
y finalmente alcanzó una segura esperanza de perdón
mediante la preciosa sangre del inmaculado Cordero,
que vino al mundo a salvar a los pecadores y llamarlos al arrepentimiento,
y que también murió por los pecados del mundo.
Ella dio pruebas manifiestas de este cambio en su juicio frente al juez Hale, quien,
habiendo oído de cuán arrepentida estaba, deseaba con ansias perdonarla,
e intencionalmente hizo que se insertaran en la acusación
las palabras "`voluntaria y deliberadamente,`" para que,
aprovechándose de eso,
pudiera negar el cargo y así anular la acusación. Pero cuando se le preguntó
según la forma "`culpable o no culpable,`" rápidamente contestó:
"`Culpable.`"
Esto asombró al juez,
quien le dijo que parecía que no había considerado debidamente lo que había dicho;
ya que no era fácil de creer que una persona como ella--que tal vez había tratado
bruscamente a su hijo--lo hubiera matado "`voluntaria y deliberadamente.`"
Aquí el juez le abrió una puerta trasera para evitarle la pena de muerte.
Pero en ese momento el temor de Dios había ganado tanto lugar en el corazón de ella,
que ninguna manipulación serviría, ninguna hoja de higuera podría servirle de cubierta,
porque ahora sabía, que eso habría sido añadir pecado al pecado;
'`cobijarse con cubierta, y no del Espíritu de Dios.`'^
footnote:[Isaías 30:1]
Por tanto ella le indicó de manera clara al tribunal,
que en verdad había cometido intencionalmente el malvado acto,
para ocultar así la vergüenza de haber dado a luz un niño fuera del matrimonio;
y que habiendo pecado tan gravemente y estando afectada entonces por el verdadero arrepentimiento,
por ningún medio podía excusarse,
sino que estaba dispuesta a sufrir el castigo que exigía la ley;
no podía sino reconocerse culpable,
pues de otra manera ¿cómo podría esperar el perdón de Dios.
Esta confesión libre y franca, pronunciada con un rostro serio,
afectó tanto al juez que las lágrimas le corrían por el rostro, y muy entristecido dijo:
"`Mujer, nunca me había topado con un caso como este.
Tal vez tú, que eres joven y hablas tan piadosamente,
como quien ha sido golpeada en el corazón por el arrepentimiento,
aún podrías hacer mucho bien en el mundo; pero ahora me obligas a que, ex officio,^
footnote:[Obligación bajo la que está alguien en virtud de su oficio.]
pronuncie la sentencia de muerte contra ti, ya que no admites ninguna excusa.`"
Manteniéndose firme en lo que había dicho, el juez pronunció la sentencia de muerte.
Y más tarde, cuando fue llevada al lugar de ejecución,
pronunció un conmovedor discurso al pueblo, exhortando a los espectadores,
especialmente a los jóvenes, a tener el temor de Dios ante sus ojos,
a atender a Sus secretas reprensiones contra el mal,
para no afligir ni resistir al buen Espíritu del Señor;
pues al no haber atendido ella misma esto a tiempo, la había hecho correr en el mal,
y así, continuando de maldad en maldad había llegado a este funesto fin.
Pero dado que había confiado firmemente en la infinita misericordia de Dios,
y creía verdaderamente que sus pecados, aunque rojos como la sangre,
habían sido lavados por la sangre pura de Cristo, su Redentor,
podía partir de esta vida con contentamiento.
De esta manera predicó en el patíbulo una doctrina
muy consonante con la de los llamados Cuáqueros,
y dio pruebas conmovedoras de que su alma inmortal estaba por entrar en el paraíso,
como la del ladrón en la cruz muchos siglos antes.

=== George Fox y Oliver Cromwell

George Fox, en el transcurso de sus viajes en la obra del ministerio, llegó a Drayton,
en Leicestershire, alrededor del año 1654.
Tras dejar su lugar natal, pasó por uno o dos pueblos,
pero no había llegado muy lejos cuando fue aprehendido por un grupo
de soldados a caballo y llevado ante el coronel Hacker.
En ese momento, corrían rumores de un complot contra Oliver Cromwell, de modo que,
aunque George Fox pudo justificarse lo suficiente en este aspecto,
como no se atrevía prometer hacer de su casa una prisión,
dejando de asistir a las reuniones religiosas,
fue enviado a Londres para ser presentado ante el Protector.
El Protector, al tener conocimiento de él, requirió que firmara un documento,
prometiendo no tomar armas contra él ni contra el gobierno actual.
G+++.+++ Fox lo hizo en un escrito,
en el que declara que él había sido enviado por Dios para dar testimonio
contra toda violencia y contra las obras de las tinieblas,
para volver a las personas de las tinieblas a la luz,
y llevarlos del motivo de la guerra y pelea al evangelio pacífico.
Después de un tiempo, el mensajero regresó y lo llevó a Whitehall.
Siendo conducido al aposento donde se hallaba el Protector, George Fox dijo:
"`Paz sea en esta casa,`" y le pidió que se mantuviera en
el temor de Dios para que pudiera recibir sabiduría de Él,
y por medio de ella pudiera ser ordenado y ordenar
todas las cosas bajo su mano para la gloria de Dios.
También conversó mucho con él acerca de religión,
y durante ese tiempo Cromwell se condujo muy moderadamente,
pero dijo que G. Fox y sus amigos disputaban con los ministros.
G+++.+++ Fox le dijo que eran ellos los que contendían con él y sus amigos;
pues él no podía sostener a tales ministros tal como eran, ni podía darles de comer,
viendo que no eran como Cristo lo había ordenado, sino que contra tales, los profetas,
Cristo y los Apóstoles declararon expresamente en contra de los codiciosos y avaros,
que predican por ganancia deshonesta, etc.
También dijo, que todos los cristianos tenía las Escrituras,
pero carecían del poder y del Espíritu de quienes las habían dado;
y que esa era la razón por la que ellos no estaban en comunión con el Hijo,
ni con el Padre, ni con las Escrituras, ni unos con otros.
Mientras hablaba de esta manera, Cromwell dijo varias veces: "`Muy bueno.`"
"`Es verdad.`"
G+++.+++ Fox intercambió más palabras con él, pero al ver que la gente entraba,
retrocedió un poco, y mientras se volvía,
Cromwell lo cogió por la mano y con lágrimas en sus ojos dijo: "`Ven de nuevo a mi casa,
porque si tú y yo pasáramos una hora juntos al día,
estaríamos más cerca el uno del otro;`" y añadió que no
le deseaba más mal del que deseaba a su propia alma.
A esto G. Fox replicó, que si él lo hacía, perjudicaría su propia alma;
y le pidió que le prestara atención a la voz de Dios
para que pudiera permanecer en Su consejo,
y obedecerlo; y que si lo hacía, eso lo guardaría de la dureza de corazón,
pero que si no escuchaba la voz de Dios, su corazón se endurecería.^
footnote:[Salmo 95:8]
Esto alcanzó al protector tanto, que dijo que era cierto.
Luego G. Fox salió, y el capitán Drury le dijo mientras lo seguía,
que el señor protector había dicho que quedaba en libertad y que podía ir donde quisiera.
Entonces fue llevado a un gran salón, donde los caballeros del protector iban a cenar.
George preguntó por qué había sido llevado ahí,
y le dijeron que lo había ordenado el protector, para que cenara con ellos.
Pero George, en su modo de hablar, les pidió que le dijeran al protector,
que él no comería un bocado de su pan, ni bebería un sorbo de su bebida.
Cuando Cromwell lo oyó, dijo:
"`Ahora veo que ha surgido y se ha levantado un pueblo que no puedo ganar con regalos,
ni honores, ni oficios, ni cargos;
pero con las otras sectas y pueblos sí puedo hacerlo.`"
En respuesta a eso le fue dicho,
que los Cuáqueros habían abandonado todo lo que era de ellos,
y que no era probable que buscaran tales cosas de él. . En Londres se acostumbra,
en verano, cuando se acerca la noche y los artesanos dejan de trabajar,
a que muchos hombres fornidos se reúnan en los campos
para probar su habilidad y su fuerza en la lucha;
y generalmente una multitud de personas se queda mirando en un círculo.
Sucedió entonces que Edward Burrough pasó por el lugar donde estaban luchando,
y de pie entre los espectadores vio cómo un sujeto fuerte
y hábil ya había arrojado al suelo a otros tres,
y estaba esperando a un cuarto campeón, si alguno se atrevía a entrar.
Finalmente, como nadie fue suficientemente audaz para intentarlo,
E+++.+++ Burrough entró en el espacio de pelea,
rodeado comúnmente por personas de todo tipo de condición;
y al mirar al luchador con un semblante serio, el hombre se sorprendió mucho,
porque en lugar de un antagonista brioso se encontró con un joven sobrio y solemne.
Todos estaban atónitos ante esta escena,
esperando ansiosamente saber cuál sería el resultado de este combate.
Sin embargo, E. Burrough se proponía una pelea completamente diferente.
Pues después de haber peleado contra la maldad espiritual
que una vez había prevalecido sobre él,
y haber vencido en alguna medida por la gracia de Dios,
ahora se esforzaba por pelear contra ella en otros,
y por volverlos de la maldad de sus caminos.
Con esta intención les comenzó a hablar muy seriamente a los espectadores,
y alcanzó los corazones con un poder tan penetrante,
que fue escuchado por esta variada multitud con no menos atención que admiración,
pues su discurso procuraba volverlos de las tinieblas a la luz,
y del poder de Satanás a Dios.
Para lograrlo luchó con palabras convincentes,
mostrando que Dios no se había quedado sin testimonio,
sino que le había dado al hombre una medida de Su gracia,
y alumbrado a todos con la luz de Cristo.
De esta forma predicó con celo, y aunque muchos consideraron eso una rareza,
tuvo tal efecto, que algunos fueron convencidos de la Verdad.
Pues Burrough era una quebrantador de corazones de piedra, y por eso,
no fue injustamente llamado, por cierto autor,
"`hijo del trueno,`" aunque a su debido tiempo,
también pronunciaba palabras de consuelo a los que
tenían un corazón quebrantado y un espíritu contrito.
William Sewel

=== El Campeón de Lucha

En Londres se acostumbra, en verano,
cuando se acerca la noche y los artesanos dejan de trabajar,
a que muchos hombres fornidos se reúnan en los campos
para probar su habilidad y su fuerza en la lucha;
y generalmente una multitud de personas se queda mirando en un círculo.
Sucedió entonces que Edward Burrough pasó por el lugar donde estaban luchando,
y de pie entre los espectadores vio cómo un sujeto fuerte
y hábil ya había arrojado al suelo a otros tres,
y estaba esperando a un cuarto campeón, si alguno se atrevía a entrar.
Finalmente, como nadie fue suficientemente audaz para intentarlo,
E+++.+++ Burrough entró en el espacio de pelea,
rodeado comúnmente por personas de todo tipo de condición;
y al mirar al luchador con un semblante serio, el hombre se sorprendió mucho,
porque en lugar de un antagonista brioso se encontró con un joven sobrio y solemne.
Todos estaban atónitos ante esta escena,
esperando ansiosamente saber cuál sería el resultado de este combate.
Sin embargo, E. Burrough se proponía una pelea completamente diferente.
Pues después de haber peleado contra la maldad espiritual
que una vez había prevalecido sobre él,
y haber vencido en alguna medida por la gracia de Dios,
ahora se esforzaba por pelear contra ella en otros,
y por volverlos de la maldad de sus caminos.
Con esta intención les comenzó a hablar muy seriamente a los espectadores,
y alcanzó los corazones con un poder tan penetrante,
que fue escuchado por esta variada multitud con no menos atención que admiración,
pues su discurso procuraba volverlos de las tinieblas a la luz,
y del poder de Satanás a Dios.
Para lograrlo luchó con palabras convincentes,
mostrando que Dios no se había quedado sin testimonio,
sino que le había dado al hombre una medida de Su gracia,
y alumbrado a todos con la luz de Cristo.
De esta forma predicó con celo, y aunque muchos consideraron eso una rareza,
tuvo tal efecto, que algunos fueron convencidos de la Verdad.
Pues Burrough era una quebrantador de corazones de piedra, y por eso,
no fue injustamente llamado, por cierto autor,
"`hijo del trueno,`" aunque a su debido tiempo,
también pronunciaba palabras de consuelo a los que
tenían un corazón quebrantado y un espíritu contrito.
William Sewel

=== Gilbert Latey y el lord D`'Aubigny

Gilbert Latey, oriundo de Cornwall, se formó allí en el oficio de sastre,
el cual continuó ejerciendo al establecerse en Londres.
Llevaba una vida y conducta sobrias, y al sentir respiraciones del alma por el Señor,
buscó a aquellos que eran los más celosos en ese tiempo.
El Señor, al mirar la integridad de su corazón,
lo prosperó de tal manera que alcanzó gran reputación en el mundo;
teniendo un buen negocio en su oficio,
y siendo empleado y respetado por muchas personas de la
más alta posición y alcurnia entonces en el reino.
Sin embargo, en medio de todos estos goces externos,
su mente y sus deseos seguían puestos en hallar paz con el Señor,
en el conocimiento de Su Verdad pura y forma de adoración.
Estando en esta condición de búsqueda,
siguió a quienes le parecían los más puros en sus profesiones,
pero sin mucha satisfacción;
hasta que se encontró con Edward Burrough en una reunión en Londres;
y al ser dirigido por este fiel ministro a la única Guía a la paz verdadera,
sin consultar con carne ni sangre,
se rindió a la "`visión celestial,`" tomando la cruz y menospreciando el oprobio,
considerando todas las cosas como escoria y basura, para "`ganar a Cristo,
y ser hallado en Él.`"^
footnote:[Filipenses 3: 8-9]
No había pasado mucho tiempo alistado bajo el estandarte del Señor,
profesando y confesando Su bendita Verdad,
cuando le plació al Señor poner sobre él una dura prueba,
como cortar la mano derecha o sacar el ojo derecho.
Pues, teniendo un gran negocio en el mundo,
y por ello relacionado con personas de alta posición y alcurnia,
que deseaban que sus vestiduras fueran adornadas
con gran gasto y exceso de encajes y lazos,
llegó a estar bajo una consciente inquietud que lo
llevó a rechazar este aspecto superfluo de su oficio,
y también a no permitir que sus criados pusieran
tales adornos en los atuendos de los grandes.
Por causa de esto, algunos decían que había enloquecido, o que pronto estaría;
sus clientes adinerados, que vestían a la moda, en general lo abandonaron,
y su negocio decayó tanto, que teniendo muchos criados, se vio obligado a despedirlos.
No sabía si él mismo, que había tenido un negocio tan próspero,
acabaría siendo el siervo de algún otro del oficio,
y trabajar como jornalero para ganarse su pan.
Esta prueba fue muy grande,
pues llegó a ser despreciado por los hijos de su propia madre y, por así decirlo,
desterrado de la casa de su padre.
Sin embargo esperando con paciencia el tiempo del Señor, fue sostenido durante la prueba,
y fortalecido para preferir dejarlo todo antes que perder su paz con su Hacedor.
Así aquel que nunca abandona a los que confían en Él y le son fieles,
sostuvo su espíritu con alegre rendición bajo todos sus ejercicios,
y no solo proveyó para todas sus necesidades,
sino que también lo capacitó para suplir las necesidades de otros;
lo cual hizo de varias maneras,
especialmente mediante su influencia entre las personas
de rango y alta posición en el mundo.
Cabe agregar que,
poco tiempo después de haber rendido sacrificio al Señor en obediencia a Su voluntad,
como se mencionó anteriormente,
el Señor lo ordenó como ministro de esas preciosas verdades y consuelos,
a las cuales había mostrado tan grande estima y valor.
Este mismo hombre, piadoso y útil,
comenzó desde temprano a usar su influencia y relaciones
con personas distinguidas para el beneficio de otros,
especialmente de aquellos de la misma "`familia de la fe;`" para quienes
procuraba hallar alivio ante los grandes sufrimientos que les tocaba padecer.
En una ocasión, consideró presentarse ante el lord D`'Aubigny, quien,
con la ascensión de Charles II,
llegó a Inglaterra con la madre de la reina y era su "`gran limosnero.`"^
footnote:[Gran limosnero:
Cargo oficial en la corte real encargado de distribuir limosnas
y asistencia a los necesitados en nombre del monarca.
Su función combinaba autoridad,
representación de la corona y responsabilidad sobre la caridad oficial.]
Este lord tenía gran influencia y poder en la isla de Malta,
donde dos Amigas habían sido confinadas en la prisión de la Inquisición,
y tratadas con crueldad y dureza por testificar del evangelio de la gracia de Dios,
y advertir a las personas que se volvieran al Señor. Gilbert obtuvo acceso a él,
y halló que era un hombre de buen carácter; y aunque era un sacerdote ordenado,
y los Amigos durante esa época eran casi en todas partes difamados y maltratados,
fue muy amable y abierto en su trato con Gilbert; y solía razonar con él,
como Félix con Pablo,
sobre los principios de la verdad y el camino del Señor. . En una ocasión,
conversando con Gilbert, el lord D`'Aubigny dijo:
"`No importa cuánto tiempo hable contigo, tú me hablarás del Espíritu de Dios,
de la gracia de Dios, de Sus obras y operaciones,
y del amor de Dios del cual ustedes han sido hechos testigos mediante Jesucristo,
lo cual considero que, en cierta medida, puede ser verdadero; sin embargo,
¿no crees que es bueno tener algo externo que represente eso que tanto aman?`"
A lo que Gilbert respondió que la Sustancia de todas las cosas había llegado,
"`Cristo en nosotros, la esperanza de gloria;`" y que todos los tipos,
representaciones y sombras externos debían llegar
a su fin y ser absorbidos en nuestro bendito Señor,
quien dijo a sus discípulos que era necesario que él se fuera, porque: "`Si no me fuera,
el Consolador no vendría a vosotros; mas si me fuere,
os lo enviaré;`" y "`cuando el Espíritu de verdad venga,
Él os guiará a toda verdad;`" y también dijo que Aquel que estaba +++[+++entonces]
con ellos, estaría en ellos.
De modo que, al ser todo esto experimentado,
ya no se necesitaba nada externo que lo representara o que los hiciera recordar, pues Él,
al estar tan cerca del hombre y de la mujer, era el recordatorio diario de los santos.
Después de esto, se separaron;
pero Gilbert solía visitarlo y le recordaba que mostrara compasión
a los Amigos que sufrían bajo confinamiento por causa de consciencia,
muy lejos de sus amigos y de su tierra natal.
En otra ocasión, al ir a visitarlo, le pidió a Gilbert que lo siguiera;
y lo condujo a la capilla de la reina,
donde viendo Gilbert a las personas sobre sus rodillas
y las candelas encendidas sobre el altar,
se detuvo y le preguntó al lord D`'Aubigny qué pretendía al pedirle entrar ahí;
"`porque,`" dijo: "`sabes que no puedo inclinarme ante nada.`"
A lo que él respondió: "`Sígueme, y nadie te hará daño o se meterá contigo.`"
Entonces, Gilbert lo siguió a través de la capilla hasta una habitación detrás del altar,
donde estaba otro de los sacerdotes de la reina; y habiendo ahí algunos altares menores,
el lord D`'Aubigny le dijo a Gilbert: "`Nunca me has visto con mi hábito sacerdotal,
pero ahora lo harás.`" Y mientras se preparaba,
el poder del Señor obró de tal manera en Gilbert,
que subió a un lugar que llamaban altar privado,
y la palabra del Señor vino a él para predicarles.
Entre muchas declaraciones, dijo:
"`Nosotros tenemos un altar del cual no tienen derecho a comer.`"
Entonces el sacerdote de la reina preguntó: "`¿De qué altar hablas?`"
Gilbert respondió:
"`El altar del que hablo es aquel en el que los santos
elevan sus oraciones al Dios viviente.`"^
footnote:[Ver Apocalipsis 8:4]
Entonces, el sacerdote respondió: "`Amigo,
no hay estado más alto alcanzable que del que hablas;`" y así se despidieron.

=== Persecución en Bristol en 1682

Está registrado en la historia de nuestra sociedad religiosa una lúgubre
escena de la persecución que se abrió en Bristol en el año 1682;
cuyos diversos pormenores, aunque no puedan detallarse aquí,
quizás puedan ser aludidos brevemente,
en particular por uno o dos incidentes relacionados con ellos.
Las reuniones de los Amigos eran gravemente interrumpidas, sus casas allanadas,
y se cometían casi todo tipo de actos de violencia y abuso,
principalmente por instigación de un cruel alguacil.
Es cierto que, en aquel entonces,
las reuniones de otros disidentes protestantes eran también perturbadas;
pero parece que no eran tan persistentes en su testimonio religioso, y por ello,
no eran tan repudiados con los insolentes ataques, a los que este pueblo,
debido a su constancia y su negativa a resistir se veían sujetos.
A los personajes más viles se les permitía y se les animaba a cometer
toda clase de "`desenfreno de disolución,`" sin distinción de sexo,
edad o condición. Incluso hombres y mujeres ancianos
eran arrastrados a prisión con violencia y golpes,
y los niños pequeños eran golpeados en la cabeza hasta quedar aturdidos,
y luego llevados a la prisión de Bridewell,
y aterrorizados ante la posibilidad de ser azotados,
a menos que prometieran no asistir más a las reuniones.
Pero el odio y las amenazas que se utilizaron, incluso contra esta clase de sufrientes,
no lograron doblegar su constancia.
Apenas quedó una piedra sin mover en sus intentos de afligir a
los Amigos y disuadirlos de reunirse para adorar a su Hacedor.
Estos disturbios continuaron hasta que casi todos los hombres fueron llevados a prisión;
allí, sin embargo, sus persecuciones no cesaron,
sino que se incrementaron considerablemente debido a las privaciones y malos tratos.
Estaban tan hacinados,
que apenas había suficiente espacio para que pudieran acostarse por la noche en el suelo;
y en otros aspectos, su salud y sus vidas estaban en tal peligro,
que cuatro médicos de Bristol consideraron necesario emitir un certificado al respecto.
Tras esto,
las reuniones religiosas de los Amigos de Bristol
continuaron celebrándose principalmente por mujeres,
quienes también fueron aprehendidas,
hasta que finalmente pocos o ninguno salvo niños que permanecían
con los sirvientes en las casas de sus padres,
quedaron libres.
Es muy notable, sin embargo, que los niños antes mencionados, menores de dieciséis,
llevaran a cabo ahora lo que a sus padres no podían--se reunían para la adoración divina,
y permanecían fieles sin desmayar, a pesar de todos los insultos de una chusma malvada,
de la que sufrieron en gran medida.
Diecinueve de ellos fueron llevados a la Casa de
Corrección y permanecieron allí por un tiempo,
aunque no estaban dentro del alcance de la ley;
y cuando se les amenazaba con azotarles si volvían a la reunión, tal era su celo que,
menospreciando todo reproche y abuso, permanecieron firmes en su deber.
Esta persecución duró hasta el año siguiente,
al igual que en muchos otros lugares de la nación por la misma época.
Pero el ejemplo anterior de los sufrimientos de esta Sociedad en los
primeros tiempos no debe considerarse de ningún modo como un caso extremo.
Aquellos que lean los registros de sus sufrimientos--muchos de los cuales
aparecen en su historia o en las memorias de individuos entre ellos--serán
fácilmente convencidos de la veracidad de lo escrito.
La narración anterior concluirá con un relato sobre la muerte del carcelero,
quien fue el principal instrumento de crueldad hacia los sufrientes luego de ser encarcelados.
Algunos de los prisioneros habrían trabajado de buena
gana en la prisión para ganarse algo para su sustento,
pero él no lo permitió. Otros prisioneros se enfermaron de la fiebre manchada,^
footnote:[La fiebre manchada es una enfermedad bacteriana
que se propaga mediante las picaduras de piojos,
pulgas y garrapatas infectados.]
y algunos murieron a causa de ella; con todo,
nada de esto suavizó el corazón endurecido del carcelero.
Finalmente sufrió un golpe muy duro,
porque se enfermó y una terrible angustia mental se apoderó de él,
y en su aflicción pidió a los llamados Cuáqueros que oraran
por él y que lo perdonaran por lo que había hecho.
A lo que respondieron que lo perdonaban, pero que tenía que pedirle perdón a Dios.
Pero su angustia seguía aumentando, y cuando los médicos ordenaron que lo sangraran,
dijo que ninguna medicina le haría bien, porque su enfermedad era otra cosa,
y que ningún hombre podía ayudarlo,
pues su día de visitación había pasado y no había esperanza de
misericordia de Dios para él. Los Amigos le dijeron que ellos deseaban,
si era la voluntad de Dios, que pudiera encontrar un "`lugar para el arrepentimiento.`"^
footnote:[Hebreos 12:17]
Pero cualquier palabra que se le dijera, animándolo a buscar paz y misericordia,
él repetía que su día de visitación había terminado y que no tenía fe para creer.
Permaneció alrededor de un mes en esta lamentable condición,
y murió sin ninguna señal visible de perdón;
pero el juicio de ello debe ser dejado a Dios.

=== Gilbert Latey y el Osbispo

En el año 1679, Gilbert Latey, mientras iba de camino a Londres desde Cornwall,
donde había ido a visitar su lugar natal, llegó a Exeter.
Allí consideró apropiado visitar al obispo,
cuya mesura y amabilidad se habían extendido de manera
general hacia los Amigos en su diócesis,
y quien le había hecho varios favores a Gilbert respecto
a los Amigos que sufrían en esas regiones.
El obispo lo recibió con gran amabilidad y abrazándolo expresó su bendición. Después,
lo llevó a una habitación privada y le dijo:
"`No todos deben saber cuánto afecto hay entre nosotros.`"
Y luego le preguntó a Gilbert qué vino debía darle,
a lo que él respondió que le había dado lo que era mejor.
"`Te ruego,`" dijo el obispo, "`¿qué quieres decir con eso?`"
Gilbert le respondió: "`Me has dado tu cariño que es mejor que el vino.`"
"`Entonces,`" dijo el obispo, "`si es así, te ruego que te sientes a mi lado, y,
si no es molestia,
dime hasta dónde has viajado o hasta dónde piensas viajar por esta
región.`" A lo cual Gilbert respondió hasta dónde había viajado,
y le contó sobre las averiguaciones que había hecho respecto a la condición de
sus amigos a lo largo y ancho de la diócesis mientras pasaba por el territorio,
cómo habían sido tratados en los tribunales eclesiásticos,
y sobre la moderación mostrada por los oficiales hacia los Amigos.
"`Bien,`" dijo el obispo, "`y estoy seguro de que no halagarás a nadie,
por lo tanto dime, ¿qué reputación tengo yo donde tú has estado?`"
Ante esto Gilbert respondió, que no tenía sino buenas noticias que dar;
después de lo cual el obispo le agradeció tanto por sus averiguaciones como por su informe.
Tras reconocer su amabilidad y favores, Gilbert se despidió poco después.
Como Gilbert Latey siempre tuvo acceso directo al obispo,
y también la libertad de dirigirse a él por carta cuando surgiera la ocasión,
en el año 1683 le escribió en nombre de sus Amigos.
La respuesta es digna de un obispo cristiano, y la inclusión, junto con lo anterior,
puede mostrar de manera evidente que,
en un período en que este reino parecía estar dividido
por el espíritu de partidismo y una amarga intolerancia,
aún podían encontrarse instancias, aunque raras,
incluso entre los personajes más prominentes de esa época,
de principios cristianos que impregnaban su conducta y conversación con sinceridad,
misericordia y caridad.
Sr. Latey, . Yo habría confirmado recibo de su cordial carta,
pero esperé hasta que concluyeran nuestras sesiones de la corte,
para ver qué procedimientos se iban a realizar en contra de alguno de su persuasión;
y no he oído de ninguno.
No encuentro un caso reciente contra ellos en ninguno de mis tribunales,
pues he interrogado a mis oficiales al respecto.
Lo que los jueces de paz hayan hecho en sus reuniones mensuales, lo desconozco;
pero estoy seguro de que aquellos que viven tranquila y pacíficamente en la tierra,
no son perturbados por ninguna orden mía;
y creo que los jueces son suficientemente amables con quienes no los provocan.
Nunca fui, ni estaré, a favor de la persecución, sino que procuraré,
por cualquier medio cordial,
que quienes han errado sean conducidos al camino de la Verdad,
y que todos podamos disfrutar unos de otros en el cielo.
Ahora me encuentro algo indispuesto; escribir me resulta penoso.
Que Dios Todopoderoso te bendiga.
Tu verdadero y cordial amigo,
Thomas Exon
Exeter, 24 de Marzo, 1683
George Fox, hablando de sus viajes en América, dice:
Fuimos a Narraganset, a unas veinte millas de Rhode Island,
y el gobernador +++[+++de Rhode Island]
fue con nosotros.
Tuvimos una reunión en casa de un juez,
donde los Amigos nunca habían tenido ninguna antes.
La reunión fue muy numerosa, pues, en general, llegó la gente del campo,
también personas de Connecticut y de lugares vecinos.
Había cuatro jueces de paz.
La mayor parte de estas personas nunca antes había escuchado a los Amigos; sin embargo,
fueron profundamente conmovidos, y hay entre ellos un gran deseo de la verdad.
De modo que, la reunión fue de gran provecho.
¡Bendito sea el Señor para siempre!
En otro lugar escuché que algunos de los magistrados decían entre ellos,
que si tuvieran suficiente dinero, me contratarían para ser su ministro.
Esto fue donde no nos comprendían lo suficiente, ni a nuestros principios.
Pero cuando lo supe, les dije que ya era tiempo de que me fuera;
porque si sus ojos estaban tan puestos en mí, o en cualquiera de nosotros,
no buscarían a su propio Maestro.
Porque esto, a saber, la contratación de ministros, había sido la ruina de muchos,
al impedirles incrementar sus propios talentos;
mientras que nuestra labor es llevar a cada uno a su Maestro en sí mismos.^
footnote:[1 Juan 2: 27]
A lo anterior, se puede añadir uno o dos extractos de una carta del mismo autor,
como sigue:
En los días de los apóstoles, cuando algunos decían ser de Pablo y otros de Apolos,
y de otros, Pablo los juzgó como carnales;
y los exhortó y amonestó para que su fe no estuviera fundada en
los hombres ni en las palabras de la sabiduría de los hombres,
sino en el poder de Dios.^
footnote:[1 Corintios 2:5]
Él dijo que no conocería las palabras de ellos, sino el poder entre ellos;
porque el reino de Dios no consiste en palabras, sino en poder.^
footnote:[1 Corintios 4:19-20]
Así también debe ser ahora.
La fe de cada uno debe estar fundada en el poder de Dios, y no en los hombres,
ni deberían basarse los discursos en palabras elocuentes.
Porque hemos visto por experiencia,
que cuando comienzan a exaltar a los hombres y ponen su fe en ellos, aquellos,
que quieren que la fe de las personas se funde en ellos,
aman la popularidad y no dirigen la fe de las personas
a estar fundada en el poder de Dios.
Tales no predican a Cristo, sino a sí mismos.
No pueden exaltar a Cristo; y cuando caen,
arrastran tras sí a una gran multitud de personas.
Aquellos cuya fe descansa en los hombres, crearán sectas; de esa fe,
Cristo no es el autor; y si alguna vez lo fue,
se han desviado y han naufragado en cuanto a la fe.
Todos los que están en la verdadera fe, la cual está fundada en el poder de Dios,
los juzgarán como carnales,
y juzgarán esa parte carnal en ellos que dice ser de Pablo o de Apolos;
para que su fe esté en el poder de Dios, y para que puedan exaltar a Cristo,
el autor de la fe.
Por lo tanto, todos deben conocerse unos a otros en el Espíritu, la vida y el poder,
y poner sus ojos en Cristo; esto mantiene a todos en humildad.
Porque los ojos de todos deben ser puestos en Jesús,
y todo hombre y mujer justos deben vivir por su fe,^
footnote:[Hebreos 10: 38]de la cual Cristo es el autor y consumador.
Mediante esta fe todo hombre puede ver a Dios, que es invisible; esta fe da la victoria.
Así, cuando la fe y la esperanza de cada uno están en el poder de Dios,
todos tienen unidad, victoria y acceso al trono de gracia de Dios;
en tal fe agradan a Dios.
Por medio de esta fe son salvos, obtienen buen testimonio,
y someten todos los montes que hay entre ellos y Dios.
Durante la estancia de mi padre en Londres +++[+++dice Thomas Ellwood],
en la época de las guerras civiles,
entabló amistad con la señora Springett--quien en ese entonces era viuda,
y luego se casó con Isaac Penington, caballero--y para mantener esa relación,
a veces iba a visitarlos a su casa de campo, como en Datchet y en Causham,
cerca de Reading.
Y cuando mi padre se enteró de que ellos se habían mudado a su propiedad en Chalfont,
Buckinghamshire, como a quince millas de Crowell, fue un día a visitarlos,
y regresar por la noche, llevándome con él.
Cuando llegamos ahí nos sorprendió mucho:
primero oír y luego comprobar que se habían vuelto Cuáqueros;
un pueblo del cual no teníamos conocimiento, y un nombre que, hasta entonces,
apenas habíamos oído.
Un cambio tan grande--de su comportamiento espontáneo,
elegante y pomposo que anteriormente les habíamos visto,
a una seriedad tan estricta con la que nos recibieron en ese momento--nos
sorprendió bastante y defraudó nuestra expectativa de tener una visita
tan placentera como las que solíamos tener y nos habíamos prometido.
Y como había otros forasteros con ellos,
parientes de Isaac Penington que habían llegado esa mañana desde Londres a visitarlos,
mi padre no tuvo la oportunidad, mediante una conversación privada con ellos,
de entender la razón o motivo de ese cambio.
Por mi parte, busqué, y eventualmente hallé la manera de estar en compañía de su hija,
a quien encontré recogiendo flores en el jardín, acompañada de su criada,
que también era Cuáquera.
Pero cuando me dirigí a ella,
de mi manera acostumbrada con la intención de entablar
una conversación basándome en nuestra antigua relación,
aunque me trató de forma cortés, la seriedad de su mirada y comportamiento,
a pesar de lo joven que era, me infundieron tal temor,
que no me vi con suficiente dominio de mí mismo como
para buscar más conversación con ella.
Por lo tanto,
pidiéndole disculpas por mi atrevimiento al haberme entrometido en sus paseos privados,
me retiré, pero no sin algo de confusión mental.
Nos quedamos a cenar, la cual fue muy agradable y no careció de nada,
salvo de las risas y grata conversación,
que no pudimos tener ni con ellos ni entre nosotros mismos por causa de ellos;
porque la seriedad que estaba sobre sus espíritus y semblantes
detenía la ligereza que se habría levantado en nosotros.
Sin embargo, nos quedamos hasta que el resto del grupo se despidió de ellos,
y luego nosotros también regresamos a casa, no muy contentos de nuestro viaje,
pero sin saber qué reprochar en particular.
Sin embargo, esa visita tuvo un buen efecto sobre mi padre,
quien entonces era juez de paz,
porque lo predispuso a tener una opinión y una conducta más favorables
hacia ese pueblo cuando se cruzaran en su camino.
Un tiempo después de eso, mi padre,
habiendo oído más sobre el pueblo llamado Cuáqueros,
y deseando recibir información sobre sus principios,
hizo otra visita a Isaac Penington y a su esposa en su casa llamada Grange,
en Peter`'s Chalfont,
y me llevó a mí y a mis hermanas con él. . Fuimos allá en el décimo mes del año 1659,
donde nos recibieron muy amablemente y nos quedamos algunos días; al menos un día más,
porque mientras estábamos ahí se convocó una reunión
en un lugar que estaba como a una milla de la casa,
a la cual fuimos invitados y fuimos gustosos.
Se llevó a cabo en una casa de campo llamada The Grove,
que antes había sido la residencia de un noble y tenía un salón muy grande,
el cual las personas llenaron completamente.
A esa reunión asistió Edward Burrough, junto con otros predicadores,
como Thomas Curtis y James Nayler; pero en ese momento nadie habló salvo Edward Burrough.
Me tocó estar sentado en un taburete junto a él,
al lado de una mesa larga en la que él se había sentado,
y bebí sus palabras con gran anhelo; porque ellas no solo alcanzaron mi entendimiento,
sino que también calentaron mi corazón con un cierto fuego,
que hasta ese día nunca había sentido a través del ministerio de ningún hombre.
Cuando la reunión terminó, nuestros amigos nos llevaron de nuevo a su casa;
y después de la cena, siendo la puesta del sol muy tardía en aquella época del año,
llamaron a los sirvientes de la familia (que eran
Cuáqueros) y todos nos sentamos en silencio.
Pero no teníamos mucho tiempo sentados,
cuando Edward Burrough comenzó a hablar entre nosotros.
Y aunque no habló por mucho tiempo, lo que dijo tocó, según supongo,
el nervio religioso de mi padre, como dice el dicho.
Y él,
habiendo sido religioso desde joven (aunque no tenía
una estrecha unión con ninguna persuasión),
y valorándose a sí mismo por el conocimiento que estimaba
tener de las diferentes doctrinas de cada denominación,
pensó que en ese momento tenía una buena oportunidad para mostrar su conocimiento,
y entonces, comenzó a poner objeciones contra lo que había sido dicho.
El tema de la conversación era la gracia universal
y gratuita de Dios para con toda la humanidad.
A eso él se opuso con el principio calvinista de la predestinación particular y personal.
Pero en su intento de defender esa indefendible doctrina,
muy pronto se halló más perdido de lo que esperaba.
Edward Burrough no le dijo mucho al respecto,
aunque lo que dijo fue directo al grano y convincente.
Pero luego intervino James Nayler,
y manejó el tema con tanta perspicacia y evidente demostración,
que su razonamiento me pareció irresistible; y supongo que mi padre lo vio así,
lo que hizo que rápidamente estuviera dispuesto a dejar la conversación.
En cuanto a Edward Burrough, era un joven vivaz, con facilidad para hablar,
y podría haber sido, por todo lo que yo sabía en ese entonces, un erudito,
lo que hizo que admirara menos su forma de razonar.
Pero lo que salió de la boca de James Nayler tuvo mayor impacto sobre mí,
porque se veía como un simple y humilde hombre de campo,
con la apariencia de un agricultor o de un pastor.
Al ver que mi papá no había sido capaz de mantener la discusión a su favor,
ellos tampoco estuvieron dispuestos a llevarla en extremo al suyo; sino que,
tratándolo con suavidad y gentileza, después de un rato dejaron la conversación,
y luego nos retiramos a nuestras respectivas habitaciones.
La mañana siguiente nos preparamos para regresar a casa, a saber, mi padre,
mi hermana menor y yo;
porque mi hermana mayor se había ido antes en una diligencia a Londres.
Y cuando comenzamos a salir, después de habernos despedido de nuestros amigos,
ellos nos acompañaron a la puerta,
donde Edward Burrough nos habló unas pocas palabras a cada uno individualmente,
según el sentido que tenía de nuestras diferentes condiciones.
Y luego de que nos fuimos, cuando ellos habían vuelto a entrar,
los Penington le preguntaron qué pensaba de nosotros.
Él les respondió (como ellos me contaron después) de esta manera: "`En cuanto al anciano,
está establecido en sus opiniones; y la joven es superficial e indiferente;
pero el joven ha sido alcanzando, y le puede ir bien si no lo pierde.`"
Y sin duda, las palabras que me había hablado,
o más bien el Espíritu por medio del cual las había hablado,
se apoderó de mí tan fuertemente, que sentí que me invadieron la tristeza y la angustia,
aunque no entendía con claridad por qué estaba angustiado.
No sabía qué me afligía, pero sabía que era algo fuera de lo normal,
y mi corazón estaba muy pesado.
Me di cuenta de que no le sucedía lo mismo a mi padre, ni a mi hermana;
porque mientras cabalgaba detrás del coche, podía escucharlos conversar placenteramente.
Pero ellos no pudieron discernir lo que me estaba pasando, porque al ir a caballo,
me mantuve fuera de su vista.
Samuel Fothergill, encontrándose en Scarborough,
vio que el almirante Tyrrell asistió a varias reuniones de los Amigos en ese lugar,
y tomó particular nota de la solemnidad y reverencia
del comportamiento del almirante durante la reunión,
especialmente en el tiempo de silencio.
Poco después de esto, el almirante se acercó a Samuel, en los salones comunes,
delante de muchos miembros de la nobleza y de la alta sociedad, y dijo: "`Sr. Fothergill,
tengo una muy alta opinión de los principios y prácticas de su pueblo,
en especial del recogimiento y espiritualidad de su adoración silenciosa.`"
Samuel respondió: "`Almirante,
me parece una declaración extraordinaria viniendo de usted, siendo un hombre de guerra,
respecto a nosotros y a nuestros principios,
que son de paz y contrarios a toda violencia.`"
El otro continuó: "`Señor, concuerdo con usted en ese punto;
y creo plenamente que llegará el tiempo cuando "`no alzará espada nación contra nación,
ni se adiestrarán más para la guerra;`" pues así como toda
dispensación de la Sabiduría infalible ha de tener un comienzo,
ésta la ha tenido esta entre ustedes, aunque aún no nos ha alcanzado.
Y en cuanto a lo que ustedes sostienen sobre una unión y comunión con el divino Instructor,
sé por feliz experiencia, que es algo alcanzable en este tiempo;
y ahora se me ocurre un ejemplo de ello.`"
"`Cuando tuve el honor de comandar tres de los
buques de guerra de su majestad como comodoro,
un poco antes de que concluyera la última paz,
se nos informó que cinco grandes barcos franceses se dirigían hacia nosotros,
todos superiores a nosotros en hombres y artillería.
Inmediatamente se convocó un consejo de guerra,
y mientras estaban reunidos, me retiré solo a mi camarote;
y tras alcanzar un silencio perfecto,
oí en lo secreto de mi mente una voz tan perceptible a mi entendimiento
como cualquiera palabra lo haya sido jamás a mis sentidos externos:
'`Ve y combate la flota francesa,
porque los he entregado en tus manos.`' Me levanté
con reverente gratitud por esta divina indicación,
e hice saber al consejo que debíamos combatir a la flota francesa,
y que estaba seguro de la victoria.
Se preparó todo,
y el resultado demostró la certeza de aquella misericordiosa advertencia;
habiendo obtenido plena victoria, como se relata en la historia de aquella guerra.`"
Los detalles de esta conversación fueron contados por Samuel Fothergill a un Amigo,
mientras viajaban juntos en su camino desde Londres tras la reunión anual de 1770;
y habiendo sido publicados,
pueden ocupar un lugar en este libro en concordancia con el título
de esta colección. Este relato transmite una ilustración muy clara
de la perspectiva que adoptamos respecto al tema de la guerra,
y al mismo tiempo sirve de confirmación para quienes creen
en las manifestaciones del Espíritu Santo.
No podemos considerar que estas manifestaciones, o revelaciones de la voluntad divina,
estén limitadas a una época del mundo, ni a un grupo específico de personas,
ni siquiera a un momento particular en la vida de un hombre; tampoco podemos,
de ninguna manera, limitar la influencia y las operaciones de ellas,
ya sea en cuanto a su naturaleza, modo, alcance o propósito.
La gracia, misericordia, luz, verdad o poder divinos,
que visitan y redimen el alma del hombre perdido, constituyen, sin duda alguna,
el principio vital de la religión;
y aquel que no resiste estas manifestaciones palpables, sino que, por el contrario,
aprovecha con agradecimiento y sencillez la capacidad
que nunca deja de acompañarlas--este hombre,
según su medida o don de gracia,
comienza a conocer algo de los rudimentos de la religión. Y, según entendemos,
si él continúa conociendo al Señor, y así cree y permanece en Él,
será finalmente aceptado por Él. Sin este aliento celestial de vida en él,
el pobre hombre está como muerto;
no puede avanzar un solo paso en el camino de la salvación.
¡Cuán grande es, pues, el don gratuito y universal de Dios en Su Hijo,
el "`Espíritu vivificante,`"^
footnote:[1 Corintios 15:45]
"`la Luz del mundo,`" el único camino al Padre.
Fue mediante esta "`obediencia de la fe`" al único
gran objeto de la fe que todos los fieles,
desde el justo Abel hasta este día, heredaron las promesas.
Fue mediante la revelación del Espíritu eterno en el interior,
en sus corazones y conciencias, que los patriarcas, profetas y apóstoles de antaño,
según sus diversas dispensaciones de luz, llegaron a conocer el camino de paz;
y por la ayuda de Él fueron capacitados para agradar a Dios y adorarle.
Las visiones y el ministerio de los ángeles parecen haber
constituido un canal de comunicación divina en aquel tiempo,
como esos y muchos otros medios lo han sido desde entonces;
pero cualquiera que sea el método, directo o indirecto, que el Señor,
en las riquezas de su misericordia,
se complazca en proveer para el servicio de su criatura,
sigue siendo una verdad firme que "`nadie conoce al Hijo, sino el Padre,
ni al Padre conoce alguno, sino el Hijo, y aquel a quien el Hijo lo quiera revelar.`"^
footnote:[Mateo 11: 27]
De modo que, cuando se concede una ayuda instrumental,
tanto el receptor como el simple instrumento quedan
igualmente en deuda con el Autor de todo bien,
por la directa extensión de Su bendición--es decir, por la capacidad de entender,
aplicar y poner en práctica Su esencial Verdad salvadora, la cual es la misma ayer,
hoy y por los siglos.
Las breves observaciones recién expresadas referentes solo a
algunos aspectos de este tema tan importante y extenso,
espero que no sea de tropiezo para ningún buscador sincero en el camino a Sion.
No me pareció este el lugar apropiado para tratar los vínculos y las numerosas
ramificaciones que fácilmente pueden surgir en la mente al considerar lo anterior;
y quizá por esta razón convenga que el lector que no está
plenamente familiarizado con nuestros principios,
sea prudente al sacar conclusiones de este breve pasaje, no sea que, sin motivo,
atribuya error a sus hermanos profesantes del cristianismo.^
footnote:[El Cristiano Cuáquero, de William Penn,
transmite mucha información e instrucción relacionada con este tema.]
Puede añadirse una observación más a lo anterior.
Muchos que concuerdan con nosotros en estas cosas,
no alcanzan a ver tan plenamente como el almirante,
que la disposición de corazón más apta para percibir
y recibir los secretos de la divina Sabiduría,
es aquella que se retira frecuente y deliberadamente, tanto como sea posible,
de las cosas visibles que son temporales: un alma quieta y atenta; es decir,
un apartarse de las meras divagaciones de la imaginación no sujeta,
acompañado de una rendición completa de todo nuestro corazón a nuestro Hacedor,
con el deseo de que lo haga y lo mantenga como un
templo apto para la morada de Su Santo Espíritu.
No niego que esto sea un arduo trabajo y un gran logro; sin embargo,
aquellos que han sido constreñidos a intentar andar en este camino,
hallan que es un camino de deleite y paz interior.
Ellos también conocen con certeza que lo difícil se vuelve fácil,
pues "`el socorro se ha puesto sobre Aquel que es poderoso.`"^
footnote:[Salmo 89:19]
En el curso de sus deberes entre sus prójimos,
están comprometidos a examinar con cuidado sus palabras y sus acciones,
y hasta sus propios pensamientos están sujetos a
regulación. Su comportamiento general es,
por consiguiente, tal que, en todos los aspectos, es conforme al evangelio de Cristo,
pues profesan caminar con Dios, creer en Él y sentir Su presencia,
un Dios verdaderamente cercano en los corazones de sus hijos dependientes.
Mientras me encontraba en Londres +++[+++en el año 1668],
fui un día a visitar al que llamaban el esquire^
footnote:[En Inglaterra, este título se otorga a los hijos menores de los nobles,
a los funcionarios de los tribunales del rey y de la casa, a los consejeros de la ley,
a los jueces de paz, mientras están en comisión, a los alguaciles y a otros caballeros.]
Marsh, quién había mostrado mucha amabilidad tanto hacia mí como hacia los Amigos.
Sucedió que llegué cuando estaba cenando.
Tan pronto como escuchó mi nombre,
me hizo llamar y quiso que me sentara a la mesa con él;
pero no sentí la libertad de hacerlo.
Había varias personas de importancia cenando con él, y le dijo a una de ellas,
que era un papista: "`Aquí hay un Cuáquero, lo cual no has visto antes.`"
El papista me preguntó si yo reconocía el bautismo de niños. Le
respondí que no había Escritura alguna que respaldara tal práctica.
"`¿Cómo?,`" dijo él, ¿no hay Escritura para el bautismo de niños?`" "`No,`" le dije,
y le dije que nosotros reconocíamos el único bautismo
por el único Espíritu en un solo cuerpo;
pero que echar un poco de agua sobre el rostro de
los niños y decir que eso era bautizarlo y cristianizarlo,
no tenía fundamento en las Escrituras.
Luego me preguntó si reconocía la fe católica.
Le dije que sí, pero añadí que ni el papa ni los papistas están en la fe católica;^
footnote:[La palabra católica significa universal.]
pues la fe verdadera obra por el amor^
footnote:[Gálatas 5: 6]
y purifica el corazón;^
footnote:[Hechos 15:9]
y que, si ellos estuvieran en esa fe que da la victoria,
por la cual se puede tener acceso a Dios,^
footnote:[Efesios 3:12]
no hablarían a la gente de un purgatorio después de la muerte,
porque la verdadera y preciosa fe divina, de la cual Cristo es el autor,
da victoria sobre el diablo y el pecado que separan al hombre y a la mujer de Dios.
Y que si ellos (los papistas) estuvieran en la verdadera fe, jamás usarían torturas,
prisiones o multas para perseguir y obligar a los que no eran de su propia fe
a entrar en su religión. Esta no fue la práctica de los apóstoles ni de los cristianos
primitivos (quienes dieron testimonio y gozaron de la verdadera fe de Cristo),
sino la de los judíos incrédulos y de los paganos.
"`Pero,`" continué, "`viendo que eres un hombre prominente entre los papistas,
enseñado y formado bajo la autoridad del papa;
y que dices que no hay salvación sino en su iglesia, quiero saber de ti,
¿qué es lo que trae la salvación en tu iglesia?`"
Él respondió: "`Una buena vida.`"
"`¿Nada más?`" pregunté. "`Sí,`" replicó, "`buenas obras.`"
"`¿Es esto lo que trae la salvación en tu iglesia: una buena vida y buenas obras?
¿Es esta tu doctrina y principio?`"
le dije.
"`Sí,`" respondió. "`Entonces,`" continué, "`ni tú, ni el papa,
ni ninguno de los papistas saben qué es lo que trae la salvación.`" Él me preguntó,
qué traía la salvación en nuestra iglesia.`"
Le respondí: "`Lo mismo que trajo la salvación a la iglesia en los días de los apóstoles,
eso mismo nos trajo salvación a nosotros, y no otra cosa; a saber, la gracia de Dios,
que--según las Escrituras--trae salvación y se ha manifestado a todos los hombres.
Esta enseñó a los santos de antaño, y nos enseña ahora a nosotros.
Esta gracia, que trae salvación,
enseña a "`renunciar a la impiedad y a los deseos mundanos, y a vivir sobria,
justa y piadosamente.`"
Así que, no son las buenas obras, ni una buena vida lo que trae salvación, sino la gracia.
"`¿Qué?`" dijo el papista,
"`¿esta gracia que trae salvación se manifiesta a todos los hombres?`"
"`Sí,`" le respondí. "`Entonces,`" dijo, "`niego eso.`"
Le contesté: "`Todos los que lo niegan son sectaristas, y no están en la fe,
la gracia y la verdad universales en que estaban los apóstoles.`"
Luego me habló de la madre-iglesia.
Le dije que las diversas sectas en la cristiandad nos habían acusado,
diciendo que habíamos abandonado nuestra madre-iglesia.
Los papistas nos acusaban de abandonar su iglesia,
diciendo que Roma era la única madre-iglesia.
Los episcopales nos reprochaban haber dejado la antigua religión protestante,
alegando que la suya era la madre-iglesia reformada.
Los presbiterianos e independientes nos censuraban por apartarnos de ellos,
cada uno pretendiendo que su iglesia era la correctamente reformada.
Pero, le dije, si pudiéramos reconocer algún lugar externo como madre-iglesia,
sería Jerusalén, donde el evangelio fue predicado primero por Cristo y los apóstoles,
donde Cristo sufrió,
donde tuvo lugar la gran conversión al cristianismo por medio de Pedro,
donde se hallaban los tipos, figuras y sombras que Cristo cumplió,
y donde Cristo mandó a sus discípulos a esperar hasta
ser investidos con poder de lo alto.
Si algún lugar externo mereciera ser llamado madre,
ese sería el lugar donde ocurrió la primera gran conversión al cristianismo.
Pero el apóstol dice: "`La Jerusalén actual, junto con sus hijos está en esclavitud.
La Jerusalén de arriba, es madre de todos nosotros.`"^
footnote:[Gálatas 4:25-26 RVG]
Y aunque este título de "`madre`" ha sido otorgado
a lugares y sectas por los cristianos degenerados,
seguimos diciendo, como el apóstol de antaño: "`La Jerusalén de arriba,
es madre de todos nosotros.`"
No podemos reconocer otra, ni la Jerusalén externa, ni Roma,
ni ninguna secta o pueblo como nuestra madre, sino la Jerusalén de arriba, que es libre,
la madre de todos los que han nacido de nuevo,
se han convertido en verdaderos creyentes en la Luz, y han sido injertados en Cristo,
la Vid celestial.
Pues todos los que han "`nacido de nuevo de la semilla inmortal, por la Palabra de Dios,
que vive y permanece para siempre,`" se alimentan
de la "`leche de la Palabra,`" el pecho de vida,
crecen en la vida por ella,
y no pueden reconocer otra madre sino la Jerusalén de arriba.
Del diario de George Fox
Siempre había tenido tan en alta estima el matrimonio, como institución divina,
que nunca consideré lícito convertirlo en una especie
de negocio político para ascender en el mundo.
Y por tanto,
así como no podía sino reprobar en mi juicio a aquellos
que se proponían como objetivo andar tras,
y procurar conseguir,
esposas que fueran tenidas por "`grandes fortunas;`"
sin preocuparse tanto de lo que ella es,
sino de lo que tiene, haciendo así de la riqueza lo principal, si no lo único,
a lo que aspiraban:--así resolví evitar en mi propia práctica tal camino.
Y aunque mi condición pudiera, como a otros,
haberme impulsado a buscar ventaja de ese modo,
determiné nunca comprometerme por motivo de riquezas, ni en modo alguno casarme,
hasta que un afecto juicioso me llevara a ello;
afecto que ahora comenzaba a experimentar en mi pecho.
El objeto de este afecto era una Amiga llamada Mary Ellis,
a quien había tratado durante varios años únicamente en términos de amistad;
y en quien creí ver entonces aquellas nobles huellas de la Verdad y de la virtud sólida,
que después encontré en ella en grado sublime; pero en cuanto a su condición en el mundo,
respecto a bienes, yo lo ignoraba por completo, ni deseaba saberlo.
Una vez, uno o dos años antes,
tuve la oportunidad de prestarle un pequeño servicio en algo en que necesitaba ayuda;
y en ello actué con toda sinceridad y libertad de mente,
sin esperar ni desear obtener provecho alguno de ella, ni recompensa de su parte,
quedando muy satisfecho con el acto mismo por haber
ayudado a una amiga y socorrido a quien lo necesitaba.
Aquel pequeño intercambio de amabilidad común entre nosotros
terminó sin la menor sospecha--estoy verdaderamente persuadido,
de su parte,
y seguro de la mía--de una relación entre nosotros
más allá de la de una amistad sincera y leal;
ni nos condujo entonces a una conversación más cercana,
ni a una intimidad mayor entre nosotros que la que ya teníamos.
Pero después de un tiempo considerable,
hallé que mi corazón se sentía secretamente inclinado y atraído hacia ella.
Sin embargo, no me apresuré en proponer nada,
sino que esperé sentir una convicción interior satisfactoria
al respecto antes de dar cualquier paso.
Al cabo de un tiempo,
encontré una oportunidad para abrir mi corazón a mis muy honorables amigos,
Isaac y Mary Penington,
quienes entonces ocupaban para mí el lugar de padres (paretum loco).
Ellos, tras sopesar con solemnidad el asunto, expresaron su conformidad con ello;
y en verdad, su aprobación fue para mí una gran confirmación. No obstante,
tomé más tiempo para reflexionar,
retirándome a menudo en espíritu ante el Señor y clamando a Él por dirección,
antes de dirigirme a ella.
Finalmente, estando sentado a solas, esperando en el Señor consejo y guía en este asunto,
que en sí mismo y para mí, era de tanta importancia,
sentí que una palabra se levantaba dulcemente en mí,
como si hubiera oído una voz que decía: "`Ve, y prevalece.`"
Y brotando la fe en mi corazón con aquella palabra, me levanté de inmediato y fui,
sin dudar en lo más mínimo.
Ya en su hogar, que estaba a casi dos kilómetros de la mía,
le pedí a la criada que le hiciera saber a su señora que había llegado a visitarla;
tras lo cual fui invitado a subir.
Y después de una conversación ligera,
sintiendo en mi espíritu la gran importancia de ello,
le abrí solemnemente mi corazón respecto al asunto particular que me había llevado allí;
lo cual pronto percibí que la sorprendió grandemente.
Pues ella había asumido, como también lo habían hecho otros,
que mis ojos estaban puestos en otro lugar, y más cerca de casa.
No le dije muchas palabras; pero sentí que un poder divino acompañaba las palabras,
y que lo expresado quedó tan firmemente arraigado en su pecho que,
como después me confesó, no pudo apartarlo de sí. . Mi visita fue breve.
Pues, habiéndole hecho mi propuesta,
le dije que no esperaba una respuesta de ella en ese momento;
sino que deseaba que la sopesara de la manera más solemne,
y a su debido tiempo me diera la respuesta que el Señor le otorgara.
Me despedí de ella y me fui, dejando el resultado en manos del Señor.
Tenía entonces un viaje por delante, que preveía me tomaría cerca de dos semanas.
Por tanto, el día antes de partir fui a visitarla de nuevo,
para informarle de mi viaje y disculpar mi ausencia;
sin presionarla aún por una respuesta,
sino confirmándole que sentía en mí un incremento de afecto hacia ella,
y que esperaba recibir una respuesta correspondiente de su parte en el tiempo del Señor;
a Quién, entretanto, había encomendado tanto a ella como a mí mismo,
así como el asunto que nos concernía. Y, en verdad, comprobé a mi regreso,
que no podría haber dejado aquello en mejores manos;
pues el Señor había sido mi abogado en mi ausencia,
y había respondido tan bien a todas sus objeciones, que, cuando acudí a ella de nuevo,
me las comunicó sin defenderlas.
Desde entonces nos tratamos con afectuosa ternura, con miras al matrimonio; al cual,
sin embargo, no nos apresuramos, sino que fuimos avanzando con prudencia.
Tampoco usé aquellos métodos comunes de cortejo,
que consisten en hacer frecuentes y costosos regalos;
no sólo porque mi situación externa no me lo permitía,
sino porque no me agradaba obtener algo por tales medios,
y prefería un afecto sin sobornos.
Continué visitando a mi más querida amiga hasta que nos casamos,
lo cual ocurrió en el año 1669.
Nos unimos en una reunión selecta de los ancianos y piadosos Amigos de aquella región,
llevada a cabo en la casa de un Amigo.
Donde, en aquella época,
no sólo se realizaba la reunión mensual para la disciplina de la iglesia,
sino también a veces la reunión pública para adoración. Fue una reunión muy solemne,
y nos hallábamos en un estado de espíritu profundamente recogido;
en el cual sentimos de manera palpable que el Señor estaba con nosotros y nos unía;
sensación que permaneció con nosotros toda nuestra vida,
y que fue de gran provecho y muy consoladora en toda ocasión.
Cerca del año 1660 recibimos un informe de Nueva Inglaterra,
que decía que el gobierno de aquel lugar había hecho
una ley para desterrar a los Cuáqueros de sus colonias,
so pena de muerte en caso de regresar; que varios de nuestros Amigos,
habiendo sido desterrados y habiendo regresado,
fueron apresados y efectivamente ahorcados,
y muchos más estaban en prisión y en peligro de que se les impusiera una sentencia similar.
Cuando ellos fueron ejecutados, yo me hallaba en la prisión de Lancaster,
y tenía un perfecto sentido de sus sufrimientos, como si hubiera sido yo mismo,
como si la soga hubiera sido puesta en mi propio cuello,
aunque en ese momento aún no lo habíamos oído. Pero en cuanto lo supimos,
Edward Burrough fue a ver al rey y le dijo:
"`Hay una vena de sangre inocente abierta en tus dominios, la cual, si no se detiene,
lo invadirá todo.`"
A esto el rey replicó: "`Yo detendré esa vena.`"
Edward Burrough dijo: "`Entonces hazlo rápidamente,
porque no sabemos cuántos vayan a ser ejecutados pronto.`"
El rey respondió: "`Tan pronto como ustedes lo deseen.
Llamen,`" dijo a algunos de los presentes, "`al secretario y lo haré en seguida.`"
El secretario fue llamado, y un mandato real fue concedido de inmediato.
Uno o dos días después,
Edward Burrough regresó a ver al rey para pedirle que se acelerara el asunto,
y el rey le dijo que por el momento no tenía ocasión de enviar un barco a Nueva Inglaterra;
pero que si nosotros queríamos enviar uno, podíamos hacerlo tan pronto como quisiéramos.
E+++.+++ Burrough le preguntó al rey si él estaría dispuesto
a conceder su representación a un Cuáquero,
para llevar el mandato a Nueva Inglaterra.
El rey respondió: "`Sí, a quien quieras.`"
Entonces E. Burrough nombró a Samuel Shattock,
que siendo habitante de Nueva Inglaterra había sido desterrado por su ley,
bajo pena de muerte si regresaba;
y a él le fue concedida la representación. Luego mandó a llamar a un Amigo honesto,
capitán de un buen barco,
y acordó con él por trescientas libras (hubiera o no mercancía) para zarpar
en diez días. El capitán se preparó de inmediato para navegar,
y con un viento favorable llegó en unas seis semanas ante la ciudad de Boston,
la mañana del primer día. Con él viajaban muchos pasajeros,
tanto de Nueva como de Vieja Inglaterra,
Amigos a quienes el Señor había movido a ir y dar
testimonio contra aquellos sangrientos perseguidores,
que habían sobrepasado en esa época a todo el mundo en sus sangrientas persecuciones.
Los habitantes de Boston,
al ver que una embarcación con colores ingleses entraba a la bahía,
subieron rápidamente a bordo, y preguntaron al comandante si traía cartas.
El respondió: "`Sí.`" Le preguntaron si las entregaría, pero él dijo: "`No; hoy no.`"
Entonces bajaron a tierra e informaron que había un barco lleno de Cuáqueros,
y que entre ellos estaba Samuel Shattock, de quien sabían que, según su ley,
debía ser condenado a muerte por regresar después del destierro;
pero ellos no sabían su encargo ni su autoridad.
A la mañana siguiente, Samuel Shattock, representante del rey,
y el comandante desembarcaron,
enviando de vuelta al barco a los hombres que los habían llevado a tierra,
atravesaron la ciudad hasta la puerta del gobernador John Endicot y llamaron.
El gobernador envió a un criado para enterarse del asunto;
y ellos respondieron que su asunto era del rey de Inglaterra,
y que no le darían su mensaje a nadie sino al propio gobernador.
En seguida se les permitió entrar y el gobernador salió a recibirlos.
Tras haber recibido la autorización y el mandato real,
se quitó el sombrero y los miró. Luego salió, ordenó a los dos Amigos que lo siguieran,
fue donde el vicegobernador, y tras una breve consulta, volvió y les dijo:
"`Obedeceremos el mandato de Su majestad.`"
Después de esto,
el capitán del barco dio libertad a los pasajeros
para desembarcar y en seguida se difundió la noticia,
y los Amigos de la ciudad y los pasajeros de la nave se reunieron
para ofrecer alabanzas y acciones de gracias a Dios,
quien tan maravillosamente los había librado de las fauces del devorador.
Mientras estaban reunidos, entró un pobre Amigo, quien,
sentenciado a muerte por aquella ley,
llevaba tiempo encadenado en espera de la ejecución. Esto aumentó
su gozo y los hizo elevar sus corazones en exaltaciones a Dios,
quien es digno por siempre de alabanza, gloria y honor; pues sólo Él puede librar,
salvar y sostener a todos los que confían sinceramente en Él.
John Churchman, en su visita a Nueva Inglaterra en 1742,
tuvo una reunión cerca de Newberry.
De esta reunión dice:
Fui movido a hablar brevemente sobre el inicio de la Reforma--que se apartó
de los errores de la iglesia de Roma--y de los sufrimientos de los protestantes,
particularmente en Inglaterra,
algunos de cuyos sucesores se convirtieron en perseguidores,
y fueron muy crueles con aquellos a quienes llamaba sectarios.
Entre ellos,
los presbiterianos llegaron a América y se establecieron en Nueva Inglaterra,
con la esperanza de disfrutar de ese derecho razonable, la libertad de consciencia.
Pero, olvidando la ley de oro de hacer a los demás como quisieran que les hicieran a ellos,
se convirtieron en perseguidores del pueblo llamado Cuáqueros,
llegando incluso a causar la muerte de varios de ellos.
Sentí hablar sobre la naturaleza y el fundamento de la persecución,
y la gran inconsistencia que ésta tiene con el cristianismo.
Varios de los presbiterianos se encontraban presentes; y un hombre mayor de Newberry,
uno de sus líderes, y un anciano entre ellos,
pidió hablar conmigo apenas terminó la reunión.
Habiéndome retirado a un pequeño salón,
un Amigo me informó que el anciano quería ser admitido para hablar conmigo,
a lo que no sentí ninguna objeción, pues estaba tranquilo y sereno en mi mente,
aunque esperaba que viniera a discutir.
Cuando entró, me hizo saber que tenía algunas observaciones que hacerme;
dijo que suponía que yo era un hombre que había leído mucho,
o no podría estar tan familiarizado con la Reforma,
y que también suponía que había recibido educación universitaria.
Con respecto a esto último,
le dije que nunca había asistido a una escuela sino unos tres meses,
y que el hombre con quien había estudiado, siendo tejedor de profesión,
se sentaba en su telar y escuchaba a sus alumnos leer;
que yo estaba muy lejos de haber recibido una educación formal,
pues había nacido en un lugar despoblado, donde se habían asentado pocas familias,
a muchas millas de otros habitantes.
Ante lo cual, levantando sus manos, se santiguó y añadió: "`Entonces,
el cielo te ha ungido para predicar el evangelio y hoy has predicado la Verdad;
pero te aseguro que, aunque he sido funcionario de la parroquia,
nunca he tomado nada de tus amigos Cuáqueros, pues estoy en contra de la persecución;
así que Dios te bendiga en tu viaje.`"
La siguiente narración fue escrita por William Penn,
en el relato que dejó de sus viajes a Holanda y Alemania, en el año 1677.
Parece que este viaje se emprendió principalmente por motivos religiosos; en parte,
para visitar y confirmar a sus compañeros profesantes en
ese precioso testimonio y doctrina de la cual habían participado,
y también para contribuir (bajo el expreso encargo,
dirección y asistencia de su santo Líder) a la expansión
y esparcimiento del reino de Cristo,
ese bendito reino que es declarado ser "`justicia, paz, y gozo en el Espíritu Santo.`"^
footnote:[Romanos 14:17]
Habiéndonos refrescado con algo de comida, tomamos un carruaje para Wiewart,
la mansión de la familia de Somerdykes, donde residía la compañía Jean de Labadie,^
footnote:[En otra parte del diario de William Penn describe a esta persona de esta manera.
{footnote-paragraph-split}
"`Este hombre era francés,
y como estaba insatisfecho con la ligereza y la muerte
espiritual de los protestantes franceses,
incluso en la misma Ginebra, los dejó y se fue a Holanda;
y allí denunció con tal vehemencia la apostasía de los sacerdotes y del pueblo,
que el clero se enfureció y agitó a los magistrados en su contra;
especialmente porque muchos los seguían,
entre ellos varias mujeres de elevada condición social.
Me sentí movido a visitar a este hombre y a su compañía hace seis años,
y llegué a verlo a él y a sus dos principales discípulos;
pero ellos no me permitieron ver a las personas que lo seguían,
algo que procuré conseguir.
En aquel día logré ver la ligereza e inestabilidad del espíritu de ese hombre,
y que su nombre era "`maestro de secta;`" y sentí sobre mí hacerles saber,
tanto de palabra como por escrito,
que el enemigo prevalecería contra ellos al arrastrarlos a cosas inconvenientes,
si no llegaban a permanecer en la Luz de Cristo y a conocer el santo silencio;
y que al final acabarían por enemistarse entre sí y dispersarse.
Esto ha llegado a suceder en alguna medida, tal como temía;
porque percibí claramente que, aunque habían recibido algunos toques divinos,
corrían el peligro de desperdiciarlos y malgastarlos como pródigos,
sin saber entonces dónde mantener sus mentes para recibir el pan de cada día. Verdaderamente,
aunque eran algo angelicales y semejantes a los cuerpos celestes,
si no se mantenían en su estado, se convertirían en estrellas caídas.
No se movían bajo la guía de Aquel que los había visitado,
sino que estaban llenos de mezclas evidentes.
Sin embargo, tenía buena opinión de algunas de estas personas,
porque había algo bueno moviéndose en ellos.`"]
después de haber sentido fuertemente en mi espíritu visitarlos.
Llegamos alrededor de las cinco; y mientras caminábamos por un campo hacia la casa,
nos encontramos con un joven de esa compañía que nos condujo hasta
allí. Pregunté por el pastor Ivon y por Anna Maria Schurmans.
Ivon se presentó con su copastor; nos recibieron amablemente y me invitaron a entrar.
Pero, previendo que mi tiempo allí sería muy corto para el mensaje
que debía dar--pues el sol estaba a punto de ponerse,
y teníamos por delante dos millas inglesas de camino desconocido hasta nuestro alojamiento,
a pie--les pedí que me dieran la oportunidad de hablar a la mañana siguiente,
a lo cual accedieron rápidamente.
Entonces me despedí de ellos,
quienes amigablemente nos acompañaron una parte de nuestro camino.
Aquella noche sentí un gran peso sobre mi espíritu, y aún más a la mañana siguiente;
sin embargo, mi fe estaba en el poder de Dios,
y tenía un claro sentir de que tendría un buen servicio entre ellos,
de que despejaría mi conciencia, y de que mi paz descansaría conmigo.
La mañana siguiente regresé donde ellos, acompañado de John Claus.
Tan pronto llegamos, nos llevaron al apartamento de Anna Maria Schurman,
donde también se encontraba una de las tres Somerdykes.
Anna Maria Schurmans tiene más de sesenta años,
y es muy conocida y célebre por sus conocimientos y estudios en idiomas y filosofía,
habiendo alcanzado un lugar reconocido entre los hombres más eruditos de su época.
Las Somerdykes son hijas de un noble de La Haya, personas de gran linaje y herencia.
Éstas, junto con otras varias personas,
al ser afectadas por la ferviente denuncia de Jean de Labadie
contra las iglesias muertas y formales del mundo,
y despertadas a buscar una comunión y sociedad más espirituales,
se separaron de las iglesias calvinistas comunes y lo siguieron
en el camino de una independencia más depurada.
Son un pueblo serio y sencillo,
y se han acercado más a los Amigos en cuanto a las reuniones en silencio,
la participación de las mujeres, la predicación por el Espíritu,
la sencillez en la vestimenta y en el mobiliario de sus casas.
Junto con estas dos mujeres, nos acompañaron dos pastores y un doctor en medicina.
Después de un tiempo de silencio,
les pregunté qué los había impulsado a separarse
de la manera común en que antes habían vivido.
Les pedí que fueran claros y abiertos conmigo en cuanto al motivo de su separación;
pues no había venido a poner objeciones, sino, en espíritu cristiano, a informarme.
Ante esto, Ivon, el pastor principal,
nos relató la historia de la educación de Jean de Labadie,
cómo había sido formado entre los jesuitas,
los había abandonado y había abrazado la religión protestante,
así como la gran insatisfacción que había sentido con las iglesias protestantes.
Añadió varios testimonios solemnes sobre la sencillez e
integridad de sus corazones en estas cuestiones.
Una vez que Ivon terminó, Anna Maria Schurmans continuó. Nos habló de su vida pasada,
de su placer por aprender y de su amor por la religión en la que había sido educada;
pero confesó que durante ese tiempo no había conocido verdaderamente a Dios ni a Cristo.
Y aunque desde niña Dios la había visitado en ocasiones,
nunca había sentido un golpe tan poderoso como el
que experimentó por el ministerio de Jean de Labadie.
Comprendió que su aprendizaje era vanidad,
y que su religión era como un cuerpo de muerte; determinó menospreciar el oprobio,
abandonar su pasada manera de vivir y sus antiguas relaciones,
y unirse a esta pequeña familia alejada del mundo,
entre quienes anhelaba ser hallada como un sacrificio vivo,
enteramente ofrecido al Señor. Habló de manera muy seria y conmovedora,
no sin cierto temblor.
Éstas son breves referencias de lo que dijo.
Luego, una de las Somerdykes comenzó, en un estado de ánimo muy reverente y serio,
que correspondía plenamente con su desprecio del mundo.
Nos contó cuán a menudo había lamentado desde su juventud,
no haber conocido al Señor como deseaba; diciendo a menudo dentro de sí:
"`Si Dios me hiciera saber Su camino, yo pisotearía todo orgullo y la gloria del mundo.`"
Expresó solemnemente la frecuente angustia de espíritu que había sentido debido
a la muerte y formalidad de los cristianos entre quienes había sido educada,
diciéndose: "`¡Oh, el orgullo, los placeres,
los vanos deleites en que viven los cristianos! ¿Puede ser éste el camino al cielo?
¿Es éste el camino a la gloria?
¿Son éstos los seguidores de Cristo?
¡Oh no!
Oh Dios, ¿dónde está tu manada pequeña que vive enteramente para Ti, y que Te sigue?
Hazme una de ese número.`"
"`Y cuando`"--continuó ella--"`el siervo del Señor, Jean de Labadie, llegó a Holanda,
yo, entre otros, sentí curiosidad por escucharlo,
y junto con varios quedé profundamente afectada.
Puso en palabras los mismos pensamientos de mi corazón.
Mi corazón fue traspasado cuando lo oí,
y decidí, por la gracia de Dios, abandonar toda la gloria y el orgullo de este mundo,
para ser una de aquellos que se sentaban con él separados
de las vanas y muertas adoraciones de este mundo.
Me considero muy dichosa de haberlo conocido,
y a estos pastores que no se buscan a sí mismos,
sino al Señor. Somos una familia que vive unida en amor, en una misma alma,
un mismo espíritu, entregada a servir al Señor; y éste es el mayor gozo del mundo.`"
Después, Du Lignon, el otro pastor,
también nos dio un relato de los motivos que lo llevaron a seguir a Jean de Labadie,
aunque de manera menos vívida.
Después de él, habló el doctor en medicina, que había sido educado para ser sacerdote,
pero que voluntariamente había rechazado ese llamado;
y se expresó de la siguiente manera:
"`Yo también puedo dar testimonio ante la presencia de Dios, de que,
a pesar de que había gozado de tanta reputación en
la universidad como cualquiera de mis colegas,
y era bien considerado por mi sobriedad y mi honestidad,
nunca había experimentado un sentido tan vivo de Dios como cuando oí al siervo del Señor,
Jean de Labadie.`"
Y añadió: "`El primer día que lo oí, fui tan golpeado y afectado,
que puedo decir con verdad que, por la buena gracia de Dios y la guía del Espíritu Santo,
fue para mí como el día de mi salvación;
tocó mi corazón tan vívidamente con un sentido de verdadera adoración cristiana,
que abandoné la universidad y decidí pertenecer a esta familia.
Y lo puedo decir en el temor del Señor.`"
Luego, Ivon concluyó:
"`Esto es lo que tenemos que decir respecto a la obra de Dios entre nosotros.`"
Durante todo ese tiempo, no prestaba tanta atención a sus palabras,
sino al sentimiento de unidad que tenía con la medida
del sentido divino que estaba sobre ellos.
Ciertamente, el Señor ha estado entre ellos; sí,
tuve un sentido vivo en mi corazón de que algo del
aliento de vida había soplado sobre ellos,
y aunque había en ellos gran mezcla, el amor de Dios estaba hacia ellos.
Después de un silencio, comencé de esta manera:
"`No vengo a juzgarlos, sino a visitarlos; no a contender ni a disputar,
sino a hablar de las cosas del reino de Dios; y no tengo prejuicios,
sino gran amor y estima en mi corazón hacia ustedes.
Por tanto, óiganme con paciencia y ternura cristiana.`"
"`Confieso y creo que Dios ha tocado sus corazones con Su dedo divino,
y que Su obra está entre ustedes;
que fue Su Espíritu quien les mostró la vanidad y necedad de este mundo,
y quien los ha hecho conscientes de las religiones muertas
que existen en él. Este es el sentido que amo y honro;
y estoy tan lejos de menospreciar u oponerme a este tierno sentido que siento en ustedes,
que por esto precisamente he venido a visitarlos, a ustedes, por amor a ello.
Y en cuanto a los reproches que puedan sobrevenirles a causa de su separación,
con todos los rumores que por ello circulan acerca de ustedes,
son justamente por lo que los respeto,
pues conozco muy bien la naturaleza y práctica de
este mundo hacia quienes se apartan de él.`"
"`Ahora que he escuchado con paciencia--y puedo decir sinceramente,
con gran satisfacción--el relato de sus experiencias,
concédanme la misma libertad cristiana para compartirles las mías,
a fin de que puedan comprender algo de la obra de Dios en mí;
porque aquellos que han alcanzado alguna medida del sentido divino,
son como espejos unos para otros, así como el rostro responde al rostro en un espejo.`"
Aquí comencé a contarles cómo y cuándo se me había aparecido el Señor por primera vez,
lo cual había ocurrido cuando tenía doce años, en 1656.
Cómo, en ocasiones, entre esa edad y los quince años, el Señor me había visitado,
y las impresiones divinas que me había dado de Sí mismo.
De mi persecución en Oxford,
y cómo el Señor me había sostenido en medio de aquella espesa oscuridad y corrupción;
de mi expulsión de la universidad;
del trato amargo que había sufrido al regresar a casa de mi padre; de los azotes,
golpes y el ser echado de casa en 1662.
De los tratos del Señor conmigo en Francia, y durante la gran plaga en Londres.
En resumen, del profundo sentido que Él me había dado de la vanidad de este mundo,
y de la irreligiosidad de las religiones en él. Luego,
les relaté mis lamentos y amargos clamores a Él,
pidiéndole que me mostrara Su propio camino de vida y salvación,
y les hablé de mis resoluciones de seguirle,
sin importar los reproches o sufrimientos que me sobrevinieran,
y todo ello con gran reverencia y contrición de espíritu.
Cómo, después de todo esto, la gloria del mundo me había vuelto a alcanzar,
y había estado incluso dispuesto a rendirme a ella,
al no ver aún nada del espíritu y la iglesia primitivos sobre la tierra;
y cómo estuve a punto de desfallecer respecto a mi
esperanza en la restitución de todas las cosas.
Fue durante este tiempo que el Señor me visitó con un
cierto sonido y testimonio de su eterna Palabra,
mediante uno de aquellos que el mundo llama Cuáqueros, a saber, Thomas Loe.
Les relaté las amargas burlas y desprecios que cayeron sobre mí;
el descontento de mis padres, los insultos y la crueldad de los sacerdotes,
lo extraño que me consideraban todos mis compañeros;
qué señal y maravilla hicieron de mí; pero sobre todo,
aquella gran cruz de resistir y velar contra mis propios
y vanos afectos y pensamientos interiores.
Aquí tuve una buena oportunidad para hablar del misterio
de iniquidad y de impiedad en su raíz y fundamento,
y para darles cuenta del poder y la presencia de Dios que nos acompañaban
en nuestros testimonios públicos y en nuestros sufrimientos;
censurando, de manera indirecta, sus debilidades^
footnote:[La obra del Señor entre los hombres--tal como
se muestra en el relato de William Penn--parece haber sido,
en aquel tiempo y país, obstaculizada por el temor al hombre,
la vergüenza de la cruz y el temor a la persecución;
lo cual los inclinaba más bien a una vida retirada que a
una profesión abierta de sus opiniones religiosas.]
al declarar y alabar las prácticas contrarias entre los Amigos,
demasiado extensas para relatarlas aquí. Y que,
a pesar de todos mis sufrimientos y pruebas por parte de los magistrados, padres,
compañeros y por encima de todo, de los sacerdotes de las religiones falsas del mundo,
el Señor me había preservado hasta este día y me había dado ciento por uno en este mundo,
así como la certeza de la vida eterna; informándoles de la ternura de mi padre hacia mí,
antes y a la hora de su muerte, y de cómo, mediante paciencia y longanimidad,
toda oposición había sido conquistada.
Luego comencé mi exhortación hacia ellos, de la siguiente manera: Que,
puesto que Dios nos había dado a mí y a ellos un sentido divino de Sí mismo,
nuestra mirada debía estar puesta en Él y no en el hombre;
para que pudiéramos entrar más en el silencio de nosotros
mismos y en un crecimiento en ese sentido celestial.
Que esta era la obra del verdadero ministerio:
no mantener a las personas centradas en los ministros mismos, enseñándoles siempre,
sino volverlas a Dios, al Maestro del nuevo pacto, y a Cristo,
el gran Ministro del evangelio.
Así lo hizo Juan, sin tener por afrenta que lo dejaran para ir a Cristo.
"`¡He aquí el Cordero de Dios,`" dijo, "`que quita el pecado del mundo!`"
Incluso los discípulos de Juan lo dejaron para seguir a Cristo.
Ciertamente, Juan da testimonio de sí mismo,
de que él debía "`menguar`" y que Cristo debía que crecer.`"
Por ello les rogué que fijaran sus ojos en Cristo, que quita el pecado,
Aquel que es del cielo, celestial, y los exhorté a velar para que Él creciera en ellos.
Sí, que de ahí en adelante no conocieran a nadie según la carne; no,
ni siquiera a Cristo mismo.^
footnote:[2 Corintios 5:16]
Que su conocimiento, y su consideración,
y su comunión unos con otros descansara en la revelación del Hijo de Dios en ellos,^
footnote:[Gálatas 1:16]
quien es el gran Profeta de Dios,
por medio del cual Dios habla en estos postreros días. Y
que si sus ministros fueran verdaderos ministros,
considerarían su gloria ceder el paso a Cristo,
de modo que ellos menguaran y Cristo creciera;
que el instrumento diera lugar a Aquel que lo usa, el siervo al Señor. . Esto,
aunque pudiera parecer que disminuye a los ministros, es, sin embargo,
la gloria de un verdadero ministro: que Dios y Cristo sean el todo en todos,
y que Su voluntad sea cumplida.
Porque, les dije, que el día del Señor Dios había llegado,
y que todos debían volver la mirada a Él para obtener salvación;
que todos debían ahora guardar el gran sábado de Dios,
reposar del mero hombre y del espíritu del hombre, y de todos los pensamientos,
palabras y obras de los hombres; y que, si eran verdaderos creyentes,
al menos ya estaban entrando en su reposo.^
footnote:[Hebreos 4: 1, 3]
Les recomendé encarecidamente que no fueran de aquellos
que comienzan en el Espíritu y acaban en la carne.^
footnote:[Gálatas 3:3]
"`Por tanto,`" les dije, "`permitan que Cristo tenga Su honor;
permitan que sea Él quien predique y hable entre ustedes, en ustedes y ustedes en Él;
y que solo por Él suspiren, oren, giman, canten, y no de otro modo,
no sea que la muerte venga sobre ustedes; porque así entró la apostasía,
por ir delante de Cristo, en lugar de dejar que Cristo fuera delante de ellos.`"
Además les aconsejé que esperaran en la Luz y en
el Espíritu de juicio que los había visitado,
para que todo lo que no había nacido de Dios fuera desarraigado;
y así llegarían a experimentar el nacimiento en la Semilla incorruptible,
"`por la Palabra de Dios, que vive y permanece para siempre,`"^
footnote:[1 Peter 1: 23]
para llegar a ser un sacerdocio santo,
que ofrece un sacrificio vivo con el fuego celestial de Dios,
y así Él tuviera Su honor en todos y a través de todos por medio de Jesucristo.^
footnote:[1 Pedro 2:5]
Dirigiéndome a las Somerdykes, con espíritu serio y tierno, les hablé:
"`Tengo un profundo y reverente sentir de que ustedes
deben ser peregrinas en la herencia de su Padre.
¡Oh, que puedan morar con Él para siempre, y exaltar a Aquel que las ha visitado,
con quien están las recompensas de la bienaventuranza eterna!`"
Así dejé entre ellos la bendición y la paz de Jesús,
marchándome en el amor y la paz de Dios;
y debo decir que ellos fueron más tiernos y respetuosos con nosotros de lo que esperábamos.
Todos nos acompañaron a la puerta exterior, excepto la anciana Anna Maria Schurmans,
que no podía caminar,
nos dieron la mano amistosamente y expresaron su gran satisfacción por nuestra visita.
Al llegar al pórtico y encontrarme con varios miembros de la familia,
fui movido a volverme hacia ellos y exhortarlos, en presencia de los demás,
a mantenerse vueltos a Cristo,
quien les había dado un sentido del espíritu de este mundo y había
despertado en ellos el deseo de ser liberados de él;
y a no conocer a nadie según la carne, sino a tener comunión en Cristo,
en unión y comunión con Dios, y unos con otros;
para que toda su adoración y actos descansen en Él,
para que Él pudiera ser todo en todos.
Deseé que el Señor los guardara en Su temor todos los días del tiempo que había determinado,
para que así Le sirvieran en su generación, en Su propio Espíritu universal,
para Su gloria, ¡quien es bendito por siempre!
El Señor consoló mi alma en este servicio; sí,
todo lo que hay dentro de mí magnificó Su Santo nombre,
por causa de Su bendita presencia que estaba con nosotros.
¡Oh, que mi alma confíe y repose en el Señor para siempre! ¡Oh,
que pueda morar y permanecer con Aquel que es fiel y verdadero,
y bendito por los siglos de los siglos!
Los dos pastores y el doctor caminaron con nosotros la distancia de un campo,
donde tomamos el carruaje;
y el mayor de ellos aprovechó la ocasión para preguntarme si la
Verdad no se había levantado primero entre un pueblo pobre,
analfabeto y simple.
Le dije que sí, que ese era nuestro consuelo,
y que no se lo debíamos al aprendizaje de este mundo.
"`Entonces,`" dijo él,
"`no permitas que el aprendizaje de este mundo sea usado para defender
lo que el Espíritu de Dios ha sacado a la luz;
porque los instruidos que ahora vienen entre ustedes estarán propensos a mezclar
la erudición académica con el lenguaje más sencillo y puro de ustedes,
y así oscurecerán el resplandor del testimonio.`"
Le dije que era bueno para todos tener cuidado de nuestros propios espíritus,
palabras y obras; reconociendo que lo que él había dicho tenía peso;
y que era nuestro cuidado escribir y hablar conforme al sentido divino,
y no según la invención humana.
Y así, de una manera muy sobria y seria, nos despedimos.

=== Popularidad

George Fox, hablando de sus viajes en América, dice:
Fuimos a Narraganset, a unas veinte millas de Rhode Island,
y el gobernador +++[+++de Rhode Island] fue con nosotros.
Tuvimos una reunión en casa de un juez,
donde los Amigos nunca habían tenido ninguna antes.
La reunión fue muy numerosa, pues, en general, llegó la gente del campo,
también personas de Connecticut y de lugares vecinos.
Había cuatro jueces de paz.
La mayor parte de estas personas nunca antes había escuchado a los Amigos; sin embargo,
fueron profundamente conmovidos, y hay entre ellos un gran deseo de la verdad.
De modo que, la reunión fue de gran provecho.
¡Bendito sea el Señor para siempre!
En otro lugar escuché que algunos de los magistrados decían entre ellos,
que si tuvieran suficiente dinero, me contratarían para ser su ministro.
Esto fue donde no nos comprendían lo suficiente, ni a nuestros principios.
Pero cuando lo supe, les dije que ya era tiempo de que me fuera;
porque si sus ojos estaban tan puestos en mí, o en cualquiera de nosotros,
no buscarían a su propio Maestro.
Porque esto, a saber, la contratación de ministros, había sido la ruina de muchos,
al impedirles incrementar sus propios talentos;
mientras que nuestra labor es llevar a cada uno a su Maestro en sí mismos.^
footnote:[1 Juan 2: 27]
A lo anterior, se puede añadir uno o dos extractos de una carta del mismo autor,
como sigue:
En los días de los apóstoles, cuando algunos decían ser de Pablo y otros de Apolos,
y de otros, Pablo los juzgó como carnales;
y los exhortó y amonestó para que su fe no estuviera fundada en
los hombres ni en las palabras de la sabiduría de los hombres,
sino en el poder de Dios.^
footnote:[1 Corintios 2:5]
Él dijo que no conocería las palabras de ellos, sino el poder entre ellos;
porque el reino de Dios no consiste en palabras, sino en poder.^
footnote:[1 Corintios 4:19-20]
Así también debe ser ahora.
La fe de cada uno debe estar fundada en el poder de Dios, y no en los hombres,
ni deberían basarse los discursos en palabras elocuentes.
Porque hemos visto por experiencia,
que cuando comienzan a exaltar a los hombres y ponen su fe en ellos, aquellos,
que quieren que la fe de las personas se funde en ellos,
aman la popularidad y no dirigen la fe de las personas
a estar fundada en el poder de Dios.
Tales no predican a Cristo, sino a sí mismos.
No pueden exaltar a Cristo; y cuando caen,
arrastran tras sí a una gran multitud de personas.
Aquellos cuya fe descansa en los hombres, crearán sectas; de esa fe,
Cristo no es el autor; y si alguna vez lo fue,
se han desviado y han naufragado en cuanto a la fe.
Todos los que están en la verdadera fe, la cual está fundada en el poder de Dios,
los juzgarán como carnales,
y juzgarán esa parte carnal en ellos que dice ser de Pablo o de Apolos;
para que su fe esté en el poder de Dios, y para que puedan exaltar a Cristo,
el autor de la fe.
Por lo tanto, todos deben conocerse unos a otros en el Espíritu, la vida y el poder,
y poner sus ojos en Cristo; esto mantiene a todos en humildad.
Porque los ojos de todos deben ser puestos en Jesús,
y todo hombre y mujer justos deben vivir por su fe,^
footnote:[Hebreos 10: 38]de la cual Cristo es el autor y consumador.
Mediante esta fe todo hombre puede ver a Dios, que es invisible; esta fe da la victoria.
Así, cuando la fe y la esperanza de cada uno están en el poder de Dios,
todos tienen unidad, victoria y acceso al trono de gracia de Dios;
en tal fe agradan a Dios.
Por medio de esta fe son salvos, obtienen buen testimonio,
y someten todos los montes que hay entre ellos y Dios.

=== Dos Visitas a la Casa de Isaac Penington

Durante la estancia de mi padre en Londres +++[+++dice Thomas Ellwood],
en la época de las guerras civiles, entabló amistad con la señora Springett--
quien en ese entonces era viuda, y luego se casó con Isaac Penington,
caballero--y para mantener esa relación, a veces iba a visitarlos a su casa de campo,
como en Datchet y en Causham, cerca de Reading.
Y cuando mi padre se enteró de que ellos se habían mudado a su propiedad en Chalfont,
Buckinghamshire, como a quince millas de Crowell, fue un día a visitarlos,
y regresar por la noche, llevándome con él.
Cuando llegamos ahí nos sorprendió mucho:
primero oír y luego comprobar que se habían vuelto Cuáqueros;
un pueblo del cual no teníamos conocimiento, y un nombre que, hasta entonces,
apenas habíamos oído.
Un cambio tan grande--de su comportamiento espontáneo,
elegante y pomposo que anteriormente les habíamos visto,
a una seriedad tan estricta con la que nos recibieron en ese momento--nos
sorprendió bastante y defraudó nuestra expectativa de tener una visita
tan placentera como las que solíamos tener y nos habíamos prometido.
Y como había otros forasteros con ellos,
parientes de Isaac Penington que habían llegado esa mañana desde Londres a visitarlos,
mi padre no tuvo la oportunidad, mediante una conversación privada con ellos,
de entender la razón o motivo de ese cambio.
Por mi parte, busqué, y eventualmente hallé la manera de estar en compañía de su hija,
a quien encontré recogiendo flores en el jardín, acompañada de su criada,
que también era Cuáquera.
Pero cuando me dirigí a ella,
de mi manera acostumbrada con la intención de entablar
una conversación basándome en nuestra antigua relación,
aunque me trató de forma cortés, la seriedad de su mirada y comportamiento,
a pesar de lo joven que era, me infundieron tal temor,
que no me vi con suficiente dominio de mí mismo como
para buscar más conversación con ella.
Por lo tanto,
pidiéndole disculpas por mi atrevimiento al haberme entrometido en sus paseos privados,
me retiré, pero no sin algo de confusión mental.
Nos quedamos a cenar, la cual fue muy agradable y no careció de nada,
salvo de las risas y grata conversación,
que no pudimos tener ni con ellos ni entre nosotros mismos por causa de ellos;
porque la seriedad que estaba sobre sus espíritus y semblantes
detenía la ligereza que se habría levantado en nosotros.
Sin embargo, nos quedamos hasta que el resto del grupo se despidió de ellos,
y luego nosotros también regresamos a casa, no muy contentos de nuestro viaje,
pero sin saber qué reprochar en particular.
Sin embargo, esa visita tuvo un buen efecto sobre mi padre,
quien entonces era juez de paz,
porque lo predispuso a tener una opinión y una conducta más favorables
hacia ese pueblo cuando se cruzaran en su camino.
Un tiempo después de eso, mi padre, habiendo oído más sobre el pueblo llamado Cuáqueros,
y deseando recibir información sobre sus principios,
hizo otra visita a Isaac Penington y a su esposa en su casa llamada Grange,
en Peter`'s Chalfont,
y me llevó a mí y a mis hermanas con él. Fuimos allá en el décimo mes del año 1659,
donde nos recibieron muy amablemente y nos quedamos algunos días; al menos un día más,
porque mientras estábamos ahí se convocó una reunión
en un lugar que estaba como a una milla de la casa,
a la cual fuimos invitados y fuimos gustosos.
Se llevó a cabo en una casa de campo llamada The Grove,
que antes había sido la residencia de un noble y tenía un salón muy grande,
el cual las personas llenaron completamente.
A esa reunión asistió Edward Burrough, junto con otros predicadores,
como Thomas Curtis y James Nayler; pero en ese momento nadie habló salvo Edward Burrough.
Me tocó estar sentado en un taburete junto a él,
al lado de una mesa larga en la que él se había sentado,
y bebí sus palabras con gran anhelo; porque ellas no solo alcanzaron mi entendimiento,
sino que también calentaron mi corazón con un cierto fuego,
que hasta ese día nunca había sentido a través del ministerio de ningún hombre.
Cuando la reunión terminó, nuestros amigos nos llevaron de nuevo a su casa;
y después de la cena, siendo la puesta del sol muy tardía en aquella época del año,
llamaron a los sirvientes de la familia (que eran
Cuáqueros) y todos nos sentamos en silencio.
Pero no teníamos mucho tiempo sentados,
cuando Edward Burrough comenzó a hablar entre nosotros.
Y aunque no habló por mucho tiempo, lo que dijo tocó, según supongo,
el nervio religioso de mi padre, como dice el dicho.
Y él,
habiendo sido religioso desde joven (aunque no tenía
una estrecha unión con ninguna persuasión),
y valorándose a sí mismo por el conocimiento que estimaba
tener de las diferentes doctrinas de cada denominación,
pensó que en ese momento tenía una buena oportunidad para mostrar su conocimiento,
y entonces, comenzó a poner objeciones contra lo que había sido dicho.
El tema de la conversación era la gracia universal
y gratuita de Dios para con toda la humanidad.
A eso él se opuso con el principio calvinista de la predestinación particular y personal.
Pero en su intento de defender esa indefendible doctrina,
muy pronto se halló más perdido de lo que esperaba.
Edward Burrough no le dijo mucho al respecto,
aunque lo que dijo fue directo al grano y convincente.
Pero luego intervino James Nayler,
y manejó el tema con tanta perspicacia y evidente demostración,
que su razonamiento me pareció irresistible; y supongo que mi padre lo vio así,
lo que hizo que rápidamente estuviera dispuesto a dejar la conversación.
En cuanto a Edward Burrough, era un joven vivaz, con facilidad para hablar,
y podría haber sido, por todo lo que yo sabía en ese entonces, un erudito,
lo que hizo que admirara menos su forma de razonar.
Pero lo que salió de la boca de James Nayler tuvo mayor impacto sobre mí,
porque se veía como un simple y humilde hombre de campo,
con la apariencia de un agricultor o de un pastor.
Al ver que mi papá no había sido capaz de mantener la discusión a su favor,
ellos tampoco estuvieron dispuestos a llevarla en extremo al suyo; sino que,
tratándolo con suavidad y gentileza, después de un rato dejaron la conversación,
y luego nos retiramos a nuestras respectivas habitaciones.
La mañana siguiente nos preparamos para regresar a casa, a saber, mi padre,
mi hermana menor y yo;
porque mi hermana mayor se había ido antes en una diligencia a Londres.
Y cuando comenzamos a salir, después de habernos despedido de nuestros amigos,
ellos nos acompañaron a la puerta,
donde Edward Burrough nos habló unas pocas palabras a cada uno individualmente,
según el sentido que tenía de nuestras diferentes condiciones.
Y luego de que nos fuimos, cuando ellos habían vuelto a entrar,
los Penington le preguntaron qué pensaba de nosotros.
Él les respondió (como ellos me contaron después) de esta manera: "`En cuanto al anciano,
está establecido en sus opiniones; y la joven es superficial e indiferente;
pero el joven ha sido alcanzando, y le puede ir bien si no lo pierde.`"
Y sin duda, las palabras que me había hablado,
o más bien el Espíritu por medio del cual las había hablado,
se apoderó de mí tan fuertemente, que sentí que me invadieron la tristeza y la angustia,
aunque no entendía con claridad por qué estaba angustiado.
No sabía qué me afligía, pero sabía que era algo fuera de lo normal,
y mi corazón estaba muy pesado.
Me di cuenta de que no le sucedía lo mismo a mi padre, ni a mi hermana;
porque mientras cabalgaba detrás del coche, podía escucharlos conversar placenteramente.
Pero ellos no pudieron discernir lo que me estaba pasando, porque al ir a caballo,
me mantuve fuera de su vista.
